### ISSUE TITLE
Investigate Jest over Karma

### ISSUE THREAD

**Issue by DmyMi** [ita-social-projects/OoS-Frontend#1]
Investigate [Jest](https://jestjs.io/) [Karma](https://karma-runner.github.io/latest/index.html) for running tests.

**Comment by litvinets** [comment]
[jest.docx](https://github.com/ita-social-projects/OoS-Frontend/files/5841379/jest.docx)


В файле:
1) преимущества Jest 
2) решение проблем дебагинга (2 метода)
3) методы настройки Jest

**Comment by litvinets** [comment]
a useful tutorial for debugging in vscode
https://www.basefactor.com/using-visual-studio-code-to-debug-jest-based-unit-tests
