### ISSUE TITLE
[Search field] Inconsistent error message appears when entering valid data into the search field

### ISSUE THREAD

**Issue by hanna-lenko** [ita-social-projects/OoS-Frontend#1007]
**Environment:** Win10 v21H2 64-bit, Chrome v 99.0.4844.74
**Reproducible:** sometimes – bug appears after switching web browser tabs
**Build found:** frontend: gcp-0.0.56, backend: gcp-0.0.119

**Preconditions**
- Go to OoS (https://oos.dmytrominochkin.cloud/#/) as unregistered user 
- Go to the 'Search' page by clicking 'Переглянути всі' near 'Найпопулярніші гуртки'
- The other tab with any website is opened in the same web browser

**Steps to reproduce**
1. Enter 256 chars with allowed special chars into the ‘Search’ field (allowed chars [A-Я a-я 0-9 ` ' / . , № " ' ] and space). E.g.
Душа моя озарена неземной радостью, как эти чудесные весенние утра, которыми я наслаждаюсь от всего сердца. Я совсем один и блаженствую в здешнем краю, словно созданном для таких, как я. Я так счастлив, мой друг, так упоен ощущением покоя, что искусство мо
3. Switch to another tab of web browser
4. Switch back to the tab with OoS

**Actual result**
The inconsistent error message appears ‘Пошук не може містити спеціальні символи.’
![image](https://user-images.githubusercontent.com/97878413/159254409-1f1b5a2a-c7da-4c34-9563-199131e9a0c2.png)

**Expected result**
No error message appears

**User story and test case links**
User story [#213](https://github.com/ita-social-projects/OoS-Backend/issues/213)
Test case [OS-264](https://jira.softserve.academy/browse/OS-264)

**Labels to be added**
"Bug", "pri: low", "severity: minor"

**Comment by litvinets** [comment]
fixed!

**Comment by hanna-lenko** [comment]
Verified, closed.
