### ISSUE TITLE
[UI] Inconsistent design of the ‘Workshop’ cards

### ISSUE THREAD

**Issue by hanna-lenko** [ita-social-projects/OoS-Frontend#1008]
**Environment:** Win10 v21H2 64-bit, Chrome v 99.0.4844.74
**Reproducible:** always
**Build found:** frontend: gcp-0.0.56, backend: gcp-0.0.119

**Preconditions**
Go to OoS (https://oos.dmytrominochkin.cloud/#/) as unregistered user 

**Steps to reproduce**
1. Scroll down to the area with ‘Workshop’ cards

**Actual result**
The ‘Workshop’ cards do not meet the design: address field is beyond the card’s frame
![image](https://user-images.githubusercontent.com/97878413/159258971-96837fa1-3a72-4f01-a8a0-fd6ebaa992e6.png)

**Expected result**
Design https://www.figma.com/file/YRYP4zAAchOyYMgdoeP782/MoE-%7C-Dev-Team?node-id=805%3A1552 

**Labels to be added**
"Bug", "pri: medium", "severity: trivial", Type ‘UI’

**Comment by litvinets** [comment]
fixed!

**Comment by hanna-lenko** [comment]
Verified, closed.
