### ISSUE TITLE
[Edit child UI] Error messages of the 'Місце проживання' and 'Місце навчання (заклад)' fields contain inaccuracies

### ISSUE THREAD

**Issue by AnnaDidiaieva** [ita-social-projects/OoS-Frontend#1009]
**Environment:** Windows 10 Corporate LTSC 64-bit, Google Chrome v99.0.4844.74
**Reproducible:** always (also while adding child)
**Build found:** Frontend: gcp-0.0.56, Backend: gcp-0.0.120

**Preconditions**
1. Follow link https://oos.dmytrominochkin.cloud/#/
2. Log into system as parent: 'Email'="dub@gmail.com", 'Password'="Qwert1!".
3. Select "Інформація про дитину" in the menu bar at the top right corner. At least 1 child must be created.
4. Click on the "Pen" button of the created child.

**Steps to reproduce**
1. Set incorrect value (1. Less than 10 characters; 2. More than 256 characters) in the 'Місце проживання' field.
2. Set incorrect value (1. Less than 10 characters; 2. More than 256 characters) in the 'Місце навчання (заклад)' field.
3. Look at the displayed error messages.

**Actual result**
The error messages inform the user that the minimum length is 1 character.
![1](https://user-images.githubusercontent.com/97879289/159531989-0fb70536-352f-42c3-a790-42e93710bbc8.jpg)
![2](https://user-images.githubusercontent.com/97879289/159532009-928342fc-2f52-448c-ae9d-d1a5ef9e08f4.jpg)

**Expected result**
The error messages should inform the user that the minimum length is 10 characters.
![12](https://user-images.githubusercontent.com/97879289/159532016-7dd68635-1b23-407b-b601-77c7c4e14a50.jpg)

**User story and test case links**
User story https://github.com/ita-social-projects/OoS-Frontend/issues/43
Test case: https://jira.softserve.academy/browse/OS-191

**Labels to be added**
Bug, pri: very low, severity: trivial, UI

**Comment by AnnaDidiaieva** [comment]
@litvinets 
The bug is still reproducible (also while adding child).
Please check error messages. Expected result: The error messages should inform the user that the minimum length is 10 characters, not 1.

**Comment by litvinets** [comment]
Please, verify changes according to this doc!
https://github.com/ita-social-projects/OoS-Frontend/wiki/Validation-Rules-For-All-the-Forms

PS: it was discussed with BA and new rules are applied for all the forms. Validation is simplified.
