### ISSUE TITLE
[Administrator/ provider search] Add padding to the icon 

### ISSUE THREAD

**Issue by litvinets** [ita-social-projects/OoS-Frontend#1060]
Role: Provider
url: /personal-cabinet/administration/all
![image](https://user-images.githubusercontent.com/27493959/162957356-3c3b5563-42e0-4984-bda7-df0b546ed310.png)
Should be the same as for: 
![image](https://user-images.githubusercontent.com/27493959/162957445-d5224778-66e0-4557-ac9b-85d4eb11ddf5.png)

**Comment by LeraKornienko** [comment]
done
