### ISSUE TITLE
[Edit button admin personal cabinet] - style fix

### ISSUE THREAD

**Issue by litvinets** [ita-social-projects/OoS-Frontend#1066]
edit button in the personal cabinet of the administrator should have the same styles as other buttons. should be bold 
![image](https://user-images.githubusercontent.com/27493959/162961075-6321b0b7-1a5e-4631-8cce-a00f1f993cc6.png)
![image](https://user-images.githubusercontent.com/27493959/162961663-9e0e80e7-7038-4bc3-a292-2a187c516eac.png)

**Comment by LeraKornienko** [comment]
Done
