### ISSUE TITLE
[Direction cards] Absence of number available workshops

### ISSUE THREAD

**Issue by OksanaGuz** [ita-social-projects/OoS-Frontend#1112]
**Environment:** macOS Big Sur 11.5.1; Chrome version 101.0.4951.54.
**Reproducible:** always.
**Build found:** 
gcp-0.0.73 

**Preconditions**

1. Go to OoS as unregistered user ([https://oos.dmytrominochkin.cloud/#/](https://oos.dmytrominochkin.cloud/#/)))
2. Geographic location is selected (e.g. Kyiv)
3. There is at least one registered workshop (@Гурток) with chosen direction (@Напрямок) in the selected location

**Steps to reproduce**
1. Click 'Переглянути всі' link near 'Найпопулярніші напрямки' label at the main page

**Actual result**
The new page with 'Найпопулярніші напрямки' section appears, direction cards displays
<img width="435" alt="Снимок экрана 2022-05-05 в 15 30 58" src="https://user-images.githubusercontent.com/97882565/166923953-c666a588-a9b5-420c-b896-1dd305745020.png">

**Expected result**
Direction cards displays with number of available workshops related to current direction.
<img width="391" alt="Снимок экрана 2022-05-05 в 15 31 11" src="https://user-images.githubusercontent.com/97882565/166923991-0f4f131b-c225-4f85-abf8-98818cab269a.png">

**User story and test case links**
User story  https://github.com/ita-social-projects/OoS-Backend/issues/98
Test case [OS-378](https://jira.softserve.academy/browse/OS-378)

**Labels to be added**
"Bug", Priority ("pri: medium "), Severity ("severity: minor"), Type ("UI, "Functional")

**Comment by Illya97** [comment]
Fixed

**Comment by OksanaGuz** [comment]
@Illya97 The feature appears only on the main page and on the 'Найпопулярніші напрямки' page number of available workshops is absent
<img width="1335" alt="Снимок экрана 2022-09-02 в 12 06 08" src="https://user-images.githubusercontent.com/97882565/188105304-2698bdee-72b8-4b7f-b39e-748c11894c6c.png">

**Comment by OksanaGuz** [comment]
Verified.
