### ISSUE TITLE
[Search page] Inconsistent results are displayed when workshops are filtered according to the set age range 

### ISSUE THREAD

**Issue by hanna-lenko** [ita-social-projects/OoS-Frontend#1118]
**Environment:** Win10 v21H2 64-bit, Chrome v 101.0.4951.54
**Reproducible:** always
**Build found:** frontend: gcp-0.0.73, backend: gcp-0.0.129

**Preconditions**
1. Go to OoS (https://oos.dmytrominochkin.cloud/#/) as unregistered user 
2. The location is selected (e.g. Kyiv)
3. Go to the 'Search' page (=click on "Переглянути всі" link near the "Найпопулярніші гуртки" title)

**Steps to reproduce**
1. Set the age range in the 'Обрати вік' filter option from ‘6’ to ‘10’
2. Check that workshops displayed are filtered according to the set age range
3. Verify that the total number of the workshops filtered by the age range and displayed on the page is consistent with system records. Use the following SQL script:
SELECT count(w.ID) FROM Workshops w, Addresses a
WHERE w.AddressId = a.Id
AND a.City = 'Київ'
AND w.MinAge >= 6
AND w.MaxAge <= 10;

**Actual result**
1. The age range is set from ‘6’ to ‘10’
2. The workshops displayed include results that out of the set age range: from ‘3’ to ‘16’ years, from ‘3’ years, etc. (see the screen below)
![image](https://user-images.githubusercontent.com/97878413/167368940-16eead27-0c97-4698-bef3-2a2f3142695a.png)

3. The result returned by script is ‘2’ workshops that is inconsistent with the result displayed on the ‘Search’ page – ‘51’ workshops
![image](https://user-images.githubusercontent.com/97878413/167368953-88beb770-15b0-4ecb-9dfc-83823d736de0.png)

The same bug appears when setting other age range, e.g. from ‘1’ to ‘18’, from ‘0’ to ‘1’, etc.; both for unregistered and registered user (Parent, SP).

**Expected result**
1. The age range is set from ‘6’ to ‘10’
2. The workshops displayed are filtered according to the set age range: from ‘6’ to ‘10’ years
3. The total number of the workshops filtered by the age range and displayed on the page is consistent with system records

**User story and test case links**
User story [#12](https://github.com/ita-social-projects/OoS-Backend/issues/12), User story [#70](https://github.com/ita-social-projects/OoS-Backend/issues/70) 
Test case [OS-447](https://jira.softserve.academy/browse/OS-447), Test case [OS-449](https://jira.softserve.academy/browse/OS-449)

**Labels to be added**
"Bug", "pri: high", "severity: medium"

**Comment by ViktoriiaHrytchyna** [comment]
This bug is not relevant anymore.
