### ISSUE TITLE
[Workshop page] Institution labels different from the design

### ISSUE THREAD

**Issue by OksanaGuz** [ita-social-projects/OoS-Frontend#1119]
**Environment:** macOS Big Sur 11.5.1; Chrome version 101.0.4951.54.
**Reproducible:** always.
**Build found:** 
gcp-0.0.73 

**Preconditions**

Design - https://www.figma.com/file/YRYP4zAAchOyYMgdoeP782/MoE-%7C-Dev-Team?node-id=1%3A1971
1. Go to https://oos.dmytrominochkin.cloud/#/
2. There is at least one service provider with more than 2 groups
3. Enter in search field keyword (e.g. "музика") and click on loupe icon.
4. Click on "Детальніше" button
5. Click on "Інші гуртки школи" button

**Steps to reproduce**
1. Take a look to the institution name and label.
2. Take a look to the institution name and label on a workshop card from "Інші гуртки закладу".

**Actual result**
1. On the general card label and name have blue color.
2. On a workshop card label and name have grey color.

<img width="908" alt="Снимок экрана 2022-05-09 в 13 55 46" src="https://user-images.githubusercontent.com/97882565/167397024-dae2e58d-1882-49b6-a461-97d2ed6b1884.png">

**Expected result**
In this two cases label should be grey colored and name of institution - blue colored.

<img width="773" alt="Снимок экрана 2022-05-09 в 13 57 15" src="https://user-images.githubusercontent.com/97882565/167397241-a715fe32-4956-448c-82f4-d30eb74ceb9d.png">

**User story and test case links**
User Story - https://github.com/ita-social-projects/OoS-Backend/issues/166
Test Case - https://jira.softserve.academy/browse/OS-504

**Labels to be added**
"Bug", "priority: low", "severity: trivial", Type UI

**Comment by litvinets** [comment]
According to the new req, now it is a link to the provider-details page. So initial it is gray and on hover, it is a blue link. 
Discussed with BA! If there any other questions - text me!

**Comment by OksanaGuz** [comment]
Closed according to the new req.
