### ISSUE TITLE
[Workshop page] Indentation of text from the label is different from the design

### ISSUE THREAD

**Issue by OksanaGuz** [ita-social-projects/OoS-Frontend#1120]
**Environment:** macOS Big Sur 11.5.1; Chrome version 101.0.4951.54.
**Reproducible:** always.
**Build found:**
gcp-0.0.73

**Preconditions**

Design - https://www.figma.com/file/YRYP4zAAchOyYMgdoeP782/MoE-%7C-Dev-Team?node-id=1%3A1971

1. Go to https://oos.dmytrominochkin.cloud/#/
2. There is at least one service provider with more than 2 groups
3. Enter in search field keyword (e.g. "музика") and click on loupe icon.
4. Click on "Детальніше" button
5. Click on "Інші гуртки школи" button

**Steps to reproduce**
1. Take a look to the institution name and label.

**Actual result**

Indent of item from institution name is not centered and shorter than indent in the design.

<img width="402" alt="Снимок экрана 2022-05-09 в 14 25 48" src="https://user-images.githubusercontent.com/97882565/167400664-9f9af80d-a2cf-40c5-82cc-aa742eb3e3fd.png">

**Expected result**

The indent of item from institution name should be the same as on the design.

<img width="656" alt="Снимок экрана 2022-05-09 в 14 26 23" src="https://user-images.githubusercontent.com/97882565/167400638-ab2792ec-3b32-4868-b2b8-fbf5d9d559a5.png">

**User story and test case links**
User Story - https://github.com/ita-social-projects/OoS-Backend/issues/166
Test Case - https://jira.softserve.academy/browse/OS-504

**Labels to be added**
"Bug", Priority ("pri: medium "), Severity ("severity: trivial"), Type ("UI").

**Comment by litvinets** [comment]
According to the new req, now it is a link to the provider-details page. So initial it is gray and on hover, it is a blue link.
Discussed with BA! If there any other questions - text me!

**Comment by OksanaGuz** [comment]
@litvinets The bug with indent of item from institution name. Name is too close and not centered to the icon.

**Comment by LeraKornienko** [comment]
Done
