### ISSUE TITLE
[Create workshop] No ‘Гурток/Секція/Клас’ drop-down box is available when SP creates a workshop

### ISSUE THREAD

**Issue by hanna-lenko** [ita-social-projects/OoS-Frontend#1121]
**Environment:** Win10 v21H2 64-bit, Chrome v 101.0.4951.54
**Reproducible:** always
**Build found:** frontend: gcp-0.0.73, backend: gcp-0.0.130

**Preconditions**
1. Follow the link https://oos.dmytrominochkin.cloud/#/
2. Log into OoS website as SP (e.g. 'email'="didivan@gmail.com", 'Password'="Qwerty123!")
3. Select «Мої гуртки» in the menu bar at the top right corner.
4. At least 1 workshop has already been registered or not.
5. Click on the “Додати гурток” button.

**Steps to reproduce**
1. Select the valid value from the ‘Гурток/Секція/Клас’ drop-down box (e.g. ‘Клас’)

**Actual result**
1. There is no drop-down box with a choice ‘Гурток’ or ‘Секція’ or ‘Клас’ when creating a new workshop 

**Expected result**
The drop-down box with a choice ‘Гурток’ or ‘Секція’ or ‘Клас’ is enabled when SP creates a new workshop. [Link on design ](https://www.figma.com/file/YRYP4zAAchOyYMgdoeP782/MoE-%7C-Dev-Team?node-id=805%3A172)
![image](https://user-images.githubusercontent.com/97878413/167405427-052b847c-945f-4c9b-b218-3dd251d6debc.png)

**User story and test case links**
User story [#55](https://github.com/ita-social-projects/OoS-Backend/issues/55)  
Test case [OS-351](https://jira.softserve.academy/browse/OS-351)

**Labels to be added**
"Bug", "pri: high", "severity: medium"

**Comment by litvinets** [comment]
This is no more relevant! 
Гурток, секція, клас was converted to напрямок, відділ, клас and displayed on teh second page. I think this issue can be closed. Text me if there si any questions!

**Comment by hanna-lenko** [comment]
Closed due to updates in requirements
