### ISSUE TITLE
[Create workshop] SP cannot enter the email with valid max length of 256 chars when creating a workshop

### ISSUE THREAD

**Issue by hanna-lenko** [ita-social-projects/OoS-Frontend#1122]
**Environment:** Win10 v21H2 64-bit, Chrome v 101.0.4951.54
**Reproducible:** always
**Build found:** frontend: gcp-0.0.73, backend: gcp-0.0.130

**Preconditions**
1.	Follow the link https://oos.dmytrominochkin.cloud/#/
2.	Log into OoS website as SP (e.g. 'email'="didivan@gmail.com", 'Password'="Qwerty123!")
3.	Select «Мої гуртки» in the menu bar at the top right corner.
4.	At least 1 workshop has already been registered or not.
5.	Click on the “Додати гурток” button.
6.	Set the valid value into the “Назва“ field (e.g. ‘Гурток тестовий’)
7.	Set the valid value into the “Телефон“ field (e.g. ‘123456789’)

**Steps to reproduce**

1. Set the valid value into the “Емейл“ field with length of 256 characters (with all symbols ". - _" and "@"). E.g. ‘RROWalG3ic7bR1AIcKune0PG7DGcqvBZH8DkcQhbiV8uXHkCadkARCm98mpnnIs5q3N6mUU1HQTM7Iatq1Pbs3zbumUdCi8N4caTvlqQC3YZ3ASDsThRHdSda9m1ACbBISfqosJxlRnuZcSwjJIGFCwxirx3nuEf9vY4HjyZUiIeNeQaJcQ1vppMT8SZ4ofuEGJC6Hsi1zKdMeYYI7hncUWjjB0NicRIm1x2l4KY90wuIb3XYDpFVU@gmail.com’

**Actual result**

1. The field is highlighted red, the error message ‘Введіть коректний імейл’ appears. 
![image](https://user-images.githubusercontent.com/97878413/167406369-1fa624f7-5a42-4fee-a149-d38ddeac4df3.png)

Note: the error message disappears when entering email with length of 74 chars (e.g. ‘RROWalG3ic7i8NEf9vY4HjyZUiIeNeQafH1zKdMeYYI7hncUWjjB0NicRIm1x2l4@gmail.com’)

**Expected result**
1. The set value with length of 256 characters (with all symbols ". - _" and "@") is displayed in the “Емейл“ field, no error message appears

**User story and test case links**
User story [#572]( https://github.com/ita-social-projects/OoS-Backend/issues/572), User story [#55](https://github.com/ita-social-projects/OoS-Backend/issues/55)
Test case [OS-351](https://jira.softserve.academy/browse/OS-351)

**Comment by litvinets** [comment]
Please, verify changes according to this doc!
https://github.com/ita-social-projects/OoS-Frontend/wiki/Validation-Rules-For-All-the-Forms

PS: it was discussed with BA and new rules are applied for all the forms. Validation is simplified.

**Comment by hanna-lenko** [comment]
Closed due to updates in requirements
