### ISSUE TITLE
[Create workshop] The ‘Директор’ field, which is absent on the design, appears when creating a workshop

### ISSUE THREAD

**Issue by hanna-lenko** [ita-social-projects/OoS-Frontend#1124]
**Environment:** Win10 v21H2 64-bit, Chrome v 101.0.4951.54
**Reproducible:** always
**Build found:** frontend: gcp-0.0.73, backend: gcp-0.0.130

**Preconditions**
1. Follow the link https://oos.dmytrominochkin.cloud/#/
2. Log into OoS website as SP (e.g. 'email'="didivan@gmail.com", 'Password'="Qwerty123!")
3. Select «Мої гуртки» in the menu bar at the top right corner
4. At least 1 workshop has already been registered or not
5. Click on the “Додати гурток” button
6. Fill in the mandatory fields on the 'Про заклад' section 

**Steps to reproduce**
Go to the 'Опис' section of the 'НОВИЙ ГУРТОК' page by clicking the ‘Далі’ button

**Actual result**

The 'Опис' section of the 'НОВИЙ ГУРТОК' page appears. The mandatory field ‘Директор’ is present on the page
![image](https://user-images.githubusercontent.com/97878413/167416495-91310db9-aa01-421a-9b33-7ca09378c626.png)

The [design]( https://www.figma.com/file/YRYP4zAAchOyYMgdoeP782/MoE-%7C-Dev-Team?node-id=7162%3A6366) and User story [#55](https://github.com/ita-social-projects/OoS-Backend/issues/55) do not include the 'Директор' field

**Expected result**
The 'Опис' section of the 'НОВИЙ ГУРТОК' page does not contain the ‘Директор’ field

**User story and test case links**
User story [#55](https://github.com/ita-social-projects/OoS-Backend/issues/55)
Test case [OS-351](https://jira.softserve.academy/browse/OS-351)

**Labels to be added**
"Bug", "pri: medium", "severity: low"

**Comment by litvinets** [comment]
it is no relevant anymore, this field was included as mandatory later. maybe should be confirmed again with BA

**Comment by litvinets** [comment]
delete filed director from the workshop

**Comment by litvinets** [comment]
fixed!
