### ISSUE TITLE
[Create workshop] The ‘Ключові слова’ field is mandatory when creating a workshop

### ISSUE THREAD

**Issue by hanna-lenko** [ita-social-projects/OoS-Frontend#1125]
**Environment:** Win10 v21H2 64-bit, Chrome v 101.0.4951.54
**Reproducible:** always
**Build found:** frontend: gcp-0.0.73, backend: gcp-0.0.130

**Preconditions**

1. Follow the link https://oos.dmytrominochkin.cloud/#/
2. Log into OoS website as SP (e.g. 'email'="didivan@gmail.com", 'Password'="Qwerty123!")
3. Select «Мої гуртки» in the menu bar at the top right corner
4. At least 1 workshop has already been registered or not
5. Click on the “Додати гурток” button
6. Fill in the mandatory fields on the 'Про заклад' section 

**Steps to reproduce**
Go to the 'Опис' section of the 'НОВИЙ ГУРТОК' page by clicking the ‘Далі’ button

**Actual result**
The 'Опис' section of the 'НОВИЙ ГУРТОК' page appears. The ‘Ключові слова’ field is mandatory 
![image](https://user-images.githubusercontent.com/97878413/167419122-846341c2-75aa-42b0-a33a-3baa835fbc07.png)

**Expected result**
The ‘Ключові слова’ field is not mandatory when creating a workshop, see the [design]( https://www.figma.com/file/YRYP4zAAchOyYMgdoeP782/MoE-%7C-Dev-Team?node-id=7162%3A6366)

**User story and test case links**
User story [#55](https://github.com/ita-social-projects/OoS-Backend/issues/55)
Test case [OS-351](https://jira.softserve.academy/browse/OS-351)

**Labels to be added**
"Bug", "pri: medium", "severity: low"

**Comment by litvinets** [comment]
This should be mandatory because for the correct search process on the website. Maybe should be clarified again with BA. it is required in this doc 
https://github.com/ita-social-projects/OoS-Frontend/wiki/Validation-Rules-For-All-the-Forms

**Comment by litvinets** [comment]
remove required validator from key words

**Comment by litvinets** [comment]
fixed!

**Comment by hanna-lenko** [comment]
Verified and closed
