### ISSUE TITLE
[Create workshop] SP cannot create a workshop without filling the fields about a teacher

### ISSUE THREAD

**Issue by hanna-lenko** [ita-social-projects/OoS-Frontend#1126]
**Environment:** Win10 v21H2 64-bit, Chrome v 101.0.4951.54
**Reproducible:** always
**Build found:** frontend: gcp-0.0.73, backend: gcp-0.0.130

**Preconditions**
1. Follow the link https://oos.dmytrominochkin.cloud/#/
2. Log into OoS website as SP (e.g. 'email'="didivan@gmail.com", 'Password'="Qwerty123!")
3. Select «Мої гуртки» in the menu bar at the top right corner
4. At least 1 workshop has already been registered or not
5. Click on the “Додати гурток” button
6. Fill in the mandatory fields on the 'Про заклад', ‘Опис’ and ‘Контакти’ sections 

**Steps to reproduce**
1. Go to the 'Викладачі' section of the 'НОВИЙ ГУРТОК' page by clicking the ‘Далі’ button
2. Finish the workshop creation by clicking the ‘Зберегти’ ('Завершити') button

**Actual result**
1. The 'Викладачі' section of the 'НОВИЙ ГУРТОК' page appears, all fields are marked as mandatory. 
2.The fields of the 'Викладачі' section are highlighted with red, the error messages appear. SP cannot create a workshop without filling the fields about a teacher
![image](https://user-images.githubusercontent.com/97878413/167424273-19d11ad1-a247-48f4-a476-786a74bd5db5.png)

**Expected result**
1. The fields of ‘Викладачі’ section are NOT mandatory when creating a workshop.
2. SP can create a workshop without filling the fields about a teacher. Please see the comment to User story [#55](https://github.com/ita-social-projects/OoS-Backend/issues/55)
![image](https://user-images.githubusercontent.com/97878413/167424360-b1e7f97c-9ca6-4fe1-90e0-05f74781bc2e.png)

**User story and test case links**
User story [#55](https://github.com/ita-social-projects/OoS-Backend/issues/55)
Test case [OS-351](https://jira.softserve.academy/browse/OS-351)

**Labels to be added**
"Bug", "pri: medium", "severity: major"

**Comment by litvinets** [comment]
fixed!

**Comment by litvinets** [comment]
fixed!

**Comment by ladikdadik** [comment]
Can`t be retested, appeared new bug : 
On second step of creating new workshop, on page "Опис",  "Підпорядкування" dropdown list DONT show any options and "Підпорядкування" dropdown list isn`t marked as mandatory but it is.

![image](https://user-images.githubusercontent.com/97900899/183039466-f08d47b3-e64a-456b-9527-aa697143becd.png)

**Comment by litvinets** [comment]
@ladikdadik verify please

**Comment by litvinets** [comment]
fixed!

**Comment by ViktoriiaHrytchyna** [comment]
This bug is fixed.
