### ISSUE TITLE
[Create workshop] Incorrect design of the system message displayed when SP creates a workshop

### ISSUE THREAD

**Issue by hanna-lenko** [ita-social-projects/OoS-Frontend#1128]
**Environment:** Win10 v21H2 64-bit, Chrome v 101.0.4951.54
**Reproducible:** always
**Build found:** frontend: gcp-0.0.73, backend: gcp-0.0.130

**Preconditions**
1. Follow the link https://oos.dmytrominochkin.cloud/#/
2. Log into OoS website as SP (e.g. 'email'="didivan@gmail.com", 'Password'="Qwerty123!")
3. Select «Мої гуртки» in the menu bar at the top right corner
4. At least 1 workshop has already been registered or not
5. Click on the “Додати гурток” button
6. Fill in the mandatory fields on the 'Про заклад', ‘Опис’, ‘Контакти’, ‘Викладачі’ sections 

**Steps to reproduce**
Finish the workshop creation by clicking the ‘Зберегти’ ('Завершити') button

**Actual result**
The "Гуртки" page is opened with the new workshop created. The system message displayed at the top of the page does not meet the design:
1. Text of the message is ‘Гурток створено!' 
![image](https://user-images.githubusercontent.com/97878413/167431930-a1caf651-fd42-4fcd-b0f2-9b8739036220.png)

2. The alignment of ‘x’ button is broken 
![image](https://user-images.githubusercontent.com/97878413/167432755-b21766bd-dbcf-4f06-9c1b-d1146fcd581e.png)

**Expected result**
The "Гуртки" page is opened with the new workshop created. The system message meets the [design](https://www.figma.com/file/YRYP4zAAchOyYMgdoeP782/MoE-%7C-Dev-Team?node-id=805%3A28)
1. Text of the message is 'Дякуємо! Новий гурток успішно доданий.'
2. The alignment of ‘x’ button is according to design

![image](https://user-images.githubusercontent.com/97878413/167432206-63f07a7a-3aef-4a7e-8503-eca3324bd9f2.png)

**User story and test case links**
User story [#55](https://github.com/ita-social-projects/OoS-Backend/issues/55)
Test case [OS-351](https://jira.softserve.academy/browse/OS-351)

**Labels to be added**
"Bug", "pri: low", "severity: trivial"

**Comment by koliapatskal** [comment]
@OksanaGuz, can you please verify this fix? 
I have provided the screenshot of my fix in this pull request
https://github.com/ita-social-projects/OoS-Frontend/pull/1695

**Comment by OksanaGuz** [comment]
@koliapatskal for now when new workshop is **created** the displayed system message is - "Гурток оновлено!"
<img width="708" alt="Снимок экрана 2022-10-03 в 14 13 11" src="https://user-images.githubusercontent.com/97882565/193564118-ff097645-c46d-4152-9afd-2bf8335e46a9.png">

**Comment by koliapatskal** [comment]
Fixed

**Comment by ViktoriiaHrytchyna** [comment]
This bug is fixed.
