### ISSUE TITLE
[Applying for a workshop] Incorrect behavior is displayed when editing the child's information

### ISSUE THREAD

**Issue by AnnaDidiaieva** [ita-social-projects/OoS-Frontend#1129]
**Environment:** Windows 10 Corporate LTSC 64-bit, Google Chrome v100.0.4896.127
**Reproducible:** always
**Build found:** Frontend: gcp-0.0.75, Backend: gcp-0.0.130 

**Preconditions**
1. Follow the link https://oos.dmytrominochkin.cloud/#/
2. Log into system as a Parent (e.g. 'email'="teteruk@gmail.com", 'Password'="Teteruk1!").
3. Open any workshop's page by clicking the "Детальніше" button on the workshop card.
4. Click on the 'Подати заяву' button.
5. The 'Application' page is opened.
6. Choose the child from the "Виберіть дитину" drop-down list.

**Steps to reproduce**
1. Click on the 'Редагувати' button in the 'Дані про дитину' field.
2. Change data in the 'Прізвище' field (e.g. 'Тетерів').
3. Click on the 'Зберегти' button.

**Actual result**
The user is redirected to his Personal Cabinet on the 'Інформація про дитину' tab. 
https://user-images.githubusercontent.com/97879289/167610200-47b19cf8-b9ef-4a54-a4cb-0ac9d4e42978.mp4

**Expected result**
The user is redirected to the 'Application' page from the preconditions. The new data of the 'Прізвище' field (e.g. 'Тетерів') is displayed in the 'Дані про дитину' field.

**User story and test case links**
User story https://github.com/ita-social-projects/OoS-Backend/issues/131
Test case: [OS-433](https://jira.softserve.academy/browse/OS-433)

**Labels to be added**
Bug, pri: medium, severity: major, functional

**Comment by litvinets** [comment]
fixed!

**Comment by OksanaGuz** [comment]
Verified.
