### ISSUE TITLE
[Registration form] Typo in text under "Пароль" field in registration form as Parent or Service provider

### ISSUE THREAD

**Issue by ladikdadik** [ita-social-projects/OoS-Frontend#1130]
**Environment:** Windows 10 x64(86), Google Chrome 101.0.4951.54 ver.
**Reproducible:** always
**Build found:** frontend: gcp-0.0.73, backend: gcp-0.0.129

**Preconditions**
1. Go to https://oos.dmytrominochkin.cloud/#/ as unregistered user.

**Steps to reproduce**
1. Click on "УВІЙТИ/ЗАРЕЄСТРУВАТИСЯ" button in header
2. Pay attention to text under "Пароль" field

**Actual result**
Text under "Пароль" field is written "Пароль має містити мінімум 6 символів".

![image](https://user-images.githubusercontent.com/97900899/167613949-99e26c3c-9f5f-4ca6-a0f8-04e68714b86a.png)

**Expected result**
Text under "Пароль" field is written "Пароль має містити мінімум 8 символів".

![image](https://user-images.githubusercontent.com/97900899/167615969-947cc449-e560-4fb1-857c-677d95d6ab6f.png)

**User story and test case links**
[#37 Story](https://github.com/ita-social-projects/OoS-Backend/issues/37)
[Test case OS-528](https://jira.softserve.academy/browse/OS-528)
[Test case OS-531](https://jira.softserve.academy/browse/OS-531)

**Labels to be added**
"Bug", Priority ("pri: low"), Severity ("severity: trivial"), Type ("UI").

**Comment by litvinets** [comment]
fixed

**Comment by ladikdadik** [comment]
verified and closed!
