### ISSUE TITLE
[Registration form] Missing additional text under "ЗАРЕЄСТРУВАТИСЯ" text in registration form as Parent either Service provider

### ISSUE THREAD

**Issue by ladikdadik** [ita-social-projects/OoS-Frontend#1131]
Environment: Windows 10 x64(86), Google Chrome 101.0.4951.54 ver.
Reproducible: always
Build found: frontend: gcp-0.0.73, backend: gcp-0.0.129

**Preconditions**
1. Go to https://oos.dmytrominochkin.cloud/#/ as unregistered user.

**Steps to reproduce**
1. Click on "УВІЙТИ/ЗАРЕЄСТРУВАТИСЯ" button in header
2. Pay attention to absence of "Щоб мати змогу подавати заявки у гуртки або стати надавачем послуг" text under "ЗАРЕЄСТРУВАТИСЯ" text.

**Actual result**
"Щоб мати змогу подавати заявки у гуртки або стати надавачем послуг" text is absent under "ЗАРЕЄСТРУВАТИСЯ" text.

![image](https://user-images.githubusercontent.com/97900899/167614825-8a4fda16-4162-4d62-a519-a839cde13e82.png)

**Expected result**
"Щоб мати змогу подавати заявки у гуртки або стати надавачем послуг" text is present under "ЗАРЕЄСТРУВАТИСЯ" text.

![image](https://user-images.githubusercontent.com/97900899/167616225-1f4d64bd-388a-40c1-b7d0-d5e77ae56bf2.png)

**User story and test case links**
[#37 Story](https://github.com/ita-social-projects/OoS-Backend/issues/37)

[Test case 528](https://jira.softserve.academy/browse/OS-528)
[Test case 531](https://jira.softserve.academy/browse/OS-531)

**Labels to be added**
"Bug", Priority ("pri: low"), Severity ("severity: trivial"), Type ("UI")

**Comment by litvinets** [comment]
fixed!

**Comment by ladikdadik** [comment]
verified and closed
