### ISSUE TITLE
[Applying for a workshop] The 'Скасувати' button doesn't cancel the applying process

### ISSUE THREAD

**Issue by AnnaDidiaieva** [ita-social-projects/OoS-Frontend#1133]
**Environment:** Windows 10 Corporate LTSC 64-bit, Google Chrome v100.0.4896.127
**Reproducible:** always
**Build found:** Frontend: gcp-0.0.75, Backend: gcp-0.0.130

**Preconditions**
1. Follow the link https://oos.dmytrominochkin.cloud/#/
2. Log into system as a Parent (e.g. 'email'="[teteruk@gmail.com](mailto:teteruk@gmail.com)", 'Password'="Teteruk1!").
3. Open any workshop's page by clicking the "Детальніше" button on the workshop card.

**Steps to reproduce**
1. Click on the 'Подати заяву' button.
2. Click on the “Скасувати” button.

**Actual result**
The 'Скасувати' button doesn't cancel the applying process.
https://user-images.githubusercontent.com/97879289/167614427-e24e6b8b-246f-490e-b803-529d2f840272.mp4

**Expected result**
The 'Скасувати' button has to cancel the applying process and take the user back to the main page.
![скасувати](https://user-images.githubusercontent.com/97879289/167614379-fa6c8cb5-e86e-4fc8-b139-a6b4a7b2c864.jpg)

**User story and test case links**
User story https://github.com/ita-social-projects/OoS-Backend/issues/131
Test case: [OS-430](https://jira.softserve.academy/browse/OS-430)

**Labels to be added**
Bug, pri: medium, severity: major, functional

**Comment by litvinets** [comment]
fixed!

**Comment by AnnaDidiaieva** [comment]
Verified
