### ISSUE TITLE
[Applying for a workshop] Inconsistency of the "Виберіть дитину" drop-down list area with the design

### ISSUE THREAD

**Issue by AnnaDidiaieva** [ita-social-projects/OoS-Frontend#1136]
**Environment:** Windows 10 Corporate LTSC 64-bit, Google Chrome v100.0.4896.127
**Reproducible:** always
**Build found:** Frontend: gcp-0.0.50, Backend: gcp-0.0.101

**Preconditions**
1. Follow the link https://oos.dmytrominochkin.cloud/#/
2. Log into system as a Parent (e.g. 'email'="[teteruk@gmail.com](mailto:teteruk@gmail.com)", 'Password'="Teteruk1!").
3. Open any workshop's page by clicking the "Детальніше" button on the workshop card.
4. Click on the 'Подати заяву' button.
5. The 'Application' page is opened.
6. Choose the child from the "Виберіть дитину" drop-down list.

**Steps to reproduce**
Look at the "Виберіть дитину" drop-down list area.

**Actual result**
1. There is no grey line above the "Виберіть дитину" drop-down list.
![9](https://user-images.githubusercontent.com/97879289/167633628-2324b2de-ace4-4b49-b995-3aade97747aa.jpg)
2. The 'Додати ще одну дитину' button doesn't meet the design. 
![3](https://user-images.githubusercontent.com/97879289/167633645-e89ae1b6-7582-4cb6-addf-7ef5aab4a975.jpg)
3. The data in the "Виберіть дитину" field is not displayed in the order as in the "Дані про дитину" textbox.
![8](https://user-images.githubusercontent.com/97879289/167633650-f1ed56e8-771d-42fc-8594-143601d2d5da.jpg)

**Expected result**
1. There has to be grey line above the "Виберіть дитину" drop-down list.
![99](https://user-images.githubusercontent.com/97879289/167633708-788ac67e-1452-4180-80fd-c934f95e86e8.jpg)
2. The 'Додати дитину' button has to meet the design. The grey text 'Немає дитини у списку?' has to be displayed to the left of the button according to the mock-up.
![33](https://user-images.githubusercontent.com/97879289/167633726-5a2e6938-7fb3-461f-84fd-e223528b3722.jpg)
3. The data in the "Виберіть дитину" field is displayed in the order as in the "Дані про дитину" textbox according to the mock-up.
![88](https://user-images.githubusercontent.com/97879289/167633790-0ead7c28-23f6-44cd-a757-b1a15f937ce2.jpg)

**User story and test case links**
User story https://github.com/ita-social-projects/OoS-Backend/issues/131

**Labels to be added**
Bug, pri: very low, severity: trivial, UI

**Comment by Illya97** [comment]
FIxed

**Comment by ladikdadik** [comment]
verified and closed!
