### ISSUE TITLE
[Applying for a workshop] The 'Скасувати' and 'Відправити' buttons are not displayed correctly

### ISSUE THREAD

**Issue by AnnaDidiaieva** [ita-social-projects/OoS-Frontend#1140]
**Environment:** Windows 10 Corporate LTSC 64-bit, Google Chrome v100.0.4896.127
**Reproducible:** always
**Build found:** Frontend: gcp-0.0.50, Backend: gcp-0.0.101

**Preconditions**
1. Follow the link https://oos.dmytrominochkin.cloud/#/
2. Log into system as a Parent (e.g. 'email'="[teteruk@gmail.com](mailto:teteruk@gmail.com)", 'Password'="Teteruk1!").
3. Open any workshop's page by clicking the "Детальніше" button on the workshop card.
4. Click on the 'Подати заяву' button.
5. The 'Application' page is opened.

**Steps to reproduce**
Look at the 'Скасувати' and 'Відправити' buttons at the bottom of the page.

**Actual result**
The 'Скасувати' and 'Відправити' buttons are not displayed in uppercase letters.
![5](https://user-images.githubusercontent.com/97879289/167640416-a52a78b3-ad9c-44cc-8764-51b8016b5650.jpg)

**Expected result**
The 'Скасувати' and 'Відправити' buttons should be displayed in uppercase letters according to the mock-up.
![55](https://user-images.githubusercontent.com/97879289/167640442-ee62322b-3f5f-48ef-b32a-951084834e80.jpg)

**User story and test case links**
User story https://github.com/ita-social-projects/OoS-Backend/issues/131

**Labels to be added**
Bug, pri: very low, severity: trivial, UI

**Comment by Illya97** [comment]
Fixed

**Comment by ladikdadik** [comment]
verified and closed!
