### ISSUE TITLE
[Applying for a workshop] Inconsistency of the 'Application' page with the design

### ISSUE THREAD

**Issue by AnnaDidiaieva** [ita-social-projects/OoS-Frontend#1141]
**Environment:** Windows 10 Corporate LTSC 64-bit, Google Chrome v100.0.4896.127
**Reproducible:** always
**Build found:** Frontend: gcp-0.0.50, Backend: gcp-0.0.101

**Preconditions**
1. Follow the link https://oos.dmytrominochkin.cloud/#/
2. Log into system as a Parent (e.g. 'email'="[teteruk@gmail.com](mailto:teteruk@gmail.com)", 'Password'="Teteruk1!").
3. Open any workshop's page by clicking the "Детальніше" button on the workshop card.
4. Click on the 'Подати заяву' button.
5. The 'Application' page is opened.
6. Choose the child from the "Виберіть дитину" drop-down list.

**Steps to reproduce**
Look at the 'Application' page.

**Actual result**
1. There is no indents after 'Дані про дитину' and 'Дані про батьків' fields.
![4](https://user-images.githubusercontent.com/97879289/167641685-21a0e48d-fedc-4abf-9594-409d2cb5abf5.jpg)
2. There is no indent after the workshop name. The name of the school doesn't match the design.
![7](https://user-images.githubusercontent.com/97879289/167641715-c4749401-fbaa-4aea-9fa9-54cc9d25582e.jpg)
3. The 'Телефон' field's data is not displayed according to the mock-up.
![6](https://user-images.githubusercontent.com/97879289/167641735-0ac4ce48-9478-4074-82be-df7c8daca855.jpg)

**Expected result**
1. There should be indents after 'Дані про дитину' and 'Дані про батьків' fields according to the mock-up.
![44](https://user-images.githubusercontent.com/97879289/167643416-389f3318-4b4a-4028-8fb9-c20f717538b6.jpg)
2. There should be an indent after the workshop name. The name of the school has to match the design.
![77](https://user-images.githubusercontent.com/97879289/167641793-2b226feb-5e94-40c8-bb61-87bad0bd94b9.jpg)
3. The 'Телефон' field's data should be displayed according to the mock-up.
![66](https://user-images.githubusercontent.com/97879289/167641811-1dc99f9d-0aaf-40e0-859e-2a8c62de22b2.jpg)

**User story and test case links**
User story https://github.com/ita-social-projects/OoS-Backend/issues/131

**Labels to be added**
Bug, pri: very low, severity: trivial, UI

**Comment by ladikdadik** [comment]
verified and closed!
