### ISSUE TITLE
[Applying for a workshop] Inconsistency of the checkboxes on the 'Application' page with the design

### ISSUE THREAD

**Issue by AnnaDidiaieva** [ita-social-projects/OoS-Frontend#1142]
**Environment:** Windows 10 Corporate LTSC 64-bit, Google Chrome v100.0.4896.127
**Reproducible:** always
**Build found:** Frontend: gcp-0.0.50, Backend: gcp-0.0.101

**Preconditions**
1. Follow the link https://oos.dmytrominochkin.cloud/#/
2. Log into system as a Parent (e.g. 'email'="[teteruk@gmail.com](mailto:teteruk@gmail.com)", 'Password'="Teteruk1!").
3. Open any workshop's page by clicking the "Детальніше" button on the workshop card.
4. Click on the 'Подати заяву' button.
5. The 'Application' page is opened.

**Steps to reproduce**
Look at the checkboxes on the 'Application' page.

**Actual result**
1. The alignment of the checkboxes text on the 'Application' page is not displayed according to the mock-up.
![1](https://user-images.githubusercontent.com/97879289/167665519-77189fd7-8963-46f0-ae9c-7b38bd4dbd2d.jpg)
2. There is a lack of space between words. Also, spelling mistake exists.
![2](https://user-images.githubusercontent.com/97879289/167664437-ed40baa9-8c39-445f-ad75-c946066ce3c0.jpg)

**Expected result**
1. The alignment of the checkboxes text on the 'Application' page is displayed according to the mock-up.
![11](https://user-images.githubusercontent.com/97879289/167664452-b3a66195-3d02-4c9c-ad9d-59fbd06032ac.jpg)
2. There is a space between words. Also, spelling mistakes shouldn't exist.
![22](https://user-images.githubusercontent.com/97879289/167664464-42bd6734-6d9e-4f13-9b5f-1ecc2db9b52c.jpg)

**User story and test case links**
User story https://github.com/ita-social-projects/OoS-Backend/issues/131

**Labels to be added**
Bug, pri: very low, severity: trivial, UI

**Comment by AnnaDidiaieva** [comment]
@perepichai The bug is still reproducible. The alignment of the checkboxes text on the 'Application' page is not displayed according to the mock-up.

**Comment by ViktoriiaHrytchyna** [comment]
This bug is fixed.
