### ISSUE TITLE
[Create workshop] Broken red highlight of mandatory fields when creating a workshop

### ISSUE THREAD

**Issue by hanna-lenko** [ita-social-projects/OoS-Frontend#1143]
**Environment:** Win10 v21H2 64-bit, Chrome v 101.0.4951.54
**Reproducible:** always
**Build found:** frontend: gcp-0.0.75, backend: gcp-0.0.130

**Preconditions**
1. Follow the link https://oos.dmytrominochkin.cloud/#/
2. Log into OoS website as SP (e.g. 'email'="didivan@gmail.com", 'Password'="Qwerty123!")
3. Select «Мої гуртки» in the menu bar at the top right corner
4. At least 1 workshop has already been registered or not
5. Click on the “Додати гурток” button

**Steps to reproduce**
Leave the fields of 'Про гурток' section empty and click the ‘Далі’ button

**Actual result**
The mandatory fields are highlighted with red, the error messages ‘Це поле є обов’язковим’ appear. The red highlight of ‘Дні/Години’ is broken, see the screen below
![image](https://user-images.githubusercontent.com/97878413/167805101-2a777b48-966b-4c4e-8d8a-0f0c15442b18.png)

**Expected result**
The mandatory fields are highlighted with red - along the contour of the corresponding field, the error messages ‘Це поле є обов’язковим’ appear

**User story and test case links**
User story [#55](https://github.com/ita-social-projects/OoS-Backend/issues/55)
Test case [OS-350](https://jira.softserve.academy/browse/OS-350)

**Labels to be added**
"Bug", “UI”, "pri: low", "severity: trivial"

**Comment by litvinets** [comment]
fixed!
