### ISSUE TITLE
[Registration form SP] "Зареєструватися" button is active when checkboxes are not ticked

### ISSUE THREAD

**Issue by OksanaGuz** [ita-social-projects/OoS-Frontend#1147]
**Environment:** macOS Big Sur 11.5.1; Chrome version 101.0.4951.54.
**Reproducible:** always.
**Build found:**
gcp-0.0.73

**Preconditions**
1. Go to [https://oos.dmytrominochkin.cloud/#](https://oos.dmytrominochkin.cloud/)
2. Click on "Увійти/Зареєструватися" button in header.
3. Clicks on "Зареєструватися" hyperlink.
4. Click on "Зареєструватися як надавач послуг" button.

**Steps to reproduce**

1. Fill all mandatory fields
2. Take a look to "Зареєструватися" button

**Actual result**
"Зареєструватися" button is enable.

<img width="946" alt="Снимок экрана 2022-05-11 в 14 09 09" src="https://user-images.githubusercontent.com/97882565/167837130-727e58a2-c211-4d93-95ff-0291426c1f44.png">

**Expected result**
"Зареєструватися" button is disable if checkboxes not ticked.

<img width="348" alt="Снимок экрана 2022-05-11 в 14 17 21" src="https://user-images.githubusercontent.com/97882565/167837229-50bc27f3-3a96-4a54-92eb-6196e2f7990d.png">

**User story and test case links**
US - https://github.com/ita-social-projects/OoS-Backend/issues/312
TC - [OS-561](https://jira.softserve.academy/browse/OS-561)

**Labels to be added**
"Bug", Priority ("pri: medium "), Severity ("severity: major"), Type ("UI, "Functional")

**Comment by litvinets** [comment]
fixed

**Comment by OksanaGuz** [comment]
Verified.
