### ISSUE TITLE
[Реєстрація нового закладу] "Далі" button is disabled when all mandatory fields are filled

### ISSUE THREAD

**Issue by OksanaGuz** [ita-social-projects/OoS-Frontend#1148]
**Environment:** macOS Big Sur 11.5.1; Chrome version 101.0.4951.54.
**Reproducible:** always.
**Build found:** gcp-0.0.73

**Preconditions**

1. Go to [https://oos.dmytrominochkin.cloud/#](https://oos.dmytrominochkin.cloud/)
2. Click on "Увійти/Зареєструватися" button in top right corner of header
3. Click on "Зареєструватися" hyperlink
4. Click on "Надавач послуг" button
5. Fill all mandatory fields with valid data and tick all checkboxes
6. Click on "Зареєструватися" button

**Steps to reproduce**
1. Fill all mandatory fields on the "Реєстрація нового закладу" page
2. Take a look to the "Далі" button

**Actual result**

"Далі" button is disable. User able go to the next step by clicking on "Контакти" section

<img width="308" alt="Снимок экрана 2022-05-11 в 14 47 05" src="https://user-images.githubusercontent.com/97882565/167842384-aa4c812f-ba09-4773-8606-b52bf3370d03.png">

**Expected result**

"Далі" button should be active

**User story and test case links**
US - https://github.com/ita-social-projects/OoS-Backend/issues/312
TC - [OS-570](https://jira.softserve.academy/browse/OS-570)

**Labels to be added**
"Bug", Priority ("pri: high "), Severity ("severity: majot"), Type ("UI, "Functional")

**Comment by litvinets** [comment]
fixed!

**Comment by OksanaGuz** [comment]
Verified.
