### ISSUE TITLE
[Create workshop] Incorrect behavior of the ‘trash’ icon in the ‘Дні/Години’ field when creating a workshop

### ISSUE THREAD

**Issue by hanna-lenko** [ita-social-projects/OoS-Frontend#1149]
**Environment:** Win10 v21H2 64-bit, Chrome v 101.0.4951.54
**Reproducible:** sometimes
**Build found:** frontend: gcp-0.0.75, backend: gcp-0.0.130

**Preconditions**
1. Follow the link https://oos.dmytrominochkin.cloud/#/
2. Log into OoS website as SP (e.g. 'email'="didivan@gmail.com", 'Password'="Qwerty123!")
3. Select «Мої гуртки» in the menu bar at the top right corner
4. At least 1 workshop has already been registered or not
5. Click on the “Додати гурток” button and fill in all mandatory fields in ‘Про гурток’ section

**Steps to reproduce**
1. Set the value in the ‘Дні/Години’ field (@first_line), e.g. ‘Пн’, від ’12:00’ до ’13:00’ 
2. Сlick the ‘Додати ще одні Дні/Години’ link
3. Set the value in the second line of ‘Дні/Години’ field (@second_line), e.g. ‘Вт’, від ’13:00’ до ’14:00’ 
4. Repeat steps 2-3 (set e.g. ‘Ср’, від ’14:00’ до ’15:00 in @third_line)
5. Click the ‘trash’ icon near the @third_line

**Actual result**
1. The value is set in the ‘Дні/Години’ field (@first_line)
2. The new empty ‘Дні/Години’ field appears
3. The value is set in the second line of ‘Дні/Години’ field (@second_line)
4. The value is set in the third line of ‘Дні/Години’ field (@third_line)
![image](https://user-images.githubusercontent.com/97878413/167880792-d70d3d81-4943-4409-978d-3b1e3c4c012d.png)

5. The first line of ‘Дні/Години’ field is deleted instead of the third line
![image](https://user-images.githubusercontent.com/97878413/167880928-c4b41fc0-893f-408e-8e3d-e9bc5ff5259e.png)

Note on reproducibility: in case the ‘trash’ icon near the @first_line is clicked, the corresponding @first_line is deleted. So, the bug is reproducible for second, third, etc lines

**Expected result**
1. The value is set in the ‘Дні/Години’ field (@first_line) 
2. The new empty ‘Дні/Години’ field appears
3. The value is set in the second line of ‘Дні/Години’ field (@second_line)
4. The value is set in the third line of ‘Дні/Години’ field (@third_line)
5. The third line of ‘Дні/Години’ field is deleted after clicking the ‘trash’ icon near it

**User story and test case links**
User story [#55](https://github.com/ita-social-projects/OoS-Backend/issues/55)
Test case [OS-350](https://jira.softserve.academy/browse/OS-350)

**Labels to be added**
"Bug", "pri: low", "severity: trivial"

**Comment by litvinets** [comment]
fixed

**Comment by hanna-lenko** [comment]
Verified and closed
