### ISSUE TITLE
[Реєстрація нового закладу] Missing "Форми власності" dropdown option

### ISSUE THREAD

**Issue by OksanaGuz** [ita-social-projects/OoS-Frontend#1152]
**Environment:** macOS Big Sur 11.5.1; Chrome version 101.0.4951.54.
**Reproducible:** always.
**Build found:** gcp-0.0.73

**Preconditions**

1. Go to [https://oos.dmytrominochkin.cloud/#](https://oos.dmytrominochkin.cloud/)
2. Click on "Увійти/Зареєструватися" button in top right corner of header
3. Click on "Зареєструватися" hyperlink
4. Click on "Надавач послуг" button
5. Fill all mandatory fields with valid data and tick all checkboxes
6. Click on "Зареєструватися" button

**Steps to reproduce**
1. Click on "Форма власності" dropdown list

**Actual result**
There are  Громадська організація, Приватна, Державна options

<img width="612" alt="Снимок экрана 2022-05-11 в 20 10 50" src="https://user-images.githubusercontent.com/97882565/167907735-c0128490-219e-4788-b1ce-e9c5973dd8f9.png">

**Expected result**
There should be Державна, Коммунальна, Приватна options

<img width="415" alt="Снимок экрана 2022-05-11 в 20 11 04" src="https://user-images.githubusercontent.com/97882565/167907804-e4baa95a-6d16-40bd-8722-1bbe61bad009.png">

**User story and test case links**
US - https://github.com/ita-social-projects/OoS-Backend/issues/312
TC - [OS-570](https://jira.softserve.academy/browse/OS-570)

**Labels to be added**
"Bug", Priority ("pri: high"), Severity ("severity: major"), Type ("UI, "Functional").

**Comment by litvinets** [comment]
fixed

**Comment by OksanaGuz** [comment]
Verified.
