### ISSUE TITLE
[Registration Form SP] No error messages in the "Прізвище/Ім`я/По-батькові" fields

### ISSUE THREAD

**Issue by OksanaGuz** [ita-social-projects/OoS-Frontend#1154]
**Environment:** macOS Big Sur 11.5.1; Chrome version 101.0.4951.54.
**Reproducible:** always.
**Build found:** gcp-0.0.73

**Preconditions**

1. Go to [https://oos.dmytrominochkin.cloud/#](https://oos.dmytrominochkin.cloud/)
2. Click on "Увійти/Зареєструватися" button in header.
3. Clicks on "Зареєструватися" hyperlink.
4. Click on "Зареєструватися як надавач послуг" button.

**Steps to reproduce**
1. Fill "Прізвище" field with incorrect value (e.g. D@2 )
2. Fill "Ім`я" field with incorrect value (e.g. only spaces)
3. Fill "По-батькові" field with incorrect value (e.g. 23 !^ )

**Actual result**
There are no error messages

<img width="724" alt="Снимок экрана 2022-05-12 в 13 44 12" src="https://user-images.githubusercontent.com/97882565/168053504-d9ea9b00-dc9d-434e-b0bd-7fd98c52b4c7.png">

**Expected result**

There should be "Перевірте введені дані. Використовуйте, будь ласка, тільки кирилицю та символи ( ' - ) " highlighted red color error messages 

Validation - https://github.com/ita-social-projects/OoS-Backend/issues/572

**User story and test case links**

User story https://github.com/ita-social-projects/OoS-Backend/issues/312
Test case [OS-571](https://jira.softserve.academy/browse/OS-571)

**Labels to be added**
"Bug", Priority ("pri: major"), Severity ("severity: minor"), Type ("UI, "Functional").

**Comment by litvinets** [comment]
Please, verify changes according to this doc!
https://github.com/ita-social-projects/OoS-Frontend/wiki/Validation-Rules-For-All-the-Forms

PS: it was discussed with BA and new rules are applied for all the forms. Validation is simplified.

**Comment by litvinets** [comment]
we limited entering more than 30 symbols

**Comment by litvinets** [comment]
@DmyMi @RBiyovskiy  take a look please

**Comment by litvinets** [comment]
according to the approach, this field validation is happening only after clicking the submit button. For now, these fields cannot be checked dynamically.

**Comment by ViktoriiaHrytchyna** [comment]
This bug is not reproduced.
