### ISSUE TITLE
[Create Workshop "Контакти"] "Місто" field supports invalid value of characters  

### ISSUE THREAD

**Issue by OksanaGuz** [ita-social-projects/OoS-Frontend#1166]
**Environment:** macOS Big Sur 11.5.1; Chrome version 101.0.4951.54.
**Reproducible:** always.
**Build found:** gcp-0.0.73

**Preconditions**

1. Follow the link https://oos.dmytrominochkin.cloud/#/
2. Log into OoS website as SP (e.g. 'email'="didivan@gmail.com", 'Password'="Qwerty123!")
3. Select «Мої гуртки» in the menu bar at the top right corner.
4. Click on the “Додати гурток” button and fill in all mandatory fields in the 'Про гурток' and 'Опис' sections.
5. Click on the 'Далі' button.

**Steps to reproduce**

1. Fill “Місто“ field  with : 
   - more than 15 alphabetic characters
   - 1-15 numeric characters
   - 1-15 special characters
2.  Click on the next input field.

 **Actual result**

Field is filled. Text visible not through whole input field. Hover message "Такого міста немає" is shown.

https://user-images.githubusercontent.com/97882565/168279889-c7f67fcd-ded7-468a-a0a4-51632a83efda.mov

**Expected result**
The field should support max 15 alphabetic characters. 
"Перевірте правильність заповнення даних" red color error message should display

**User story and test case links**
User story - https://github.com/ita-social-projects/OoS-Backend/issues/55
Test case - [OS-368](https://jira.softserve.academy/browse/OS-368)

**Labels to be added**
"Bug", Priority ("pri: major "), Severity ("severity: minor"), Type ("UI, "Functional"), "API" (for back-end bugs).

**Comment by litvinets** [comment]
Please, verify changes according to this doc!
https://github.com/ita-social-projects/OoS-Frontend/wiki/Validation-Rules-For-All-the-Forms

PS: it was discussed with BA and new rules are applied for all the forms. Validation is simplified.

**Comment by litvinets** [comment]
fixed! Please, check comment in  https://github.com/ita-social-projects/OoS-Frontend/issues/1171

**Comment by OksanaGuz** [comment]
Verified.
