### ISSUE TITLE
[Create workshop] No validation in the ‘Назва’ field when SP creates a workshop

### ISSUE THREAD

**Issue by hanna-lenko** [ita-social-projects/OoS-Frontend#1170]
**Environment:** Win10 v21H2 64-bit, Chrome v 101.0.4951.54
**Reproducible:** always
**Build found:** frontend: gcp-0.0.75, backend: gcp-0.0.130

**Preconditions**
1. Follow the link https://oos.dmytrominochkin.cloud/#/
2. Log into OoS website as SP (e.g. 'email'="didivan@gmail.com", 'Password'="Qwerty123!")
3. Select «Мої гуртки» in the menu bar at the top right corner
4. At least 1 workshop has already been registered or not
5. Click on the “Додати гурток” button

**Steps to reproduce**
Set the invalid value into the ‘Назва’ field: length 61 characters, e.g. ‘Назва гуртка 61 символ_L3GtjSa5QHAqGN4nJL3GtjSa5QHAqGN4nL3Gtj’

**Actual result**
No error message appears, user can register a workshop with title length more than 60 characters.
The same bug appears when entering 100 or 257 or 3000 chars.

![image](https://user-images.githubusercontent.com/97878413/168556140-0ef6de09-a529-4663-b9a9-fa219cba5448.png)

**Expected result**
The field is highlighted with red, the error message ‘Це поле має містити від 1 до 60 символів’ appears

**User story and test case links**
User story [#55](https://github.com/ita-social-projects/OoS-Backend/issues/55) 
[Validation Rules For All the Forms]( https://github.com/ita-social-projects/OoS-Frontend/wiki/Validation-Rules-For-All-the-Forms)
Test case [OS-351](https://jira.softserve.academy/browse/OS-351)

**Labels to be added**
"Bug", "pri: medium", "severity: low"

**Comment by litvinets** [comment]
Please, verify changes according to this doc!
https://github.com/ita-social-projects/OoS-Frontend/wiki/Validation-Rules-For-All-the-Forms

PS: it was discussed with BA and new rules are applied for all the forms. Validation is simplified.

**Comment by hanna-lenko** [comment]
Verified and closed
