### ISSUE TITLE
[Create Workshop] 'Далі' button is active when mandatory field are empty. Reproducible on every creation step

### ISSUE THREAD

**Issue by OksanaGuz** [ita-social-projects/OoS-Frontend#1171]
Environment: macOS Big Sur 11.5.1; Chrome version 101.0.4951.54.
Reproducible: always.
Build found: gcp-0.0.73

**Preconditions**

1. Follow the link https://oos.dmytrominochkin.cloud/#/
2. Log into OoS website as SP (e.g. 'email'="[anna.didiaieva.95@ukr.net](mailto:anna.didiaieva.95@ukr.net)", 'Password'="Cdby?rf95")
3. Select «Мої гуртки» in the menu bar at the top right corner.

**Steps to reproduce**
1. Click on "Додати Гурток" button
2. Leave mandatory fields empty
3. Take a look to the 'Далі' button
4. Fill all mandatory fields
5. Click "Далі" button
6. Repeat steps 2-5 on every next creation section

**Actual result**

'Далі' button is active

**Expected result**

'Далі' button should be disabled if mandatory fields are empty

**User story and test case links**
User story - https://github.com/ita-social-projects/OoS-Backend/issues/55
Test case - 
[OS-370](https://jira.softserve.academy/browse/OS-370)
[OS-371](https://jira.softserve.academy/browse/OS-371)
[OS-372](https://jira.softserve.academy/browse/OS-372)

**Labels to be added**
"Bug", Priority ("pri: medium "), Severity ("severity: minor").

**Comment by litvinets** [comment]
fixed!

**Comment by OksanaGuz** [comment]
@litvinets Reproducible on "Контакти" section
<img width="453" alt="Снимок экрана 2022-05-23 в 13 17 53" src="https://user-images.githubusercontent.com/97882565/169808214-6e5376cd-9e79-484f-8b17-df54dca98d55.png">
.

**Comment by litvinets** [comment]
1. make the width of the input city full-width of the form
2. progress bar doesn't disappear
3. no validation message for city and street 
4. when the form is initially empty, the button is enabled but you can not move further
5. when you enter all the data (invalid city) - the button is enabled but you can not move further
6. when you enter a valid city, the - button is enabled but you can not move further
7. when you select valid city, the - button is enabled but you can not move further
8. when you select the city from the dropdown and then type a new one (but don't select it), the previous city has remained
9. no validation message for department and class,  when you reset the previous level (direction/department)

**Comment by litvinets** [comment]
no validation message for city 
when the form is initially empty, the button is enabled but you can not move further
when you enter all the data (invalid city) - the button is enabled but you can not move further
when you enter a valid city, the - button is enabled but you can not move further
when you select valid city, the - button is enabled but you can not move further
when you select the city from the dropdown and then type a new one (but don't select it), the previous city has remained

**Comment by litvinets** [comment]
Fixed!
Regarding city validation, please contact me if there are any questions regarding the functionality.

In general, the city MUST BE SELECTED from the dropdown. If you just type the city it will be replaced with the initial city (previous selected) until the correct new city from the dropdown will be selected. It is very important to have the correct and real city, otherwise, the workshop won't be displayed on the website (because we always have city filtration). If the city is unreal, then the workshop will be never displayed. That's why such functionality was provided. Also, please pay attention to the map behavior. Now the mapp is trying to find the city from the form.

If there is any question, please contact me!

**Comment by OksanaGuz** [comment]
Verified!
