### ISSUE TITLE
[Create Workshop] "Клас" field isn't hidden if it has no data

### ISSUE THREAD

**Issue by OksanaGuz** [ita-social-projects/OoS-Frontend#1174]
Environment: macOS Big Sur 11.5.1; Chrome version 101.0.4951.54.
Reproducible: always.
Build found: gcp-0.0.73

**Preconditions**

1. Follow the link https://oos.dmytrominochkin.cloud/#/
2. Log into OoS website as SP (e.g. 'email'="didivan@gmail.com", 'Password'="Qwerty123!")
3. Select «Мої гуртки» in the menu bar at the top right corner.
4. At least 1 workshop has already been registered or not.
5. Click on the “Додати гурток” button and fill in all mandatory fields in the ‘Про гурток’ section.
6. Click on the “Далі” button.

**Steps to reproduce**

1. Set the valid value into the “Напрямок за яким здійснюється навчання“ field (e.g. Спорт)
2. Set the valid value into the "Відділ/профіль" field (e.g. Фізкультурно-спортивний або спортивний)
3. Click on the "Клас" field

**Actual result**

The "Клас" field is appears with empty drop-down list

<img width="615" alt="Снимок экрана 2022-05-16 в 14 16 31" src="https://user-images.githubusercontent.com/97882565/168581295-9abd397f-755e-4a96-9bb0-6d4546423946.png">

**Expected result*.

The "Класс" field should be hidden  if it has no data.

**User story and test case links**

User story - https://github.com/ita-social-projects/OoS-Backend/issues/55
Test case- [OS-521](https://jira.softserve.academy/browse/OS-521)

**Labels to be added**
"Bug", Priority ("pri: medium"), Severity ("severity: minor")

**Comment by litvinets** [comment]
deprecated, because class and departments were removed
