### ISSUE TITLE
[Update Direction] - Finish functionality

### ISSUE THREAD

**Issue by litvinets** [ita-social-projects/OoS-Frontend#1176]
Second step - update department

1) steps to reproduce:
-go to update deportment
-click on edit section
-select department (you will see the department title in the header)
-click to add new section

expected: no already selected department 

2) after new department's creation, the next step should look like initial create form (no options for delete/update classes)
3) after class delete dispatch new list of classes
4) disable next button if there are no classes for selected department
5) fix modal for edit department
5) hide classes, departments dropdown if there are no items

**Comment by LeraKornienko** [comment]
Left:
1. Second step - update department

steps to reproduce:
-go to update deportment
-click on edit section
-select department (you will see the department title in the header)
-click to add new section
expected: no already selected department

2. after new department's creation, the next step should look like initial create form (no options for delete/update classes)
3. disable next button if there are no classes for selected department
