### ISSUE TITLE
[Personal cabinet Parent] The title is "Кабінет Надавача" instead of "Кабінет Користувача"

### ISSUE THREAD

**Issue by OksanaGuz** [ita-social-projects/OoS-Frontend#1235]
**Environment:**  macOS Big Sur 11.5.1; Chrome version 101.0.4951.54.
**Reproducible:** always.
**Build found:** gcp-0.0.89

**Preconditions**
Login as Parent

**Steps to reproduce**
1. Go to 'Особистий кабінет'
2. Take a look to the title.

**Actual result**
There is 'Кабінет надавача'

<img width="1124" alt="Снимок экрана 2022-05-30 в 14 16 59" src="https://user-images.githubusercontent.com/97882565/170981430-1f244c44-6334-4487-8be0-719f9c27beb5.png">

**Expected result**
There should be 'Кабінет користувача'

<img width="695" alt="Снимок экрана 2022-05-30 в 14 17 49" src="https://user-images.githubusercontent.com/97882565/170981544-ad1b8448-2239-4ff5-ba7a-8ad434f93296.png">

**Labels to be added**
"Bug", Priority ("pri: high"), Severity ("severity: trivial"), Type ("UI, "Functional").

**Comment by litvinets** [comment]
fixed!

**Comment by OksanaGuz** [comment]
Verified.
