### ISSUE TITLE
[Phone number] Inappropriate error message in the Phone field

### ISSUE THREAD

**Issue by OksanaGuz** [ita-social-projects/OoS-Frontend#1254]
**Environment:** macOS Big Sur 11.5.1; Chrome version 101.0.4951.54.
**Reproducible:** always
**Build found:**  gcp-0.0.94

**Preconditions**

1. Login as any user
2. Go to 'Особистий кабінет'

**Steps to reproduce**

1. Click on "Редагувати" button
2. Change value in the Phone field from 1 to 8 digits
3. Click outside Phone field

**Actual result**

'Це поле має містити від до символів.' Error message appears
<img width="328" alt="Снимок экрана 2022-06-02 в 15 06 45" src="https://user-images.githubusercontent.com/97882565/171628454-41dab543-d3ae-4b73-81b9-ab576508695d.png">

**Expected result**
The phone field must contain 9 digits only.

**User story and test case links**
User story (https://github.com/ita-social-projects/OoS-Frontend/wiki/Validation-Rules-For-All-the-Forms)

**Comment by litvinets** [comment]
Please, add displaying a message for phone inputs if the length of the field is invalid.
Pass only maxLength and add check-in validation-hint-input for minLength.
The result message should be "Це поле має містити {{maxLength}} символів".

**Comment by Pabloostr** [comment]
fixed
