### ISSUE TITLE
[Search Page] Filter doesn't open by default

### ISSUE THREAD

**Issue by OksanaGuz** [ita-social-projects/OoS-Frontend#1311]
Environment: macOS Big Sur 11.5.1; Chrome version 99.0.4844.51.
Reproducible: always.
Build found: [gcp-0.0.94](https://github.com/ita-social-projects/OoS-Frontend/releases/tag/gcp-0.0.94)

**Preconditions**
Be on the main page as any type of user

**Steps to reproduce**
1. Go to 'Найпопулярніші гуртки' page or click on the Search button 
2. Observe the hidden filter

**Actual result**
The filter is hidden

**Expected result**
The filter should open by default

**Labels to be added**
"Bug", Priority ("pri: low"), Severity ("severity: trivial")

**Comment by litvinets** [comment]
fixed

**Comment by OksanaGuz** [comment]
Verified.
