### ISSUE TITLE
Cards Alignment - cards should be centered

### ISSUE THREAD

**Issue by perepichai** [ita-social-projects/OoS-Frontend#1318]
The cards should be centered on the following components:
app-main
app-all-categories
app-result
app-workshops
app-all-provider-workshops
app-workshop-teachers
app-children

You can use flexlayout center (check documentation for that if needed, https://tburleson-layouts-demos.firebaseapp.com/#/docs)

Example:
![image-1](https://user-images.githubusercontent.com/8740198/173776217-2033afda-ec77-4477-98f6-2c2693361cae.png)
![image](https://user-images.githubusercontent.com/8740198/173776225-e853f9c0-46f1-4bb8-81ed-4302e1f03079.png)

**Comment by Illya97** [comment]
Fixed
