### ISSUE TITLE
[Applications] - service and component upgrade

### ISSUE THREAD

**Issue by litvinets** [ita-social-projects/OoS-Frontend#1322]
1) add paginator for applications (the standard one with dropdown and etc.)
2) add parameter showBlocked true/false (check it on swagger)
3) add new tab "Blocked", add to the status info card the new "status" Blocked (it is not actually status, but displayed as it is application status)
![image](https://user-images.githubusercontent.com/27493959/173809659-53b4ae5a-efed-4ea4-9810-f03238340d61.png)

4) when you click on tab "block" pass parameter showBlcoked as true
5) check in the network that only for tab "blocked" you truly have showBlcoked for getting applications

**Comment by LeraKornienko** [comment]
Tab "Blocked", add to the status info card in brunch #1193Block

<img width="1415" alt="Снимок экрана 2022-06-15 в 22 44 28" src="https://user-images.githubusercontent.com/96778768/173913346-2f182c58-65aa-4e1e-a9a3-988b97ea2282.png">

**Comment by litvinets** [comment]
@LeraKornienko add this piece of functionality into this PR and apply everything that I mentioned above
