### ISSUE TITLE
[New institution creation] Статус default value is "Відсутній" instead of "Працює"

### ISSUE THREAD

**Issue by OksanaGuz** [ita-social-projects/OoS-Frontend#1331]
Environment: macOS Big Sur 11.5.1; Chrome version 99.0.4844.51.
Reproducible: always.
Build found: gcp-0.0.94

**Preconditions**

1. Go to [https://oos.dmytrominochkin.cloud/#](https://oos.dmytrominochkin.cloud/)
2. Click on "Увійти/Зареєструватися" button in top right corner of header
3. Click on "Зареєструватися" hyperlink
4. Click on "Надавач послуг" button
5. Fill all mandatory fields with valid data and tick all checkboxes
6. Click on "Зареєструватися" button
7. Fill all mandatory fields with valid data
8. Click on "Далі" button
9. Fill all mandatory fields with valid data and tick checkbox
10. Click on "Далі" button

**Steps to reproduce**
1. Take a look to the "Статус" drop-box

**Actual result**
"Відсутній" displays by default

**Expected result**
"Працює" should display by default

**User story and test case links**
User story https://github.com/ita-social-projects/OoS-Frontend/wiki/Validation-Rules-For-All-the-Forms
Test case [OS-573](https://jira.softserve.academy/browse/OS-573)

**Labels to be added**
"Bug", Priority ("pri: low"), Severity ("severity:minor"), Type ("UI, "Functional"),

**Comment by Illya97** [comment]
Fixed

**Comment by OksanaGuz** [comment]
Verified.
