### ISSUE TITLE
[New institution creation] Phone field displays 2 error messages at once

### ISSUE THREAD

**Issue by OksanaGuz** [ita-social-projects/OoS-Frontend#1334]
Environment: macOS Big Sur 11.5.1; Chrome version 99.0.4844.51.
Reproducible: always.
Build found: gcp-0.0.94

**Preconditions**

1. Go to [https://oos.dmytrominochkin.cloud/#](https://oos.dmytrominochkin.cloud/)
2. Click on "Увійти/Зареєструватися" button in top right corner of header
3. Click on "Зареєструватися" hyperlink
4. Click on "Надавач послуг" button
5. Fill all mandatory fields with valid data and tick all checkboxes
6. Click on "Зареєструватися" button

**Steps to reproduce**
1. Fill "Дата народження керівника" field with incorrect format. (e.g. 986756)

**Actual result**

Phone field displays 2 error messages at once
<img width="354" alt="Снимок экрана 2022-06-20 в 16 44 26" src="https://user-images.githubusercontent.com/97882565/174615195-388a722b-cfdc-4458-87b2-279021da129f.png">

**Expected result**
"Перевірте введені данні. Використовуйте "ДД/ММ/РРРР" формат. Наприклад "20/10/2010" error message should appears

**User story and test case links**
User story (https://github.com/ita-social-projects/OoS-Frontend/wiki/Validation-Rules-For-All-the-Forms)
Test case [OS-604](https://jira.softserve.academy/browse/OS-604)

**Labels to be added**
"Bug", Priority ("pri: medium "), Severity ("severity:minor")

**Comment by OksanaGuz** [comment]
There is "Це поле є обов'язковим" insead of "Перевірте введені данні. Використовуйте "ДД/ММ/РРРР" формат. Наприклад "20/10/2010"
<img width="238" alt="Снимок экрана 2022-06-28 в 16 15 46" src="https://user-images.githubusercontent.com/97882565/176187954-d718103c-497a-4aa1-8f6d-3c55aef0ce1c.png">

**Comment by litvinets** [comment]
done!

**Comment by OksanaGuz** [comment]
Verified.
