### ISSUE TITLE
[New institution creation] Inappropriate error message in the "ЄДРПОУ/ІПН" field

### ISSUE THREAD

**Issue by OksanaGuz** [ita-social-projects/OoS-Frontend#1335]
Environment: macOS Big Sur 11.5.1; Chrome version 99.0.4844.51.
Reproducible: always.
Build found: gcp-0.0.94

**Preconditions**
Go to [https://oos.dmytrominochkin.cloud/#](https://oos.dmytrominochkin.cloud/)
Click on "Увійти/Зареєструватися" button in top right corner of header
Click on "Зареєструватися" hyperlink
Click on "Надавач послуг" button
Fill all mandatory fields with valid data and tick all checkboxes
Click on "Зареєструватися" button

**Steps to reproduce**
1. Fill "ЄДРПОУ/ІПН" field less than 8 chars

**Actual result**
'Це поле має містити від до символів.' Error message appears
<img width="233" alt="Снимок экрана 2022-06-20 в 19 41 42" src="https://user-images.githubusercontent.com/97882565/174646900-2d89e2cc-8d6e-47cf-b533-ac7bf963c0de.png">

**Expected result**
"Це поле має містити від 8 до 10 символів" error message should appears

**User story and test case links**
User story (https://github.com/ita-social-projects/OoS-Frontend/wiki/Validation-Rules-For-All-the-Forms)
Test case [OS-604](https://jira.softserve.academy/browse/OS-604)

**Labels to be added**
"Bug", Priority ("pri: medium "), Severity ("severity:minor")

**Comment by litvinets** [comment]
@Illya97  you can get the details how to fix it from @Pabloostr

**Comment by litvinets** [comment]
done!

**Comment by OksanaGuz** [comment]
Verified.
