### ISSUE TITLE
[New institution creation 'Контакти'] "Це поле є обов'язковим" error messages do not appear

### ISSUE THREAD

**Issue by OksanaGuz** [ita-social-projects/OoS-Frontend#1337]
Environment: macOS Big Sur 11.5.1; Chrome version 99.0.4844.51.
Reproducible: always.
Build found: gcp-0.0.94

**Preconditions**

1. Go to [https://oos.dmytrominochkin.cloud/#](https://oos.dmytrominochkin.cloud/)
2. Click on "Увійти/Зареєструватися" button in top right corner of header
3. Click on "Зареєструватися" hyperlink
4. Click on "Надавач послуг" button
5. Fill all mandatory fields with valid data and tick all checkboxes
6. Click on "Зареєструватися" button
7. Fill all mandatory fields with valid data
8. Click on "Далі" button

**Steps to reproduce**
1. Click on "Місто" field on "Юридична адреса" section and leave empty
2. Click on "Місто" field in "Фактична адреса" section and leave empty

**Actual result**
The fields are highlighted but error messages do not displays

<img width="651" alt="Снимок экрана 2022-06-20 в 20 20 05" src="https://user-images.githubusercontent.com/97882565/174651951-a9768237-ee73-4a53-a2ff-404d6aaba697.png">

**Expected result**

"Це поле є обов'язковим" error message should displays if mandatory field is empty

**User story and test case links**
User story (https://github.com/ita-social-projects/OoS-Frontend/wiki/Validation-Rules-For-All-the-Forms)
Test case [OS-605](https://jira.softserve.academy/browse/OS-605)

**Labels to be added**
"Bug", Priority ("pri: medium "), Severity ("severity:minor"), Type UI

**Comment by litvinets** [comment]
fixed

**Comment by OksanaGuz** [comment]
No error message in the "Фактична адреса" section 
![Uploading Снимок экрана 2022-06-28 в 16.17.48.png…]()

**Comment by litvinets** [comment]
fixed 
![image](https://user-images.githubusercontent.com/27493959/176201617-3c183929-1b10-4ded-941b-2badd0b49331.png)

**Comment by OksanaGuz** [comment]
Verified.
