### ISSUE TITLE
[New institution creation"Контакти"] Fields allow 1 latin and special characters and user is able to move further

### ISSUE THREAD

**Issue by OksanaGuz** [ita-social-projects/OoS-Frontend#1339]
Environment: macOS Big Sur 11.5.1; Chrome version 99.0.4844.51.
Reproducible: always.
Build found: gcp-0.0.94

**Preconditions**

1. Go to [https://oos.dmytrominochkin.cloud/#](https://oos.dmytrominochkin.cloud/)
2. Click on "Увійти/Зареєструватися" button in top right corner of header
3. Click on "Зареєструватися" hyperlink
4. Click on "Надавач послуг" button
5. Fill all mandatory fields with valid data and tick all checkboxes
6. Click on "Зареєструватися" button
7. Fill all mandatory fields with valid data
8. Click on "Далі" button

**Steps to reproduce**
1. Fill "Місто" with correct data
2. Fill "Область", "Район",  "Вулиця", "Будинок" in the both Юридична адреса and Фактична адреса sections with 1 latin character and then digits or special characters
3. Take a look to "Далі" button

**Actual result**
No error messages, user is able to move further

<img width="301" alt="Снимок экрана 2022-06-20 в 21 14 13" src="https://user-images.githubusercontent.com/97882565/174658489-2f09ea17-d77e-45bd-80a1-f518581d720b.png">

**Expected result**
"Перевірте введені дані. Використовуйте, будь ласка, тільки кирилицю." error message should be displayed 
Fields should support only cyrillic characters.
"Будинок" field should support digits too

**User story and test case links**
User story (https://github.com/ita-social-projects/OoS-Frontend/wiki/Validation-Rules-For-All-the-Forms)
Test case [OS-605](https://jira.softserve.academy/browse/OS-605)

**Labels to be added**
"Bug", Priority ("pri: high "), Severity ("severity: major")

**Comment by OksanaGuz** [comment]
Fields still  support special characters. "Область", "Вулиця", "Район" cannot contain digits or special characters (except spaces and chars '- ) , "Будинок" should support digits and special symbols -`/ 

<img width="579" alt="Снимок экрана 2022-06-30 в 13 50 38" src="https://user-images.githubusercontent.com/97882565/176659677-3f0dcc44-87a5-44fa-8844-8962ce42750b.png">

**Comment by litvinets** [comment]
@OksanaGuz  done

**Comment by litvinets** [comment]
it is not relevant anymore due to the global form changes
