### ISSUE TITLE
[New institution creation "Опис"] Mandatory fields are not marked with a red asterisk

### ISSUE THREAD

**Issue by OksanaGuz** [ita-social-projects/OoS-Frontend#1340]
Environment: macOS Big Sur 11.5.1; Chrome version 99.0.4844.51.
Reproducible: always.
Build found: gcp-0.0.94

**Preconditions**

1. Go to [https://oos.dmytrominochkin.cloud/#](https://oos.dmytrominochkin.cloud/)
2. Click on "Увійти/Зареєструватися" button in top right corner of header
3. Click on "Зареєструватися" hyperlink
4. Click on "Надавач послуг" button
5. Fill all mandatory fields with valid data and tick all checkboxes
6. Click on "Зареєструватися" button
7. Fill all mandatory fields with valid data
8. Click on "Далі" button

**Steps to reproduce**
1. Take a look to "Статус", "Тип закладу", "Підпорядкування" fields

**Actual result**
Required fields are not marked with a red asterisk

<img width="343" alt="Снимок экрана 2022-06-20 в 21 52 43" src="https://user-images.githubusercontent.com/97882565/174663064-15404d4f-23ce-49bd-a24b-cad5a2784a44.png">

**Expected result**
Required fields should be marked with a red asterisk

**User story and test case links**
User story (https://github.com/ita-social-projects/OoS-Frontend/wiki/Validation-Rules-For-All-the-Forms)
Test case [OS-605](https://jira.softserve.academy/browse/OS-605)

**Labels to be added**
"Bug", Priority ("pri: low "), Severity ("severity: trivial")

**Comment by litvinets** [comment]
fixed!

**Comment by OksanaGuz** [comment]
Verified.
