### ISSUE TITLE
[New institution creation "Опис"] There are no error messages in the dropdown boxes

### ISSUE THREAD

**Issue by OksanaGuz** [ita-social-projects/OoS-Frontend#1348]
Environment: macOS Big Sur 11.5.1; Chrome version 99.0.4844.51.
Reproducible: always.
Build found: gcp-0.0.94

**Preconditions**

1. Go to [https://oos.dmytrominochkin.cloud/#](https://oos.dmytrominochkin.cloud/)
2. Click on "Увійти/Зареєструватися" button in top right corner of header
3. Click on "Зареєструватися" hyperlink
4. Click on "Надавач послуг" button
5. Fill all mandatory fields with valid data and tick all checkboxes
6. Click on "Зареєструватися" button
7. Fill all mandatory fields with valid data
8. Click on "Далі" button

**Steps to reproduce**
1.  Click on "Тип закладу" field and leave empty
2. Click on "Підпорядкування" field and leave empty

**Actual result**
The fields are highlighted but error messages do not displays

<img width="514" alt="Снимок экрана 2022-06-21 в 15 17 50" src="https://user-images.githubusercontent.com/97882565/174797138-4f9e9166-5bb6-4f99-9841-376b27f88279.png">

**Expected result**
"Це поле є обов'язковим" error message should displays if mandatory field is empty

**User story and test case links**

User story (https://github.com/ita-social-projects/OoS-Frontend/wiki/Validation-Rules-For-All-the-Forms)
Test case [OS-606](https://jira.softserve.academy/browse/OS-606)

**Labels to be added**
"Bug", Priority ("pri: medium "), Severity ("severity:minor"), Type UI

**Comment by Pabloostr** [comment]
fixed

**Comment by OksanaGuz** [comment]
Verified.
