### ISSUE TITLE
[Search page] Search results updates while typing price range

### ISSUE THREAD

**Issue by OksanaGuz** [ita-social-projects/OoS-Frontend#1349]
Environment: macOS Big Sur 11.5.1; Chrome version 99.0.4844.51.
Reproducible: always.
Build found: gcp-0.0.94

**Preconditions**
1. Be on the Search page as any type of user

**Steps to reproduce**
1. Click on price "Платні" checkbox
2. Start typing price in the "Від" or "До" input fields

**Actual result**
Search results are updates immediately

**Expected result**
Results should be updated after the user has finished typing.

**Comment by litvinets** [comment]
fixed
