### ISSUE TITLE
[Child creation] Inappropriate error message appears in the "Серія та номер свідоцтва про народження" field

### ISSUE THREAD

**Issue by OksanaGuz** [ita-social-projects/OoS-Frontend#1361]
Environment: macOS Big Sur 11.5.1; Chrome version 99.0.4844.51.
Reproducible: always.
Build found: gcp-0.0.94

**Preconditions**

1. Log in as parent
2. Go to "Інформація про дитину" page
3. Click on "Додати дитину" button

**Steps to reproduce**
1. Fill "Серія та номер свідоцтва про народження" field with less than 10 or more than 30 characters

**Actual result**
"Це поле має містити від 1 до 30 символів" error massage appears

<img width="541" alt="Снимок экрана 2022-06-22 в 13 55 38" src="https://user-images.githubusercontent.com/97882565/175012523-1b0e6bbd-2e47-4811-bf96-e0fc60dfefc8.png">

**Expected result**

"Це поле має містити від 10 до 20 символів" error message should appear

<img width="444" alt="Снимок экрана 2022-06-22 в 13 57 11" src="https://user-images.githubusercontent.com/97882565/175012807-c054b407-3700-432d-9314-986037c9f7ae.png">

**User story and test case links**

User story (https://github.com/ita-social-projects/OoS-Frontend/wiki/Validation-Rules-For-All-the-Forms)
Test case [OS-186](https://jira.softserve.academy/browse/OS-186)

**Labels to be added**
Bug, Priority ("pri: medium "), Severity ("severity:minor")

**Comment by litvinets** [comment]
updated https://github.com/ita-social-projects/OoS-Frontend/wiki/Validation-Rules-For-All-the-Forms
