### ISSUE TITLE
[Workshop creation] Price does't fit in the field

### ISSUE THREAD

**Issue by OksanaGuz** [ita-social-projects/OoS-Frontend#1381]
Environment: macOS Big Sur 11.5.1; Chrome version 99.0.4844.51.
Reproducible: always.
Build found: gcp-0.0.94

**Preconditions**
1. Follow the link https://oos.dmytrominochkin.cloud/#/
2. Log into OoS website as SP 
3. Select «Мої гуртки» in the menu bar at the top right corner.
4. Click on the “Додати гурток” button.

**Steps to reproduce**
1. Fill price field with more than 4 digits (e.g. 10000)

**Actual result**
The field is cropped price

<img width="206" alt="Снимок экрана 2022-06-27 в 13 55 31" src="https://user-images.githubusercontent.com/97882565/175925858-e89088f2-d425-4851-8f90-05997b236ee9.png">

**Expected result**
Set price should fit in the input field

**User story and test case links**
User story - https://github.com/ita-social-projects/OoS-Backend/issues/55
Test case - [OS-363](https://jira.softserve.academy/browse/OS-363)

**Labels to be added**
"Bug", Priority ("pri: medium"), Severity ("severity:minor"), Type UI.

**Comment by Illya97** [comment]
Fixed

**Comment by OksanaGuz** [comment]
Verified.
