### ISSUE TITLE
[Workshop Creation "Вчителі"] Inappropriate error message appears in the "Дата народження" field

### ISSUE THREAD

**Issue by OksanaGuz** [ita-social-projects/OoS-Frontend#1395]
Environment: macOS Big Sur 11.5.1; Chrome version 99.0.4844.51.
Reproducible: always.
Build found: gcp-0.0.94

**Preconditions**

1. Log into OoS website as SP 
2. Select «Мої гуртки».
3. Click on the “Додати гурток” button and fill in all mandatory fields in the 'Про гурток', 'Опис' and 'Контакти' sections.
4. Click on the 'Далі' button.

**Steps to reproduce**
1. Fill "Дата народження" field with following data:
 - more that 120 years ago (e.g. 12/12/1901)
 - Alphabetic characters
 - Special symbols
 - Dates with ‘00’ (e.g. 00.00.0000)
 - Unlogic values (42.15.2021)

**Actual result**
"Це поле є обов'язковим" error message is appeared
<img width="213" alt="Снимок экрана 2022-06-29 в 12 55 05" src="https://user-images.githubusercontent.com/97882565/176412330-dac5cee2-d64a-40af-a839-b0f50944b565.png">
<img width="245" alt="Снимок экрана 2022-06-29 в 13 08 05" src="https://user-images.githubusercontent.com/97882565/176412403-7f6592c9-0b5e-4c67-aa40-0e38e57d0572.png">
<img width="243" alt="Снимок экрана 2022-06-29 в 12 55 50" src="https://user-images.githubusercontent.com/97882565/176412484-3a6b7b64-98ec-44f7-accc-fbf97d69f3f6.png">
<img width="222" alt="Снимок экрана 2022-06-29 в 13 06 49" src="https://user-images.githubusercontent.com/97882565/176412567-ac5026e6-4fd0-4f47-b6a7-bc96ef058f98.png">

**Expected result**
"Перевірте введені данні. Використовуйте "ДД/ММ/РРРР" формат. Наприклад "20/10/2010"" red colour error message should be displayed

**User story and test case links**
User story - https://github.com/ita-social-projects/OoS-Frontend/wiki/Validation-Rules-For-All-the-Forms
Test case - [OS-369](https://jira.softserve.academy/browse/OS-369)

**Labels to be added**
"Bug", Priority ("pri: medium"), Severity ("severity:minor")

**Comment by litvinets** [comment]
fixed 
![image](https://user-images.githubusercontent.com/27493959/176464895-84749b5b-5666-47c2-a264-4cf9eb8cbe05.png)

**Comment by OksanaGuz** [comment]
@litvinets User can't be older than 120 years
<img width="179" alt="Снимок экрана 2022-06-30 в 12 50 02" src="https://user-images.githubusercontent.com/97882565/176655843-f36aedb1-3b96-4c35-b3e1-e94d23861889.png">
<img width="129" alt="Снимок экрана 2022-06-30 в 13 30 52" src="https://user-images.githubusercontent.com/97882565/176656178-f66bb127-0050-4231-a471-b90de1397248.png">

**Comment by litvinets** [comment]
fixed

**Comment by OksanaGuz** [comment]
Verifed.
