### ISSUE TITLE
[Personal data edition] Data can not be changed if there more than 30 chars

### ISSUE THREAD

**Issue by OksanaGuz** [ita-social-projects/OoS-Frontend#1396]
Environment: macOS Big Sur 11.5.1; Chrome version 99.0.4844.51.
Reproducible: always.
Build found: gcp-0.0.94

**Preconditions**

1. Log in as any type of user
2. Go to the 'ОСОБИСТА ІНФОРМАЦІЯ' tab 
3. Select the 'Edit' page of 'ОСОБИСТА ІНФОРМАЦІЯ' tab

**Steps to reproduce**
1. Fill  'Прізвище'/ 'Ім'я'/'По-батькові' fields with more than 30 Cyrillic and symbols ( ` -)
2. Click on "Зберегти" button

**Actual result**
Data is displayed on the field, "На жаль виникла помилка" error notification appears
<img width="1345" alt="Снимок экрана 2022-06-29 в 13 47 21" src="https://user-images.githubusercontent.com/97882565/176419090-f3cc749c-ac9d-4108-b3a1-825076ece524.png">

**Expected result**
Fields should support up to 60 charachters
<img width="668" alt="Снимок экрана 2022-06-29 в 13 44 28" src="https://user-images.githubusercontent.com/97882565/176418318-9d15d9ec-062d-4644-9337-e7a99bd9324e.png">

**User story and test case links**
User story - https://github.com/ita-social-projects/OoS-Frontend/wiki/Validation-Rules-For-All-the-Forms
Test case - [OS-436](https://jira.softserve.academy/browse/OS-436)
[OS-588](https://jira.softserve.academy/browse/OS-588)

**Labels to be added**
"Bug", Priority ("pri: medium"), Severity ("severity: major")

**Comment by ViktoriiaHrytchyna** [comment]
This bug is not reproduced.
