### ISSUE TITLE
[Breadcrumbs] "Кабінет тех.адміна" displays when Parent edits personal info

### ISSUE THREAD

**Issue by OksanaGuz** [ita-social-projects/OoS-Frontend#1397]
Environment: macOS Big Sur 11.5.1; Chrome version 99.0.4844.51.
Reproducible: always.
Build found: gcp-0.0.94

**Preconditions**

1. Log in as Parent
2. Go to the 'ОСОБИСТА ІНФОРМАЦІЯ' tab
3. Select the 'Edit' page of 'ОСОБИСТА ІНФОРМАЦІЯ' tab

**Steps to reproduce**
1. Take a look to names of breadcrumbs

**Actual result**
"Кабінет тех.адміна"
<img width="410" alt="Снимок экрана 2022-06-29 в 13 54 22" src="https://user-images.githubusercontent.com/97882565/176420099-85d32dc4-d28a-4be7-80d6-c0ee2ae4157d.png">

**Expected result**
There should be "Кабінет користувача"

**Labels to be added**
"Bug", Priority ("pri: high"), Severity ("severity: minor")

**Comment by litvinets** [comment]
fixed

**Comment by litvinets** [comment]
@OksanaGuz  Breadcrumbs, in general, was improved, we can discuss the details of which steps should be included in the breadcrumbs. But the general approach was fixed. If it is possible, can you just test this functionality (using different roles)

**Comment by OksanaGuz** [comment]
If Admin edits workshop then breadcrumbs shows 'Кабінет надавача'

https://user-images.githubusercontent.com/97882565/178265087-0fdc5066-036a-40bd-bb00-81afb869c387.mov

**Comment by litvinets** [comment]
@OksanaGuz  done!

**Comment by OksanaGuz** [comment]
Verified.
