### ISSUE TITLE
[Institution info edition "Контакти"] Fields do not support Ukrainian letters (і,ї,є)

### ISSUE THREAD

**Issue by OksanaGuz** [ita-social-projects/OoS-Frontend#1398]
Environment: macOS Big Sur 11.5.1; Chrome version 99.0.4844.51.
Reproducible: always.
Build found: gcp-0.0.94

**Preconditions**

1. Log in as SP 
2. Go to the 'ІНФОРМАЦІЯ ПРО ЗАКЛАД' tab of SP cabinet (by clicking the button in the top right corner)
4. Forward to "Контакти" section
5. Click on 'Edit' button 

**Steps to reproduce**
1. Fill fields with Ukrainian letters (і,ї,є)

**Actual result**
1. "Перевірте введені дані, використовуйте будь-ласка тільки кирилицю" error messages is appeared
<img width="599" alt="Снимок экрана 2022-06-29 в 16 53 16" src="https://user-images.githubusercontent.com/97882565/176453828-70089014-a88b-44d1-a966-10e098520570.png">

**Expected result**
1. Fields should support Ukrainian alphabet

**User story and test case links**
User story (https://github.com/ita-social-projects/OoS-Frontend/wiki/Validation-Rules-For-All-the-Forms)
Test case [OS-291](https://jira.softserve.academy/browse/OS-291)

**Labels to be added**
"Bug", Priority ("pri: medium "), Severity ("severity:minor")

**Comment by litvinets** [comment]
fixed!:)
