### ISSUE TITLE
[Pagination dropdown] Dropdown is missing on the "Мої гуртки" page in the SP cabinet

### ISSUE THREAD

**Issue by OksanaGuz** [ita-social-projects/OoS-Frontend#1405]
**Environment**: macOS Big Sur 11.5.1; Chrome version 99.0.4844.51.
**Reproducible:** always.
**Build found:** gcp-0.0.94

**Preconditions**

1. Log in as SP (e.g. Email - kamin@gmail.com Password - Qwerty1!) There are more than 12 workshops in the cabinet

**Steps to reproduce**

1. Go to "Мої гуртки" 
2. Scroll down to the bottom

**Actual result**
There is no pagination dropdown

**Expected result**
Pagination dropdown should present on the "Мої гуртки" page

**User story and test case links**
User story - https://github.com/ita-social-projects/OoS-Frontend/issues/1115
Test case

**Labels to be added**
"Bug", Priority ("pri: medium"), Severity ("severity:minor")

**Comment by litvinets** [comment]
@DmyMi we need pagination for provider workshops
