### ISSUE TITLE
[Search page "Sorting" UI] Missing alignment "Sorting" drop down

### ISSUE THREAD

**Issue by OksanaGuz** [ita-social-projects/OoS-Frontend#1411]
Environment: macOS Big Sur 11.5.1; Chrome version 99.0.4844.51.
Reproducible: always.
Build found: gcp-0.0.94

**Preconditions**

1. Be on the main page as any type of user

**Steps to reproduce**
1. Click on "Найпопулярніші гуртки" page
2. Take a look to Sorting dropdown
3. Change page scale and observe location of dropdown

**Actual result**
The name is not centered, dropdown is too close to the search field.
<img width="207" alt="Снимок экрана 2022-07-04 в 14 36 40" src="https://user-images.githubusercontent.com/97882565/177146965-187194d6-3e62-485d-8cd5-268d980a1bc5.png">

https://user-images.githubusercontent.com/97882565/177147538-22b614cb-dc9e-485f-bdb0-8e714b9f81a0.mov

**Expected result**
The name of sorting dropdown should be centered, there should be space between fields.
<img width="796" alt="Снимок экрана 2022-07-04 в 14 40 57" src="https://user-images.githubusercontent.com/97882565/177147610-8f9ffabf-00ab-43d0-adb8-84798d30e373.png">

**User story and test case links**
User story 
Test case 

**Labels to be added**
"Bug", Priority ("pri: medium "), Severity ("severity: minor"), Type UI

**Comment by litvinets** [comment]
@OksanaGuz fixed!
Depending on the page size, they will be closer and further from each other.
![image](https://user-images.githubusercontent.com/27493959/178119983-acfa8ce0-97dc-4a58-af98-93117250a921.png)
![image](https://user-images.githubusercontent.com/27493959/178119989-78f0fc0d-76b1-4658-9498-68300f547f02.png)
![image](https://user-images.githubusercontent.com/27493959/178119994-2b4ae642-2e51-4638-b8e6-c58d0310eee0.png)

**Comment by OksanaGuz** [comment]
Verified.
