### ISSUE TITLE
[Search page "Filter"] Filter is not aligned

### ISSUE THREAD

**Issue by OksanaGuz** [ita-social-projects/OoS-Frontend#1424]
Environment: macOS Big Sur 11.5.1; Chrome version 99.0.4844.51.
Reproducible: always.
Build found: gcp-0.0.94

**Preconditions**

1. Be on the search page

**Steps to reproduce**
1. Observe filter alignment

**Actual result**
Filter is not aligned. 

<img width="172" alt="Снимок экрана 2022-07-05 в 14 44 27" src="https://user-images.githubusercontent.com/97882565/177320104-4f25e0d6-0766-4c5c-bf84-b7d60c6bb877.png">

**Expected result**
Fields should be aligned in one line.

<img width="169" alt="Снимок экрана 2022-07-05 в 14 44 52" src="https://user-images.githubusercontent.com/97882565/177320178-9edbf13b-5ab2-4afd-9109-ccf3fd7468bf.png">

**User story and test case links**
User story 
Test case

**Labels to be added**
"Bug", Priority ("pri: Medium"), Severity ("severity: Trivial"), Type UI

**Comment by litvinets** [comment]
fixed
