### ISSUE TITLE
[Search] Search is not performed from the main page

### ISSUE THREAD

**Issue by OksanaGuz** [ita-social-projects/OoS-Frontend#1425]
Environment: macOS Big Sur 11.5.1; Chrome version 99.0.4844.51.
Reproducible: always.
Build found: gcp-0.0.94

**Preconditions**

1. Be on the main page as any type of user

**Steps to reproduce**
1. Click on search field
2. Do the search (e.g. Танці)

**Actual result**
Result is shown for a second and then displays all workshops

https://user-images.githubusercontent.com/97882565/177326096-ec46eb2b-3acd-4559-bb23-de82a334877d.mov

**Expected result**
Page should show only workshops found by query

**User story and test case links**
User story https://github.com/ita-social-projects/OoS-Backend/issues/23
Test case
**Labels to be added**
"Bug", Priority ("pri: high"), Severity ("severity:major"), Type ("UI, "Functional")

**Comment by litvinets** [comment]
fixed

**Comment by OksanaGuz** [comment]
Verified.

**Comment by OksanaGuz** [comment]
The bug is reproduced again

https://user-images.githubusercontent.com/97882565/183291455-d17e0483-a98c-4011-a06b-1233a981f33c.mov

**Comment by koliapatskal** [comment]
Fixed
