### ISSUE TITLE
[Create Workshop] "Підпорядкування" dropdown is present in the workshop creation page

### ISSUE THREAD

**Issue by OksanaGuz** [ita-social-projects/OoS-Frontend#1429]
Environment: macOS Big Sur 11.5.1; Chrome version 99.0.4844.51.
Reproducible: always.
Build found: gcp-0.0.94

**Preconditions**

1. Follow the link https://oos.dmytrominochkin.cloud/#/
2. Log into OoS website as SP
3. Select «Мої гуртки» in the menu bar at the top right corner
4. At least 1 workshop has already been registered or not
5. Click on the “Додати гурток” button

**Steps to reproduce**
1. Fill all mandatory fields and go to "Опис" section 
2. Click on "Підпорядкування" dropdown

**Actual result**
There is no points to choose. "Підпорядкування" dropdown is present on the workshop creation page
<img width="344" alt="Снимок экрана 2022-07-05 в 16 59 24" src="https://user-images.githubusercontent.com/97882565/177345343-e5ec649d-3f00-43d7-ace0-387d037de307.png">

**Expected result**
 "Підпорядкування" should present on the workshop edition page and not to be on the workshop creation page

**User story and test case links**

User story [637](https://github.com/ita-social-projects/OoS-Backend/issues/637)
Postpone until story is done.
Waiting until validated design

**Labels to be added**
"Bug", Priority ("pri: "), Severity ("severity:"), Type ("UI, "Functional"), "API" (for back-end bugs).

**Comment by litvinets** [comment]
@OksanaGuz  this story does not relate to this functionality 
according to the https://github.com/ita-social-projects/OoS-Backend/issues/637 this is about editing ministry for admins.
this functionality is related to provider that edits/creates workshops and it has to be on the creation workshop page as well, it is not a bug
