### ISSUE TITLE
[Create/Edit workshop "Опис"] "Далі" button is disabled when mandatory fields are filled correctly

### ISSUE THREAD

**Issue by OksanaGuz** [ita-social-projects/OoS-Frontend#1456]
Environment: macOS Big Sur 11.5.1; Chrome version 99.0.4844.51.
Reproducible: always.
Build found: gcp-0.0.94

**Preconditions**

1. Log in as SP 
2. Go to "Мої Гуртки" page
3. Click on "Додати новий гурток" or "Редагувати" button
4. Go to "Опис" creation step

**Steps to reproduce**
1. Fill all mandatory fields with correct data
2. Take a look to "Далі" button

**Actual result**
"Далі" button is disable. User is able to move further by clicking tabs, but on the last creation/edition step workshop will not be created/edited
<img width="365" alt="Снимок экрана 2022-07-12 в 15 22 46" src="https://user-images.githubusercontent.com/97882565/178489865-1389f7a4-799f-4a3c-a81a-180d8649f327.png">
<img width="338" alt="Снимок экрана 2022-07-12 в 15 23 44" src="https://user-images.githubusercontent.com/97882565/178489869-6b90a955-052b-4432-879b-6b46549353ab.png">

**Expected result**
Click on "Далі" button should be enabled and open the next step of workshop creation/edition

**User story and test case links**
User story - https://github.com/ita-social-projects/OoS-Backend/issues/174
Test case - [OS-242](https://jira.softserve.academy/browse/OS-242)

**Labels to be added**
"Bug", Priority ("pri: high"), Severity ("severity:medium")

**Comment by litvinets** [comment]
fixed (submit/save workshop) does not work for now, but exact this issue is fixed

**Comment by OksanaGuz** [comment]
Verified
