### ISSUE TITLE
[Photo] System doesn't allow upload photo 512x286 px

### ISSUE THREAD

**Issue by OksanaGuz** [ita-social-projects/OoS-Frontend#1464]
Environment: macOS Big Sur 11.5.1; Chrome version 99.0.4844.51.
Reproducible: always.
Build found: gcp-0.0.94

**Preconditions**

1. Log in as SP
2. Click on "Додати новий гурток" or "Редагувати"

**Steps to reproduce**
1. Load 512x286 px photo in the "Про Гурток" step
2. Load 512x286 px photo in the "Опис" step
3. Load 512x286 px photo in the "Викладачі" step

**Actual result**
"Зображення не достатнього розміру.
Мінімальні розміри: ширина 512px, висота 250px." message appears
<img width="563" alt="Снимок экрана 2022-07-13 в 13 42 20" src="https://user-images.githubusercontent.com/97882565/178715438-11a02e8c-c53b-4b76-beab-311f858f9c4d.png">

**Expected result**
System should allow to upload photo with minimal size - 512x286 px

**User story and test case links**
User story https://github.com/ita-social-projects/OoS-Frontend/wiki/Images
Test case

**Labels to be added**
"Bug", Priority ("pri: medium "), Severity ("severity: minor")

**Comment by litvinets** [comment]
fixed

**Comment by OksanaGuz** [comment]
@litvinets User story has been updated. Minimum width of input image:512x300. Bug is reproducible.
