### ISSUE TITLE
[Main page] In the first application load page does not load completely

### ISSUE THREAD

**Issue by OksanaGuz** [ita-social-projects/OoS-Frontend#1473]
Environment: macOS Big Sur 11.5.1; Chrome version 99.0.4844.51.
Reproducible: always.
Build found: gcp-0.0.94

**Preconditions**
Pozashkillya page is closed

**Steps to reproduce**
1. Open the application
2. Refresh the page

**Actual result**
Page loaded completely only after refresh.

https://user-images.githubusercontent.com/97882565/179743316-1f0666a3-8288-43cc-a2ec-821f5e9de9e4.mov

**Expected result**

Page should load completely always.

**Labels to be added**
"Bug", Priority ("pri: high"), Severity ("severity: Major"), Type ("UI, "Functional")

**Comment by litvinets** [comment]
fixed

**Comment by ViktoriiaHrytchyna** [comment]
This bug is not reproduced.
