### ISSUE TITLE
[Notifications] If user does not have any notifications, the item is highlighted with "0" number

### ISSUE THREAD

**Issue by OksanaGuz** [ita-social-projects/OoS-Frontend#1475]
Environment: macOS Big Sur 11.5.1; Chrome version 99.0.4844.51.
Reproducible: always.
Build found: gcp-0.0.94

**Preconditions**

1. User is logged in.
2. User has no unread notifications.

**Steps to reproduce**
1. Take a look to notification item

**Actual result**
There is "0" number near the bell
<img width="74" alt="Снимок экрана 2022-07-20 в 14 56 28" src="https://user-images.githubusercontent.com/97882565/179976006-1c4a674e-eb14-4819-9989-b3d96ad63ecb.png">

**Expected result**

If user does not have any notifications, the item should be without any numbers

<img width="56" alt="Снимок экрана 2022-07-20 в 14 58 44" src="https://user-images.githubusercontent.com/97882565/179976387-d711af13-db26-47ff-812f-2c8b48797d07.png">

**User story and test case links**
User story - [204](https://github.com/ita-social-projects/OoS-Backend/issues/204)
Test case - [OS-479](https://jira.softserve.academy/browse/OS-479)

**Labels to be added**
"Bug", Priority ("pri: medium"), Severity ("severity: minor")

**Comment by litvinets** [comment]
fixed!
