### ISSUE TITLE
[Wrong Page] - create wrong-page wrapper if the link is incorrect

### ISSUE THREAD

**Issue by litvinets** [ita-social-projects/OoS-Frontend#1478]
![image](https://user-images.githubusercontent.com/27493959/181213011-b9a9dcdf-c692-4961-963d-e88687bc64b7.png)
https://www.figma.com/file/YRYP4zAAchOyYMgdoeP782/MoE-%7C-Dev-Team?node-id=13881%3A8110

**Comment by LeraKornienko** [comment]
done
