### ISSUE TITLE
Remove workshops from the children cards

### ISSUE THREAD

**Issue by OksanaGuz** [ita-social-projects/OoS-Frontend#1480]
Remove workshops from the children cards.
<img width="257" alt="Снимок экрана 2022-07-20 в 18 56 10" src="https://user-images.githubusercontent.com/97882565/180028509-0664e079-2002-4c63-a3a9-2f771a9f8e01.png">

Add additional information to the child's card  from child info instead of child's workshops 
<img width="529" alt="Снимок экрана 2022-07-20 в 18 56 55" src="https://user-images.githubusercontent.com/97882565/180028851-523d4ff2-51f1-4a56-837b-14cc4cff9ada.png">

**Comment by litvinets** [comment]
@OksanaGuz  done!
