### ISSUE TITLE
Rename notification text

### ISSUE THREAD

**Issue by OksanaGuz** [ita-social-projects/OoS-Frontend#1481]
If user doesn't have any notifications the message should be "У вас немає нових сповіщень"
<img width="273" alt="Снимок экрана 2022-07-20 в 19 04 16" src="https://user-images.githubusercontent.com/97882565/180030234-f1efd991-cef0-48ce-a463-d93ff7d7f097.png">

**Comment by litvinets** [comment]
@OksanaGuz  done

**Comment by OksanaGuz** [comment]
Verified.
