### ISSUE TITLE
[Personal cabinet Assistant] The title is "Кабінет Надавача" instead of "Кабінет Заступника Директора"

### ISSUE THREAD

**Issue by OksanaGuz** [ita-social-projects/OoS-Frontend#1509]
Environment: macOS Big Sur 11.5.1; Chrome version 101.0.4951.54.
Reproducible: always.
Build found: gcp-0.0.89

**Preconditions**

1. Login as Assistant

**Steps to reproduce**

1. Go to 'Особистий кабінет'
2. Take a look to the title and the breadcrumbs.

**Actual result**
There is 'Кабінет надавача'
<img width="940" alt="Снимок экрана 2022-07-26 в 13 33 48" src="https://user-images.githubusercontent.com/97882565/180986181-e0983729-fc96-46c8-ba23-58d402d184e4.png">

**Expected result**
There should be 'Кабінет Заступника Директора'

<img width="701" alt="Снимок экрана 2022-07-26 в 13 35 46" src="https://user-images.githubusercontent.com/97882565/180986507-6d69cbb9-84f3-434f-a91b-affa3a416638.png">

**User story and test case links**
User story
Test case

**Labels to be added**
"Bug", Priority ("pri: high"), Severity ("severity: trivial")

**Comment by litvinets** [comment]
Адміністратор гуртка
Логін: sitilif100@nuesond.com
Пароль: -$!5LfhO

Надавач (Директор школи)
Логін: sasuke@gmail.com
Пароль: A12345a@

Користувач
Oleksandra Lytvynets  12:26 PM
naruto@gmail.com
Пароль: A12345a@

Адмін
admin@gmail.com
Тех адмін
Пароль: A12345a@

Заступник Директора
Логін: nisav89309@lenfly.com
Пароль: ry706-jO

**Comment by litvinets** [comment]
![image](https://user-images.githubusercontent.com/27493959/191211603-132bd9c1-3b0b-4a65-8b5f-cc25c9482357.png)
This user is provider deputy (застпуник)
Логін:rodivi6124@edxplus.com
Пароль: !n0w7_WT

**Comment by ViktoriiaHrytchyna** [comment]
Bug is fixed.
