### ISSUE TITLE
[Ministery Admin] - add functionality to craete admin ministery 

### ISSUE THREAD

**Issue by litvinets** [ita-social-projects/OoS-Frontend#1511]
1. create admins wrapper component
2. add banner that has dropdown button with options to create three types of admins 
3.  ![image](https://user-images.githubusercontent.com/27493959/181038085-02ff81c8-3550-40ef-9513-29cf54ca12f9.png)
![image](https://user-images.githubusercontent.com/27493959/181038450-43851fef-4b33-453a-8e23-efcd81d83a7a.png)
![image](https://user-images.githubusercontent.com/27493959/181039660-14c11773-4ec2-4b2f-801c-7087d262affb.png)

4.  add create-admin component
 ![image](https://user-images.githubusercontent.com/27493959/181037989-1fb9158d-1c22-4e56-8296-18b037acf107.png)

5. add basic functionality to create admin of ministry (all fields, but "city" is not allowed yet, you can just mock it for now)
6. the component should be added to the data module
7. don't forget about mobile view
you can find an example in provider-admins/ create provider admin
endpoints:
![image](https://user-images.githubusercontent.com/27493959/181039208-aae33c9d-69b6-45e2-b34f-fbaeeb74acbf.png)

**Comment by Illya97** [comment]
Done
