### ISSUE TITLE
[Info prompt about statuses] In the mobile version the text about statuses is cut off 

### ISSUE THREAD

**Issue by OksanaGuz** [ita-social-projects/OoS-Frontend#1513]
Environment: macOS Big Sur 11.5.1; Chrome version 101.0.4951.54.
Reproducible: always.
Build found: gcp-0.0.89

**Preconditions**

1. Log in as any type of user
2. Switch to mobile view (e.g. IPhone 12 pro)

**Steps to reproduce**
1. Go to "Мої заяви" page
2. Click on "i" icon
3. Click on the status "i" icon

**Actual result**
Text does not fit in a frame and does not have scrolling
<img width="542" alt="Снимок экрана 2022-07-27 в 13 30 11" src="https://user-images.githubusercontent.com/97882565/181225969-bcab43da-9a0b-4377-b9df-b92ff79f8d9a.png">

<img width="486" alt="Снимок экрана 2022-07-27 в 14 01 40" src="https://user-images.githubusercontent.com/97882565/181231734-b89d52b1-6bcf-4a55-9e43-dfbb060488d3.png">

**Expected result**
Informational prompt about statuses should be visible

**User story and test case links**
User story - [346](https://github.com/ita-social-projects/OoS-Frontend/issues/346)
Test case - [OS-533](https://jira.softserve.academy/browse/OS-533)

**Labels to be added**
"Bug", Priority ("pri: medium"), Severity ("severity: minor"), Type UI

**Comment by friranger1** [comment]
Done!
