### ISSUE TITLE
[Info prompt about statuses] Status Заблоковано should have another description

### ISSUE THREAD

**Issue by OksanaGuz** [ita-social-projects/OoS-Frontend#1514]
Environment: macOS Big Sur 11.5.1; Chrome version 101.0.4951.54.
Reproducible: always.
Build found: gcp-0.0.89

**Preconditions**

1. Log in as any type of user

**Steps to reproduce**

1. Go to "Мої заяви" page
2. Click on "i" icon

**Actual result**

"Заблоковано" status has the description - "Користувача заблоковано" 

**Expected result**
Status "Заблоковано" shall be displayed with description: «Ви порушили Правила користування платформою»

**User story and test case links**

User story - https://github.com/ita-social-projects/OoS-Frontend/issues/346
Test case - [OS-533](https://jira.softserve.academy/browse/OS-533)

Labels to be added
"Bug", Priority ("pri: medium"), Severity ("severity: minor"), Type UI

**Comment by litvinets** [comment]
fixed

**Comment by OksanaGuz** [comment]
Verified.
