### ISSUE TITLE
[Search field] The color of the letters is very light when entered into the field

### ISSUE THREAD

**Issue by OksanaGuz** [ita-social-projects/OoS-Frontend#1525]
Environment: macOS Big Sur 11.5.1; Chrome version 101.0.4951.54.
Reproducible: always.
Build found: gcp-0.0.89

**Preconditions**
Be on the main page/search result page

**Steps to reproduce**
1. Type letters into search field

**Actual result**
Letters is too light and become visible after clicking Search button
<img width="1176" alt="Снимок экрана 2022-07-29 в 14 10 59" src="https://user-images.githubusercontent.com/97882565/181747594-2afc331c-1b8e-42ac-9f73-7bde91c66434.png">

**Expected result**

Letters should be visible

**User story and test case links**
User story 
Test case

**Labels to be added**
"Bug", Priority ("pri: high "), Severity ("severity:trivial")

**Comment by koliapatskal** [comment]
Fixed. The letters became visible

**Comment by OksanaGuz** [comment]
Verified.
