### ISSUE TITLE
[Workshop creation] "Далі" button is disabled when all mandatory fields are filled

### ISSUE THREAD

**Issue by OksanaGuz** [ita-social-projects/OoS-Frontend#1529]
Environment: macOS Big Sur 11.5.1; Chrome version 101.0.4951.54.
Reproducible: always.
Build found: gcp-0.0.73

**Preconditions**

1. Log in as SP
2. Go to "Мої гуртки" page
3. Click on "Додати гурток" button

**Steps to reproduce**
1. Fill all mandatory fields on the "Про гурток" page
2. Take a look to the "Далі" button

**Actual result**
"Далі" button is disable. User able go to the next step by clicking on "Контакти" section
<img width="334" alt="Снимок экрана 2022-08-01 в 17 12 44" src="https://user-images.githubusercontent.com/97882565/182167304-cb4edfb6-9255-4b46-90fc-3d2b73ff6983.png">

**Expected result**
"Далі" button should be active

**User story and test case links**
User story
Test case 

**Labels to be added**
"Bug", Priority ("pri: high "), Severity ("severity: majot"), Type ("UI, "Functional")

**Comment by sivxkxn** [comment]
@OksanaGuz I checked it, but did not see this problem. I also noticed that on the screen of the defect that you do not have some fields after 'Підпорядкування'. Can you reproduce one more time and write more detailed conditions when this problem occurs.

![defect](https://user-images.githubusercontent.com/57331621/183159381-9557dacf-b253-4e16-bb62-4973deff6289.jpg)
