### ISSUE TITLE
[TopDirections/ GetDirections] - display amount of workshops for every top direction

### ISSUE THREAD

**Issue by litvinets** [ita-social-projects/OoS-Frontend#1604]
1) update the direction model, add workshopAmount and display it on the card
2) move the redirecting not on the card clicking but on the arrow clicking
![image](https://user-images.githubusercontent.com/27493959/187422889-b5c1b358-42c9-4405-ad05-7b7749a5b29c.png)
![image](https://user-images.githubusercontent.com/27493959/187423067-a5984fed-811e-475c-b467-08be817d3ab2.png)
![image](https://user-images.githubusercontent.com/27493959/187423141-615c2244-e124-48ca-9423-9e4997e03bf9.png)

related  bug: https://github.com/ita-social-projects/OoS-Frontend/issues/1112

**Comment by Illya97** [comment]
Done
