### ISSUE TITLE
[Children creation] Impossible to add child without social group

### ISSUE THREAD

**Issue by OksanaGuz** [ita-social-projects/OoS-Frontend#1616]
Environment: macOS Big Sur 11.5.1; Chrome version 101.0.4951.54.
Reproducible: always.
Build found: gcp-0.0.73

**Preconditions**

1. Log in as Parent
2. Go to "Інформація про дітей"
3. Click on "Додати дитину" button

**Steps to reproduce**
1. Fill all mandatory fields (Прізвище, Ім'я, По-батькові, Стать)
2. Tick checkbox
3. Click on "Зберегти" button

**Actual result**
Error message is shown. "Відсутня" social group is absent.
<img width="559" alt="Снимок экрана 2022-09-01 в 14 06 20" src="https://user-images.githubusercontent.com/97882565/187899860-2d44beb7-e253-48b6-b723-1434b7ba64f5.png">
<img width="630" alt="Снимок экрана 2022-09-01 в 14 07 28" src="https://user-images.githubusercontent.com/97882565/187899921-ba373c22-d67c-4175-9eba-bc5d5620d16b.png">
<img width="476" alt="Снимок экрана 2022-09-01 в 14 15 19" src="https://user-images.githubusercontent.com/97882565/187901272-5425931d-ac78-4291-98f6-ff4eef8b7cc0.png">

**Expected result**
Social group is not mandatory so children should be created without filling the optional fields.
"Відсутня" social group should be set by default.

**User story and test case links**

User story:
https://github.com/ita-social-projects/OoS-Frontend/wiki/Validation-Rules-For-All-the-Forms

**Labels to be added**
"Bug", Priority ("pri: high"), Severity ("severity: major")

**Comment by koliapatskal** [comment]
Fixed

**Comment by OksanaGuz** [comment]
@koliapatskal "Соціальна група" should be "відсутня" by default
<img width="468" alt="Снимок экрана 2022-09-05 в 11 50 53" src="https://user-images.githubusercontent.com/97882565/188408963-17d36d10-dd23-4e94-a6a0-c1aa5eb0659e.png">
