### ISSUE TITLE
[Workshop creation] Workshop can not be created if address street more than 30 chars

### ISSUE THREAD

**Issue by OksanaGuz** [ita-social-projects/OoS-Frontend#1617]
Environment: macOS Big Sur 11.5.1; Chrome version 101.0.4951.54.
Reproducible: always.
Build found: gcp-0.0.73

**Preconditions**
Log in as SP
Go to "Мої гуртки"
Click on "Додати гурток" button

**Steps to reproduce**
1. Fill all mandatory fields on the "Про гурток" section and click on "Далі"
2. Fill all mandatory fields on the "Опис" section and click on "Далі"
3. Set Місто - Київ 
4. Set Вулиця - вул. Богдана Гаврилишина (Ванди Василевської)
5. Set Будинок - 13/1 
6. Click on "Далі"
7. Click on "Зберегти" button

**Actual result**
"Нажаль виникла помилка" error message appears. Workshop is not created.
<img width="1440" alt="Снимок экрана 2022-09-01 в 14 25 13" src="https://user-images.githubusercontent.com/97882565/187904487-5dc0307e-4a1f-4c23-ac25-98b98419036b.png">

**Expected result**
Workshop should be created as Street should support up to 60 characters

**User story and test case links**
User story - https://github.com/ita-social-projects/OoS-Frontend/wiki/Validation-Rules-For-All-the-Forms

**Labels to be added**
"Bug", Priority ("pri:  high"), Severity ("severity: major")

**Comment by litvinets** [comment]
build number was changed to max 15 characters length
