### ISSUE TITLE
[Notifications] Link in the notification leads to 404 page

### ISSUE THREAD

**Issue by OksanaGuz** [ita-social-projects/OoS-Frontend#1624]
Environment: macOS Big Sur 11.5.1; Chrome version 99.0.4844.51.
Reproducible: always.
Build found: gcp-0.0.94

**Preconditions**

1. Parent applied for workshop
2. SP received the notification

OR

1. Parent applied for workshop
2. SP received the notification
4. SP confirmed application
5. Parent received the notification

**Steps to reproduce**
1. Click on received notification
2. Click on the arrow

**Actual result**
404 page appears

https://user-images.githubusercontent.com/97882565/188123571-202a610f-f233-43bf-bdd4-f55a381b5479.mov

**Expected result**
The link should leads to "Мої заяви" page

**User story and test case links**
User story https://github.com/ita-social-projects/OoS-Backend/issues/204
Test case

**Labels to be added**
"Bug", Priority ("pri: "), Severity ("severity:"), Type ("UI, "Functional"), "API" (for back-end bugs).

**Comment by Illya97** [comment]
Fixed

**Comment by OksanaGuz** [comment]
Verified.
