### ISSUE TITLE
[Notifications] - handle new type of notifications

### ISSUE THREAD

**Issue by litvinets** [ita-social-projects/OoS-Frontend#1625]
Display information about workshop status change in notifications component

- Набір у гурток "Назва гуртка" відкрито
- Набір у гурток "Назва гуртка" призупинено

![image](https://user-images.githubusercontent.com/27493959/188123955-85b49e16-5a4c-4a93-ba35-4412374e8b42.png)

**Comment by Illya97** [comment]
Done
