### ISSUE TITLE
[GetTopDirections] - update request with city filtration

### ISSUE THREAD

**Issue by litvinets** [ita-social-projects/OoS-Frontend#1627]
![image](https://user-images.githubusercontent.com/27493959/188137751-ddacab65-f3bf-4ec3-b253-8e4114fc8c48.png)
Request URL: https://api.oos.dmytrominochkin.cloud/api/v1/Statistic/GetWorkshops?Limit=12&City=%D0%9B%D1%8C%D0%B2%D1%96%D0%B2&Latitude=49.839683532714844&Longitude=24.02971649169922&catottgId=15447
Request URL: https://api.oos.dmytrominochkin.cloud/api/v1/Statistic/GetDirections

**Comment by Illya97** [comment]
Done
