### ISSUE TITLE
[SP creation] Сannot create an organization if the name of the founder is more than 30 char

### ISSUE THREAD

**Issue by nikitaekaterinin** [ita-social-projects/OoS-Frontend#1636]
**Environment:** Windows 10, Сhrome version 104.0.5112.102.
**Reproducible:** always.
** Build:** gcp-0.0.246.

**Preconditions**
1. Click on "Зареєструватися" button.
2. Select "Надавач послуг" option.
3. Complete all registration steps till "Реєстрація нового закладу" page appears.

**Steps to reproduce**
1. Fill all required fields in "Інформація про заклад" section and click "Далі" button.
2. Fill all required fields in "Контакти" section and click "Далі" section.
3. Fill all required fields in "Опис" section.
4. Set "Малюшевськевич Ярослава Константинівна" in "Засновник" field.
5. Tick checkboxes and click "Зберегти" button.

**Actual result**
The data is displayed on the screen and "Перевірте введені дані. Електронна пошта, номер телефону та ІПН/ЄДРПО мають бути унікальними" error message appears.
![photo1662550131](https://user-images.githubusercontent.com/109725022/188873767-ccefdb97-db0b-4a3c-9680-a75344e0b4be.jpeg)

**Expected result**
Fields should support up to 60 charachters.

<img width="668" alt="176418318-9d15d9ec-062d-4644-9337-e7a99bd9324e" src="https://user-images.githubusercontent.com/109725022/188873822-26ead66b-bb5c-4888-8dc3-80246929d8cf.png">

**User story and test case links**
User story - https://github.com/ita-social-projects/OoS-Frontend/wiki/Validation-Rules-For-All-the-Forms

**Labels to be added**
"Bug", Priority ("pri: medium"), Severity ("severity: major").

**Comment by litvinets** [comment]
@nikitaekaterinin  as you cna see from eth error, teh problem is not in the length of the founder field, but in the uniqueness  of edrpou/email/phone field

**Comment by ViktoriiaHrytchyna** [comment]
Bug is not fixed.
