### ISSUE TITLE
[Application Notification] - on application-notifacation click it redirects to the wrong tab

### ISSUE THREAD

**Issue by litvinets** [ita-social-projects/OoS-Frontend#1680]
when user clicks on the arrow, it should redirects to the correct application tab
![image](https://user-images.githubusercontent.com/27493959/191958636-1ad3b4ba-878f-4792-b0a8-c812807099b7.png)
![image](https://user-images.githubusercontent.com/27493959/191958725-029ec33f-f576-4a66-805f-9adcf6b18ff2.png)

**Comment by koliapatskal** [comment]
#1731
