### ISSUE TITLE
[Registration SP/Parent] Impossible enter more than 30 chars in the ПІБ fields

### ISSUE THREAD

**Issue by OksanaGuz** [ita-social-projects/OoS-Frontend#1685]
Environment: macOS Big Sur 11.5.1; Chrome version 99.0.4844.51.
Reproducible: always.
Build found: gcp-0.0.94

**Preconditions**

1. Go to main page https://oos.dmytrominochkin.cloud/#/
2. Click on "УВІЙТИ/ЗАРЕЄСТРУВАТИСЯ" button in top right corner
3. Click on "Зареєструватися" hyperlink
4. Click on "Надавач послуг"/"Споживач" button

**Steps to reproduce**
1. Fill "Прізвище", "ім'я", "По-батькові" more  than 30 chars

**Actual result**
Fields support up to 30 characters

**Expected result**
The user should be able to enter 60 characters
![image](https://user-images.githubusercontent.com/97882565/192279000-dab69a5d-7b80-45d3-b133-715aa9915cd0.png)

**User story and test case links**
User story - https://github.com/ita-social-projects/OoS-Frontend/wiki/Registration
Test case - [OS-313](https://jira.softserve.academy/browse/OS-313) [OS-308](https://jira.softserve.academy/browse/OS-308)

**Labels to be added**
"Bug", Priority ("pri: medium"), Severity ("severity: minor"), Type ( "Functional")

**Comment by ViktoriiaHrytchyna** [comment]
This bug is not reproduced.
