### ISSUE TITLE
[Workshop/Provider details] - set current selected tab to the query param

### ISSUE THREAD

**Issue by litvinets** [ita-social-projects/OoS-Frontend#1711]
for provider/workshop details the currently selected tab should be set to the URL, so when we cope with the URL we can navigate to the correct selected tab
![image](https://user-images.githubusercontent.com/27493959/194292561-305ddd02-16ed-4c30-8d91-463956847da3.png)
Similar functionality is implemented for cabinet/application view
![image](https://user-images.githubusercontent.com/27493959/194292349-8e411729-f43f-4e87-9122-52f7fe9bf5b9.png)

**Comment by friranger1** [comment]
Done!
