### ISSUE TITLE
[Radius configuration] - custom radius configuration

### ISSUE THREAD

**Issue by litvinets** [ita-social-projects/OoS-Frontend#1743]
1. add the opportunity to custom change the radius for the map view
https://codepen.io/gjfrichard/pen/yLJQwWv

try to consider using the such slider
min 1 km
max 10 km
by default 5 km
![image](https://user-images.githubusercontent.com/27493959/196684835-263c4c80-29b5-4e54-bf84-eb2077699d58.png)

2. add a warning message that only up to 100 nearest workshops will be displayed

**Comment by khrMykhailo** [comment]
We need to provide changes on BE for this improvement. "GetByFilter" endpoint has to include queryParam "radius" or something like it

**Comment by khrMykhailo** [comment]
Desktop mockup:  https://www.figma.com/file/YRYP4zAAchOyYMgdoeP782/MoE-%7C-Dev-Team?node-id=1%3A4115
Mobile mockup: https://www.figma.com/file/YRYP4zAAchOyYMgdoeP782/MoE-%7C-Dev-Team?node-id=2388%3A1285

**Comment by litvinets** [comment]
RadiusKm

**Comment by litvinets** [comment]
@khrMykhailo **UPDATE** min radius should me 2km, max radius 10km, default 5km
