### ISSUE TITLE
[Checkbox Dropdown]- dropdown should be stick to the input 

### ISSUE THREAD

**Issue by litvinets** [ita-social-projects/OoS-Frontend#1836]
multiselect dropdown shoudl be stuck to the referred input and not move while page scrolling
![image](https://user-images.githubusercontent.com/27493959/201679351-2580761e-f486-4655-93c9-6f4fa713a005.png)
![image](https://user-images.githubusercontent.com/27493959/201679679-4af4962f-2771-47a1-a585-89959be2d8cc.png)
![image](https://user-images.githubusercontent.com/27493959/201682545-0a2100fe-4765-4217-bd03-81b093de6897.png)

**Comment by koliapatskal** [comment]
Fixed by #1849
