### ISSUE TITLE
Filters component

### ISSUE THREAD

**Issue by dmitryy90** [ita-social-projects/OoS-Frontend#186]
Create a layout for filters:
![image](https://user-images.githubusercontent.com/1244989/116709461-5bea2100-a9d9-11eb-8f4e-45ddf6bbf56d.png)

**Comment by karyna-kifiuk** [comment]
https://github.com/ita-social-projects/OoS-Frontend/issues/2674

**Comment by karyna-kifiuk** [comment]
https://github.com/ita-social-projects/OoS-Frontend/issues/2675

**Comment by karyna-kifiuk** [comment]
https://github.com/ita-social-projects/OoS-Frontend/issues/2676
