### ISSUE TITLE
[Applying for a workshop] Inconsistency of the text on the "Заява на гурток" page of the design.

### ISSUE THREAD

**Issue by ViktoriiaHrytchyna** [ita-social-projects/OoS-Frontend#1870]
**Environment:** Windows 10, 64-bit, Google Chrome 107.0.5304.107.
**Reproducible:** always.

**Preconditions**
Follow the link https://oos.dmytrominochkin.cloud/#/
1.Log into system as a Parent (e.g. 'email'="[xixofa7680@probdd.com](mailto:xixofa7680@probdd.com)", 'Password'="Qazwsx789!").
2.Open any workshop's page by clicking the "Детальніше" button on the workshop card.
3.Click on the "Подати заяву" button.
4.The "Заява на гурток" page is opened.

**Steps to reproduce**
Look at thecheckboxes and the text next to them on the "Заява на гурток" page.

**Actual result**
The alignment of the checkboxes text on the "Заява на гурток" page is not displayed according to the mock-up.
![Снимок экрана 2022-11-28 192504](https://user-images.githubusercontent.com/115226563/204354004-26c43b44-715d-4e25-b080-fd8a8fffd42e.jpg)

**Expected result**
The alignment of the checkboxes text on the "Заява на гурток" page is displayed according to the mock-up.
![Снимок экрана 2022-11-29 135822](https://user-images.githubusercontent.com/115226563/204523401-7fb19b0d-0f99-41d6-af82-91225553ecda.jpg)

**User story and test case links**
User story https://github.com/ita-social-projects/OoS-Backend/issues/131

**Labels to be added**
Bug, pri: very low, severity: trivial, UI.

**Comment by litvinets** [comment]
fixed!

**Comment by ViktoriiaHrytchyna** [comment]
This bug is fixed.
