### ISSUE TITLE
[Workshop creation] The workshop cannot be created because the "Населений пункт" field cannot be filled.

### ISSUE THREAD

**Issue by ViktoriiaHrytchyna** [ita-social-projects/OoS-Frontend#1879]
**Environment:** Windows 10, 64-bit, Google Chrome 107.0.5304.107.
**Reproducible:** always.

**Preconditions**
1. Follow the link https://oos.dmytrominochkin.cloud/#/
2. Log into system as a SP (e.g. 'email'="[gadigob939@probdd.com](mailto:gadigob939@probdd.com)", 'Password'="Qazwsx789!").
3. Go to "Мої гуртки".
4. Click on "Додати гурток" button.

**Steps to reproduce**
1. Fill all mandatory fields on the "Про гурток" section and click on "Далі"
2. Fill all mandatory fields on the "Опис" section and click on "Далі"
3. Set Місто - Київ
4. Set Вулиця - вул. Володимирська
5. Set Будинок - 25
6. Look at "Населений пункт" fild.

**Actual result**
"Населений пункт" field is cleared and an error appears that the field is mandatory.
![Снимок экрана 2022-11-30 132306](https://user-images.githubusercontent.com/115226563/204790543-98bd1ed0-a8bf-46a1-b370-a7b8757dd7e7.jpg)

**Expected result**
"Населений пункт" field is not cleared and workshop is created.

**Labels to be added**
"Bug", Priority ("pri: high"), Severity ("severity: major")

**Comment by litvinets** [comment]
![image](https://user-images.githubusercontent.com/27493959/209622646-c6707b81-39ff-4761-99a3-2253831deba3.png)
Request URL: https://api.oos.dmytrominochkin.cloud/api/v1/Geocoding
![image](https://user-images.githubusercontent.com/27493959/209622693-51bbcc7e-88c7-4016-8cf4-12eef47943b3.png)

expected response:
![image](https://user-images.githubusercontent.com/27493959/209622884-9ba28f44-6725-4c10-9158-3c8637eb9c13.png)

actual response 
![image](https://user-images.githubusercontent.com/27493959/209622987-1ddf033a-9eea-4fa8-87a2-593d48e944ef.png)
