### ISSUE TITLE
[Parent personal information] 404 error when press the 'Редагувати' button in the 'Персональні дані' field.

### ISSUE THREAD

**Issue by ViktoriiaHrytchyna** [ita-social-projects/OoS-Frontend#1899]
**Environment:** Windows 10, 64-bit, Google Chrome 107.0.5304.107.
**Reproducible:** always.

**Preconditions**
1.Go to OoS (https://oos.dmytrominochkin.cloud/). 
2.User - Parent role is created and logged in (e.g. "Email" = 'xixofa7680@probdd.com', "password" = 'Qazwsx789!').
3.The location is selected (e.g. Kyiv).
4.The interested workshop (Шахмати для початківців) is found and the 'Workshop' page is opened.
5.The 'Application' page is selected (by clicking the 'Подати заяву' button).

**Steps to reproduce**
1. Select the 'Подати дані про себе' option.
2. Press the 'Редагувати' button in the 'Персональні дані' field.

**Actual result**
404 error when press the 'Редагувати' button in the 'Персональні дані' field.
![Снимок экрана 2022-12-13 222700](https://user-images.githubusercontent.com/115226563/207443353-abb8f702-066a-4832-abb7-6d33a79cbd29.jpg)

**Expected result**
After press the 'Редагувати' button in the 'Персональні дані' field opened 'Редагування особистої інформації' page.
![Снимок экрана 2022-12-13 230624](https://user-images.githubusercontent.com/115226563/207443491-7b18d0a6-8ce2-42ff-a64a-342ad0aeb9cd.jpg)

**Labels to be added**
"Bug", Priority ("medium"), Severity ("medium"), Type ("Functional").

**Comment by litvinets** [comment]
@ViktoriiaHrytchyna  fixed!

**Comment by ViktoriiaHrytchyna** [comment]
Bug is fixed.
