### ISSUE TITLE
[Notification] Notification badges in the 'Заяви' tab and header don't disappear.

### ISSUE THREAD

**Issue by ViktoriiaHrytchyna** [ita-social-projects/OoS-Frontend#1902]
**Environment:** Windows 10, 64-bit, Google Chrome 107.0.5304.107.
**Reproducible:** always.

**Preconditions**
1.Go to OoS ([link](https://oos.dmytrominochkin.cloud/)) 
2.There is at least one workshop registered by Service provider (@workshop)
3.Parent has applied to @workshop for himself (@application)
4.Parent has no unread notifications
5.Service Provider changed the @application status  (e.g. from  'Очікує підтвердження' to 'Зараховано')
6.Parent is logged in

**Steps to reproduce**
1. Check that notification is displayed in the top right part of a header.
2. Click on the bell icon.
3. Click the 'Переглянути' link in the tooltip.
4. Go to the 'Заяви' tab of the personal cabinet.
5. Pay attention on the notification badge in the top right part of a header.

**Actual result**
Notification badges in the 'Заяви' tab and header don't disappear.
![Снимок экрана 2022-12-14 122837](https://user-images.githubusercontent.com/115226563/207576597-e07e4e24-57e3-4fac-a162-943d309da4be.jpg)

**Expected result**
Notification badges in the 'Заяви' tab and header disappear after viewing.

**Labels to be added**
"Bug", Priority ("medium"), Severity ("low"), Type ("UI, "Functional").

**Comment by koliapatskal** [comment]
Fixed
