### ISSUE TITLE
[Workshop] The parent does not return to the previous page after adding another child.

### ISSUE THREAD

**Issue by ViktoriiaHrytchyna** [ita-social-projects/OoS-Frontend#1911]
**Environment:** Windows 10, 64-bit, Google Chrome 107.0.5304.107.
**Reproducible:** always.

**Preconditions**
1.Log in as Parent ( email: jeteged298@fanneat.com, password: Qazwsx789!).
2.Child can be added or no.
3.Interested workshop is found.
4.Workshop details page is opened.

**Steps to reproduce**
1. Click on the "Подати Заяву" button.
2. Click on the "Додати ще одну дитину" button.
3. Fill all mandatory fields.
4. Click on the "Зберегти" button.
5. Pay attention to the page that opens.

**Actual result**
User is returned to the 'Заява на гурток' page.
![Screenshot_2](https://user-images.githubusercontent.com/115226563/207837241-8a3a4d2a-4ceb-4dd0-aeba-73d1c3064311.png)

**Expected result**
User is returned to the 'Інформація про дітей' page.

**Labels to be added**
"Bug", Priority ("medium"), Severity ("low"), Type ("Functional").

**Comment by litvinets** [comment]
@ViktoriiaHrytchyna  fixed!

**Comment by ViktoriiaHrytchyna** [comment]
Bug is fixed
