### ISSUE TITLE
[Сabinet] The pop-up appears on the left edge of the page not under the "i" icon.

### ISSUE THREAD

**Issue by ViktoriiaHrytchyna** [ita-social-projects/OoS-Frontend#1919]
**Environment:** Windows 10, 64-bit, Google Chrome 107.0.5304.107.
**Reproducible:** always.

**Preconditions**
1.Go to https://oos.dmytrominochkin.cloud/#/.
2.Log in as SP assistant or SP.
3.At least 1 application should exist in the Cabinet .
4.Go to "Заяви" by pressing button "Мої заяви" on the top right corner drop down list.

**Steps to reproduce**
1. Click on the "i" icon in the right corner of the page.
2. Pay attention to the placement of pop-up.
3. Click on empty area on the page.
4. Click on the status icon of any of existing application.
5. Pay attention to the placement of pop-up.

**Actual result**
A pop-up appears under the 'і' icon after pressing it.
![Screenshot_3](https://user-images.githubusercontent.com/115226563/208524893-be432164-9d54-48f3-b69b-0b02b34c17f5.png)
![Screenshot_4](https://user-images.githubusercontent.com/115226563/208525171-fb001520-2678-446c-a2bc-28d836f026e8.png)

**Expected result**
A pop-up does not appear under the 'i' icon, but on the left side of the page.

**Labels to be added**
"Bug", Priority ("low "), Severity ("low"), Type ("UI").

**Comment by koliapatskal** [comment]
@ViktoriiaHrytchyna, fixed

**Comment by ViktoriiaHrytchyna** [comment]
Bug is fixed
