### ISSUE TITLE
[Personal cabinet] Statements are displayed with different statuses.

### ISSUE THREAD

**Issue by ViktoriiaHrytchyna** [ita-social-projects/OoS-Frontend#1929]
**Environment:** Windows 10, 64-bit, Google Chrome 107.0.5304.107.
**Reproducible:** always.

**Preconditions**
1.Go to OoS (https://oos.dmytrominochkin.cloud/).
2.User - Parent role is created and logged in (e.g. "Email" = '[jeteged298@fanneat.com](mailto:jeteged298@fanneat.com)', "password" = 'Qazwsx789!').
3.Parent has statements with different statuses.

**Steps to reproduce**
1.Click on the bell icon in the top right part of a header.
2.Click the '3 заявки відхилено' link in the tooltip.
3.Pay attention to the 'Зараховано' filter and the statements statuses displayed on the page. 

**Actual result**
Statements are not filtered and are displayed with different statuses that do not match the filter.
![Screenshot_5](https://user-images.githubusercontent.com/115226563/208988563-409c2c3b-7630-4b57-a732-87d3d388118a.png)

**Expected result**
Statements are filtered and displayed according to the selected filter.

**Labels to be added**
"Bug", Priority ("low"), Severity ("low"), Type ("UI").

**Comment by litvinets** [comment]
@ViktoriiaHrytchyna naming in the notification text will be fixed
the rest is not reproducible
![image](https://user-images.githubusercontent.com/27493959/209427512-4cf5d702-891c-4e67-bf2f-b3bb4c80c0f0.png)

**Comment by ViktoriiaHrytchyna** [comment]
Bug is reproduced for SP:  gadigob939@probdd.com;    password:  Qazwsx789!
![Screenshot_10](https://user-images.githubusercontent.com/115226563/209723613-1602b2a3-c594-431b-a119-99997dd524e3.png)

**Comment by litvinets** [comment]
@ViktoriiaHrytchyna thank you for reporting this bug! Please, check it for all the rolled! Should work correctly!

**Comment by ViktoriiaHrytchyna** [comment]
Fixed
