### ISSUE TITLE
[New workshop] The name of the button does not meet the design requirements.

### ISSUE THREAD

**Issue by ViktoriiaHrytchyna** [ita-social-projects/OoS-Frontend#1946]
**Environment:** Windows 10, 64-bit, Google Chrome 107.0.5304.107.
**Reproducible:** always.

**Preconditions**
1.Follow the link https://oos.dmytrominochkin.cloud/#/
2.Log in as SP (e.g. 'email'="[gadigob939@probdd.com](mailto:gadigob939@probdd.com)", 'Password'="Qazwsx789!")
3.Select «Мої гуртки» in the menu bar at the top right corner.
4.Click on the “Додати гурток” button and fill in all mandatory fields of the "Про гурток" tab.

**Steps to reproduce**
1. Click on the button 'Далі'.
2. Pay attention to the name of the button at the bottom of the page.

**Actual result**
The button is called "Titles.Actions.Back".
![Screenshot_8](https://user-images.githubusercontent.com/115226563/210054836-f29f6fac-cef2-44fa-9473-caf5eaef36e6.png)

**Expected result**
![Screenshot_11](https://user-images.githubusercontent.com/115226563/210055335-7ab5a78d-8ec0-4b08-97ca-89ddc39b89f8.png)

**Labels to be added**
"Bug", Priority ("low"), Severity ("low"), Type ("UI").

**Comment by litvinets** [comment]
@ViktoriiaHrytchyna  fixed!

**Comment by ViktoriiaHrytchyna** [comment]
Fixed
