### ISSUE TITLE
Short time message displayed on Workshops when workshop was created

### ISSUE THREAD

**Issue by val-ukr** [ita-social-projects/OoS-Frontend#1951]
**Environment:** https://oos.dmytrominochkin.cloud/#/
**Reproducible: ** always 

**Preconditions**

1. Follow the link https://oos.dmytrominochkin.cloud/#/
2.  Log into OoS website as SP
3. Select "Мої гуртки" in the menu bar in the top right corner.

**Steps to reproduce**
1. Click on the “Додати гурток” button and fill in all mandatory fields in each section.
2.  Fill in all mandatory fields on the step "Про гурток"
3. Fill in all mandatory fields on the step "Опис"
4.  Fill in all mandatory fields on the step "Контакти"
5. Fill in all mandatory fields on the step "Викладачі"
6. Click on the button "Зберегти"
7. The "Гуртки" page is opened with the new workshop created; 'Дякуємо! Новий гурток успішно доданий.' message is displayed at the top of the page

**Actual result**
The message "Дякуємо! Новий гурток успішно доданий"  displayed for 2 seconds

**Expected result**
The message displayed for 10 seconds

**User story and test case links**
https://jira.softserve.academy/browse/OS-365

**Labels to be added**
"Bug", Priority:low, Severity: trivial, Type: Functional

**Comment by litvinets** [comment]
@val-ukr fixed!

**Comment by val-ukr** [comment]
@litvinets  I have the same mistake

email: pe.ivanova20@gmail.com
password Asdf!6789

**Comment by litvinets** [comment]
wrong password or email

**Comment by litvinets** [comment]
@val-ukr  wrong password or email

**Comment by val-ukr** [comment]
@litvinets  sorry, one more:
pe.ivanova2022@gmail.com 
Qwer1234@

**Comment by val-ukr** [comment]
Hi, the bag was fixed
