### ISSUE TITLE
Error message on "Реєстрація нового закладу" when invalid symbols in the field 

### ISSUE THREAD

**Issue by val-ukr** [ita-social-projects/OoS-Frontend#1952]
**Environment:** https://oos.dmytrominochkin.cloud/#
**Reproducible:** always

**Preconditions**

1. Go to [https://oos.dmytrominochkin.cloud/#](https://oos.dmytrominochkin.cloud/)
2. Click on "Увійти/Зареєструватися" button in top right corner of header
3. Click on "Зареєструватися" hyperlink
4. Click on "Надавач послуг" button
5. Fill all mandatory fields with valid data and tick all checkboxes
6. Click on "Зареєструватися" button

**Steps to reproduce**
1. Step "Інформація про заклад" is opened
2. Choose all fields and keep empty

**Actual result**
Not for all fields, add message "Це поле є обов'язковим."
![image](https://user-images.githubusercontent.com/71636259/210889452-e73f0876-34cd-4d5c-85ed-d7149d7a2a8a.png)

**Expected result**
For all empty fields, user can read message "Це поле є обов'язковим."

**User story and test case links**
[E.g.: "User story #100
[Test case]([#100 Story](https://github.com/ita-social-projects/OoS-Frontend/issues/100))"](https://jira.softserve.academy/browse/OS-604) 

**Labels to be added**
"Bug", Priority ("medium "), Severity ("minor"), Type ("Functional")

**Comment by val-ukr** [comment]
For fields: Форма власності, Категорія закладу, Тип закладу, Підпорядкування, Статус організації, ІПН, Телефон, Електронна пошта the error messages shown
For fields bellow no error message: 
![image](https://user-images.githubusercontent.com/71636259/213179293-f6352173-5fc7-493d-9115-9a8ee770cef8.png)
![image](https://user-images.githubusercontent.com/71636259/213179322-11f7faaf-712f-43be-b522-a9bb20626386.png)

**Comment by litvinets** [comment]
@val-ukr  done!

**Comment by val-ukr** [comment]
Hi! All was fixed, thanks!
