### ISSUE TITLE
Error message "Реєстрація нового закладу" when no one error messages before 

### ISSUE THREAD

**Issue by val-ukr** [ita-social-projects/OoS-Frontend#1954]
**Environment:** https://oos.dmytrominochkin.cloud/#
**Reproducible:** sometimes 

**Preconditions**

1. Go to [https://oos.dmytrominochkin.cloud/#](https://oos.dmytrominochkin.cloud/)
2. Click on "Увійти/Зареєструватися" button in top right corner of header
3. Click on "Зареєструватися" hyperlink
4. Click on "Надавач послуг" button
5. Fill all mandatory fields with valid data and tick all checkboxes
6. Click on "Зареєструватися" button

**Steps to reproduce**
1. Step "Інформація про заклад" is opened
2. Reload the page, all fields are empty
3. Add to the field "ІПН" from 1-7 symbols 
4. Click on the other field 
5. Reload the page, all fields are empty
6. Add any symbols (for example, '-+6789034в')
7. Add to the field "Телефон" 4 symbols 
8. Click on the other field 
9. Reload the page, all fields are empty
10. Add to the field "Електронна пошта": 12кіт№W

**Actual result**
The field is highlighted in red (for both) 
![image](https://user-images.githubusercontent.com/71636259/211549331-04589e32-a74e-4a2e-88e4-4aaa20766fa0.png)
![chrome_p6F7yb2tI1](https://user-images.githubusercontent.com/71636259/211549614-9b37a593-a4d1-4e27-94e2-61c7ad45c994.gif)
**And for ІПН:** fit any symbols not just numbers
![image](https://user-images.githubusercontent.com/71636259/211600092-e0dd55d8-3f3e-43f0-b947-00df2e353448.png)

**Expected result**
The error message "Це поле має містити від 8 до 10 символів." (ІПН) and validation only for numbers
The error message "Це поле має містити 9 символів." (Телефон)
The error message "Введіть коректний імейл." (Електронна пошта")

**User story and test case links**
(https://jira.softserve.academy/browse/OS-604) 

**Labels to be added**
"Bug", Priority ("medium"), Severity ("minor"), Type ("Functional")

**Comment by val-ukr** [comment]
**Bags for firlds Телефон and Електронна пошта was fixed**
(The error message "Це поле має містити 9 символів." (Телефон)
The error message "Введіть коректний імейл." (Електронна пошта"))

**Comment by litvinets** [comment]
@val-ukr thanks for reporting this bug! It was fixed, but ІПН and ЄДРПО have the same validation pattern, and the second field can consist of letters, not only numbers.

**Comment by val-ukr** [comment]
Hi, all was fixed, except (ІПН and ЄДРПО have the same validation pattern, and the second field can consist of letters, not only numbers.)
