### ISSUE TITLE
[Applying for a workshop] Incorrect error message when child tried to apply twice to the workshop.

### ISSUE THREAD

**Issue by ViktoriiaHrytchyna** [ita-social-projects/OoS-Frontend#1958]
**Environment:** Windows 10, 64-bit, Google Chrome 107.0.5304.107.
**Reproducible:** always.

**Preconditions**
1.Follow the link https://oos.dmytrominochkin.cloud/#/
2.Log into system as a Parent (e.g. 'email'="[xixofa7680@probdd.com](mailto:xixofa7680@probdd.com)", 'Password'="Qazwsx789!").
3.Parent has at least 1 child, who applied interested workshop and has "Зараховано" or "Очікує підтвердження" status.
4.Open interested workshop's page by clicking the "Детальніше" button on the workshop card.

**Steps to reproduce**
1.Click on "Подати заяву" button.
2. Choose a child from the dropdown.
3. Pay attention to the error message. 

**Actual result**
Error message is "Дитина не може бути прийнята в гурток".
![Снимок экрана 2022-12-14 121125](https://user-images.githubusercontent.com/115226563/211661724-a1b45e01-0776-4712-899c-b82c77c571d0.jpg)

**Expected result**
Error message should be "Заява вже падана".

**User story and test case links**
E.g.: "User story #610
[Test case]([#610 Story](https://jira.softserve.academy/browse/OS-610))"

**Labels to be added**
"Bug", Priority ("low "), Severity ("low"), Type ("UI").

**Comment by litvinets** [comment]
@ViktoriiaHrytchyna fixed!

**Comment by ViktoriiaHrytchyna** [comment]
Fixed
