### ISSUE TITLE
[Registration form] Incorrect placeholder in the "Дата народження керівника" field.

### ISSUE THREAD

**Issue by ViktoriiaHrytchyna** [ita-social-projects/OoS-Frontend#1959]
**Environment:** Windows 10, 64-bit, Google Chrome 107.0.5304.107.
**Reproducible:** always.

**Preconditions**
1.Go to [https://oos.dmytrominochkin.cloud/#](https://oos.dmytrominochkin.cloud/)
2.Click on "Увійти/Зареєструватися" button in top right corner of header
3.Click on "Зареєструватися" hyperlink
4.Click on "Надавач послуг" button
5.Fill all mandatory fields with valid data and tick all checkboxes
6.Click on "Зареєструватися" button

**Steps to reproduce**
1. Fill all mandatory fields in the "Інформація про заклад" tab.
2. Pay attention to the placeholder in the "Дата народження керівника" field.
3. Fill this field with non-valid data, for example : 12368.

**Actual result**
Placeholder in the "Дата народження керівника" field is "FORMS.PLACEHOLDERS.SHORT_DATE_FORMAT" and error message is "Перевірте введені дані. Використовуйте "FORMS.PLACEHOLDERS.SHORT_DATE_FORMAT"  формат. Наприклад "20/10/2010"".
![Screenshot_16](https://user-images.githubusercontent.com/115226563/211782198-88e4e630-e3bd-4ee6-b157-356c3929965c.png)
![Screenshot_19](https://user-images.githubusercontent.com/115226563/211782265-70f7b892-f861-4526-92b7-cc0db5df8143.png)

**Expected result**
Placeholder in the "Дата народження керівника" field is "ДД/ММ/РРРР" and error message should be "Перевірте введені дані. Використовуйте "ДД/ММ/РРРР" формат. Наприклад "20/10/2010"".

**User story and test case links**
"(https://jira.softserve.academy/browse/OS-570)"

**Labels to be added**
"Bug", Priority ("low"), Severity ("low"), Type ("UI").

**Comment by litvinets** [comment]
@ViktoriiaHrytchyna fixed!

**Comment by ViktoriiaHrytchyna** [comment]
Fixed
