### ISSUE TITLE
Error messages with empty fields when "Новий Гурток" created

### ISSUE THREAD

**Issue by val-ukr** [ita-social-projects/OoS-Frontend#1962]
**Environment**: https://oos.dmytrominochkin.cloud/#
**Reproducible**: always
**Preconditions**

1. Follow the link https://oos.dmytrominochkin.cloud/#/
2. Log into OoS website as SP 
3. Select «Мої гуртки» in the menu bar in the top right corner.
4. Click on the “Додати гурток” button.

**Steps to reproduce**

1. The field "Назва" is empty
2. Click on the other field

**Actual result**
When user doesn't write any symbols, the error message doesn't show
![chrome_1YuGyD3mmg](https://user-images.githubusercontent.com/71636259/211840662-c7f27f83-2728-4b3c-a92c-0dcbb3c8cd59.gif)

**Expected result**
When the fields are empty, the error message "Це поле є обов'язковим." shown.  
(For all fields)

**User story and test case links**
https://jira.softserve.academy/browse/OS-366 

**Labels to be added**
"Bug", Priority ("medium "), Severity ("minor"), Type ("Functional")

**Comment by litvinets** [comment]
@val-ukr fixed

**Comment by val-ukr** [comment]
Hi, thanks!
all is working
