### ISSUE TITLE
[Registration form] The required "Опис" and "Назва розділу" fields are not displayed on the "Реєстрація нового закладу" page.

### ISSUE THREAD

**Issue by ViktoriiaHrytchyna** [ita-social-projects/OoS-Frontend#1964]
**Environment:** Windows 10, 64-bit, Google Chrome 107.0.5304.107.
**Reproducible:** always.

**Preconditions**
1.Go to [https://oos.dmytrominochkin.cloud/#](https://oos.dmytrominochkin.cloud/)
2.Click on "Увійти/Зареєструватися" button in top right corner of header
3.Click on "Зареєструватися" hyperlink
4.Click on "Надавач послуг" button
5.Fill all mandatory fields with valid data and tick all checkboxes
6.Click on "Зареєструватися" button

**Steps to reproduce**
1. Fill all mandatory fields in the "Інформація про заклад" tab.
2. Click on "Далі" button.
3. Fill all mandatory fields in the "Контакти" tab.
4. Click on "Далі" button.
5. Pay attention to the missing "Опис" and "Назва розділу" fields.
6. Click on "+Додати ще один розділ".

**Actual result**
The required "Опис" and "Назва розділу" fields are not displayed on the "Реєстрація нового закладу" page on the "Опис" tab. These fields are displayed only after clicking "+Додати ще один розділ". 
![Screenshot_20](https://user-images.githubusercontent.com/115226563/211919528-2f28825f-b0ca-4098-8429-6b45f626a922.png)
![Screenshot_21](https://user-images.githubusercontent.com/115226563/211919671-85a95c96-c054-4b9f-a034-62dde1776830.png)

**Expected result**
The required "Опис" and "Назва розділу" fields are displayed on the "Реєстрація нового закладу" page.

**User story and test case links**
https://jira.softserve.academy/browse/OS-573

**Labels to be added**
"Bug", Priority ("medium"), Severity ("low"), Type ("UI, "Functional").

**Comment by litvinets** [comment]
@ViktoriiaHrytchyna fixed!

**Comment by ViktoriiaHrytchyna** [comment]
Fixed
