### ISSUE TITLE
[Registration form] The maximum length of the "Опис" field is not met the requirements.

### ISSUE THREAD

**Issue by ViktoriiaHrytchyna** [ita-social-projects/OoS-Frontend#1965]
**Environment:** Windows 10, 64-bit, Google Chrome 107.0.5304.107.
**Reproducible:** always.

**Preconditions**
1.Go to [https://oos.dmytrominochkin.cloud/#](https://oos.dmytrominochkin.cloud/)
2.Click on "Увійти/Зареєструватися" button in top right corner of header
3.Click on "Зареєструватися" hyperlink
4.Click on "Надавач послуг" button
5.Fill all mandatory fields with valid data and tick all checkboxes
6.Click on "Зареєструватися" button

**Steps to reproduce**
1.Fill all mandatory fields in the "Інформація про заклад" tab.
2.Click on "Далі" button.
3.Fill all mandatory fields in the "Контакти" tab.
4.Click on "Далі" button.
5.Pay attention to the placeholder of the "Опис" field.
6.Enter 505 characters in the "Опис" field.

**Actual result**
The maximum length of the "Опис" field is 500 characters.
![Screenshot_22](https://user-images.githubusercontent.com/115226563/211930340-3ea8e48a-471e-48e9-8db7-093956fcb065.png)
![Screenshot_23](https://user-images.githubusercontent.com/115226563/211930365-e9c4d5ff-99a7-478e-ae99-3f97c4cf102e.png)

**Expected result**
The maximum length of the "Опис" field should be 2000 characters.
![Screenshot_24](https://user-images.githubusercontent.com/115226563/211930692-9d333250-0dd6-49db-9c61-af89ea669ccd.png)

**User story and test case links**
https://jira.softserve.academy/browse/OS-573

**Labels to be added**
"Bug", Priority ("medium"), Severity ("low"), Type ("UI").

**Comment by litvinets** [comment]
@ViktoriiaHrytchyna  done!

**Comment by ViktoriiaHrytchyna** [comment]
Fixed
