### ISSUE TITLE
Error messages on step "Опис" when a new workshop is creating 

### ISSUE THREAD

**Issue by val-ukr** [ita-social-projects/OoS-Frontend#1970]
**Environment:** https://oos.dmytrominochkin.cloud/#
**Reproducible**: always

**Preconditions**

1. Follow the link https://oos.dmytrominochkin.cloud/#/
2. Log into OoS website as SP
3. Select «Мої гуртки» in the menu bar in the top right corner.
4. Click on the “Додати гурток” button.
5. Fill all mandatory fields on "Новий гурток" and the step "Про гурток" with valid data and click on "Далі"

**Steps to reproduce**

1.  Add to field "Назва" 2 symbols
2. Check the button "Назад"

**Actual result**

1. The error message "Це поле має містити від 1 до 256 символів." shown
<img width="497" alt="image" src="https://user-images.githubusercontent.com/71636259/212296623-27584f48-d774-4baa-9f87-38dd5ff6ad42.png">

2. The button has name "Titles. Action.Back" <img width="487" alt="image" src="https://user-images.githubusercontent.com/71636259/212302124-cbdcdab0-27f7-45ca-a1f7-40dfb1732600.png">

**Expected result**

1. The error message isn't shown after 1 symbols
2. The button has name: "Назад"

**User story and test case links**
https://jira.softserve.academy/browse/OS-367

**Labels to be added**
"Bug", Priority ("medium "), Severity ("minor"), Type ("Functional")

**Comment by litvinets** [comment]
@val-ukr  done!

**Comment by val-ukr** [comment]
Hi, all perfect, thanks
