### ISSUE TITLE
[Administration] The "Зберегти" button is not active when is created an assistant.

### ISSUE THREAD

**Issue by ViktoriiaHrytchyna** [ita-social-projects/OoS-Frontend#1972]
**Environment:** Windows 10, 64-bit, Google Chrome 107.0.5304.107.
**Reproducible:** always.

**Preconditions**
1.Go to OoS (https://oos.dmytrominochkin.cloud/).
2.SP role is created and logged in (e.g. "Email" = '[vemoce5808@chnlog.com](mailto:vemoce5808@chnlog.com)', "password" = 'Qazwsx789!').
3.Go to the "Administration" tab in the upper right corner in the drop-down list.

**Steps to reproduce**
1. Go to "Заступник директора" tab.
2. Click on "Додати" button.
3. Fill all mandatory fields with valid data on the "Особиста інформація" tab.
4. Click on "Далі" button.
5. Pay attention on the "Зберегти" button on the "Керування доступами" tab.

**Actual result**
The "Зберегти" button is not active when is created an assistant.

![Screenshot_25](https://user-images.githubusercontent.com/115226563/212569999-36140885-cc77-45f3-944c-b5a4865bb9dd.png)

**Expected result**
The "Зберегти" button is active when is created an assistant.

**Labels to be added**
"Bug", Priority ("medium"), Severity ("medium"), Type ("Functional").

**Comment by litvinets** [comment]
@ViktoriiaHrytchyna  fixed!

**Comment by ViktoriiaHrytchyna** [comment]
Fixed
