### ISSUE TITLE
[Parent's cabinet] There is no mail icon in "Заяви" tab in the Parent's cabinet.

### ISSUE THREAD

**Issue by ViktoriiaHrytchyna** [ita-social-projects/OoS-Frontend#1983]
**Environment:** Windows 10, 64-bit, Google Chrome 107.0.5304.107.
**Reproducible:** always.

**Preconditions**
1.Go to https://oos.dmytrominochkin.cloud/
2.Log in as a parent  "Email" = 'pidim28018@irebah.com', "password" = 'Qazwsx789!')
3.A Parent already applied his children to workshops.

**Steps to reproduce**
1. Go to the 'Заяви' tab of personal cabinet by clicking "Мої Заяви" button on the top right corner drop down list.
2. Pay attention to the absence of a letter icon on the right side of the string.

**Actual result**
There is no mail icon in "Заяви" tab in the Parent's cabinet.

![Снимок экрана 2023-01-20 124927](https://user-images.githubusercontent.com/115226563/213729438-0461ad58-b650-4b67-8242-15813d92f6a7.jpg)

**Expected result**
A mail icon is at the end of each line on the "Заяви" tab.

![Screenshot_26](https://user-images.githubusercontent.com/115226563/213730930-32e31e85-c021-42ef-9f10-f028a74107cb.png)

**User story and test case links**
https://jira.softserve.academy/browse/OS-525

**Labels to be added**
"Bug", Priority ("high"), Severity ("medium"), Type ("UI").

**Comment by litvinets** [comment]
@ViktoriiaHrytchyna  fixed!

**Comment by ViktoriiaHrytchyna** [comment]
Fixed
