### ISSUE TITLE
[Mobile] The "Результати пошуку" page is not adapted to the screen size.

### ISSUE THREAD

**Issue by ViktoriiaHrytchyna** [ita-social-projects/OoS-Frontend#2004]
**Environment:** Android 12, SM-M325FV Build/SP1A.210812.016, Chrome 109.0.5414.118.
**Reproducible:** always.

**Preconditions**
1.Follow the link https://oos.dmytrominochkin.cloud/#/

**Steps to reproduce**
1.Select location "Київ".
2.Tap on the "Всі" link next to "Найпопулярніші гуртки".
3.Swipe the "Результати пошуку" page to the right.
4.Pay attention that the search field and the map button go beyond the page.

**Actual result**
The "Результати пошуку" page is not adapted to the screen size.
![изображение_viber_2023-01-31_13-51-34-384](https://user-images.githubusercontent.com/115226563/216029493-f2e00af5-415d-4302-ac08-0f0df622617f.jpg)

**Expected result**
The "Результати пошуку" page is adapted to the screen size.

**Labels to be added**
"Bug", Priority ("medium"), Severity ("low"), Type ("UI").

**Comment by litvinets** [comment]
@ViktoriiaHrytchyna  fixed!
