### ISSUE TITLE
[Mobile] The service message is not displayed on the screen.

### ISSUE THREAD

**Issue by ViktoriiaHrytchyna** [ita-social-projects/OoS-Frontend#2006]
**Environment:** Android 12, SM-M325FV Build/SP1A.210812.016, Chrome 109.0.5414.118.
**Reproducible:** always.

**Preconditions**
1.Follow the link https://oos.dmytrominochkin.cloud/#/
2.The user is not registered.

**Steps to reproduce**
1.Select location "Київ".
2.An interested workshop is found.
3.Tap on the "Детальніше" button of the workshop card.
4.Tap on the "Надіслати повідомлення" button on the workshop's page.
5.Pay attention that the service message is not displayed on the screen.

**Actual result**
The service message is not displayed on the screen.
![изображение_viber_2023-02-01_21-45-15-162](https://user-images.githubusercontent.com/115226563/216149554-b1ee6c82-0e9b-4b33-a8fe-3d2aa3e2058a.jpg)

**Expected result**
After pressing the "Надіслати повідомлення" button, the service message is displayed on the screen “Для того щоб надіслати повідомлення, будь ласка, зареєструйтесь. Дякуємо”.

![Снимок экрана 2023-02-01 214433](https://user-images.githubusercontent.com/115226563/216149883-790d8f2f-c86b-460b-9836-15ca42c1e0fe.jpg)

**Labels to be added**
"Bug", Priority ("medium"), Severity ("low"), Type ("UI, "Functional").

**Comment by litvinets** [comment]
@ViktoriiaHrytchyna fixed!

**Comment by ViktoriiaHrytchyna** [comment]
Fixed
