### ISSUE TITLE
[Create Child] - replace url

### ISSUE THREAD

**Issue by litvinets** [ita-social-projects/OoS-Frontend#2015]
Replace functionality to create a child from the array one by one  to the endpoint that accepts an array of children and support the result of such request (on success - redirect back, on error - display errors)
![image](https://user-images.githubusercontent.com/27493959/216920577-bfe40b90-cf34-4dde-b81e-1a9e8fa7e29b.png)

**issue: currently we can not guarantee that all children were successfully created and navigated back. There is a bug, if you successfully create more than 2 children, it navigates back to each child, so eventually, you navigate back to the wrong page.**

**Comment by okedo** [comment]
pr meged
