### ISSUE TITLE
[Registration] Missing data when clicking on the "Правила користування" link.

### ISSUE THREAD

**Issue by ViktoriiaHrytchyna** [ita-social-projects/OoS-Frontend#2053]
**Environment:** Windows 10, 64-bit, Google Chrome 107.0.5304.107.
**Reproducible:** always.

**Preconditions**
1.Go to [https://oos.dmytrominochkin.cloud/#](https://oos.dmytrominochkin.cloud/)
2.Open the registration page by clicking the "Увійти/зареєструватися" button.

**Steps to reproduce**
1.Click on "Зареєструватися" link.
2.Fill in all the fields in the "Зареєструватися" page.
3.Click on the "Правила користування" link at the bottom of the page near the second checkbox.

**Actual result**
When clicking on the "Правила користування" link, the transition to the page with the rules of use does not occur.
![Снимок экрана 2023-04-18 140807](https://user-images.githubusercontent.com/115226563/232893974-f05f5395-16d1-46a4-96a3-8bee553fe99e.jpg)

**Expected result**
When you click on the "Правила користування" link, you will be redirected to the page with information about the rules of use.

**Labels to be added**
"Bug", Priority ("medium"), Severity ("low"), Type ("UI, "Functional").

**Comment by doliinyk** [comment]
Can't reproduce, might be fixed
