### ISSUE TITLE
[Registration] Incorrect translation of popup error message.

### ISSUE THREAD

**Issue by ViktoriiaHrytchyna** [ita-social-projects/OoS-Frontend#2055]
**Environment:** Windows 10, 64-bit, Google Chrome 107.0.5304.107.
**Reproducible:** always.

**Preconditions**
1.Go to [https://oos.dmytrominochkin.cloud/#](https://oos.dmytrominochkin.cloud/)
2.Click on "Увійти/Зареєструватися" button in top right corner of header
3.Click on "Зареєструватися" hyperlink
4.Click on "Надавач послуг" button
5.Fill all mandatory fields with valid data and tick all checkboxes
6.Click on "Зареєструватися" button

**Steps to reproduce**
1. Fill all mandatory fields on "Реєстрація нового закладу" and the step "Інформація про заклад" with valid data and click on "Далі".
2. Enter invalid data in the "Населений пункт" field (non-existent city).
3. Pay attention to the notification that appears.

**Actual result**
Incorrect translation of popup error message.
![Снимок экрана 2023-04-16 231912](https://user-images.githubusercontent.com/115226563/233046817-f52af78c-f5e4-467a-8948-08c84c1cf7e6.jpg)

**Expected result**
The pop-up notification has a clear Ukrainian translation.

**Labels to be added**
"Bug", Priority ("low"), Severity ("low"), Type ("UI").

**Comment by koliapatskal** [comment]
#2054 
Fixed

**Comment by ViktoriiaHrytchyna** [comment]
Fixed
