### ISSUE TITLE
[Registration] The size of the "Назва розділу" field does not meet the validation rules.

### ISSUE THREAD

**Issue by ViktoriiaHrytchyna** [ita-social-projects/OoS-Frontend#2057]
**Environment:** Windows 10, 64-bit, Google Chrome 107.0.5304.107.
**Reproducible:** always.

**Preconditions**
1.Go to [https://oos.dmytrominochkin.cloud/#](https://oos.dmytrominochkin.cloud/)
2.Click on "Увійти/Зареєструватися" button in top right corner of header
3.Click on "Зареєструватися" hyperlink
4.Click on "Надавач послуг" button
5.Fill all mandatory fields with valid data and tick all checkboxes
6.Click on "Зареєструватися" button

**Steps to reproduce**
1. Fill all mandatory fields on "Реєстрація нового закладу" and the step "Інформація про заклад" with valid data and click on "Далі".
2. Fill all mandatory fields on "Реєстрація нового закладу" and the step "Контакти" with valid data and click on "Далі".
3. Enter 150 characters in the "Назва розділу" field.
4. Pay attention to the absence of an error about an invalid number of characters.

**Actual result**
In the "Назва розділу" field, you can enter any number of characters that do not comply with the validation rules.
![Screenshot_2](https://user-images.githubusercontent.com/115226563/233175987-6bc1a5bd-efc0-458f-ba99-9adffb552bfd.jpg)

**Expected result**
According to the validation rules, the size of the "Назва розділу" field is: minLength=3, maxLength=100.

**Labels to be added**
"Bug", Priority ("low"), Severity ("low"), Type ("UI, "Functional").

**Comment by koliapatskal** [comment]
Fixed

**Comment by ViktoriiaHrytchyna** [comment]
Fixed
