### ISSUE TITLE
[Registration] There is no error when selecting a date of birth in the future when registering a Parent.

### ISSUE THREAD

**Issue by ViktoriiaHrytchyna** [ita-social-projects/OoS-Frontend#2065]
**Environment:** Windows 10, 64-bit, Google Chrome 107.0.5304.107.
**Reproducible:** always.

**Preconditions**
1.Go to [https://oos.dmytrominochkin.cloud/#](https://oos.dmytrominochkin.cloud/)

**Steps to reproduce**
1.Click on "Увійти/Зареєструватися" button in top right corner of header
2.Click on "Зареєструватися" hyperlink
3.Click on "Користувач" button
4.Select a date from the future period in the "Дата народження" field (for example: 13/06/2028)
5.Fill all mandatory fields with valid data and tick all checkboxes
6.Click on "Зареєструватися" button
7.Log in as Parent ("Email" = '[loweko1225@ippals.com](mailto:loweko1225@ippals.com)', "password" = 'Qazwsx789!')
8.Go to the "Особиста інформація" tab of Parent cabinet (by clicking the button in the top right corner).
9.Pay attention to the "Дата народження" field.

**Actual result**
There is no error when selecting a date of birth in the future when registering a Parent.
![Screenshot_10](https://user-images.githubusercontent.com/115226563/233951573-708dadb6-5313-4c21-b38e-4b26693534b2.jpg)
![Screenshot_4](https://user-images.githubusercontent.com/115226563/233951743-ec352dcb-8872-407a-bc40-b84f6e1af159.jpg)

**Expected result**
An error occurs when clicking the "Зареєструватися" button if the "Date of birth" field is filled with a date from the future period.

**Labels to be added**
"Bug", Priority ("low"), Severity ("low"), Type ("UI, "Functional"), "API" (for back-end bugs).

**Comment by koliapatskal** [comment]
Fixed
