### ISSUE TITLE
[Search] A dot is displayed next to the magnifying glass icon in the "Пошук за напрямком" field.

### ISSUE THREAD

**Issue by ViktoriiaHrytchyna** [ita-social-projects/OoS-Frontend#2067]
**Environment:**Windows 10, 64-bit, Google Chrome 107.0.5304.107.
**Reproducible:** always.

**Preconditions**
1.Go to [https://oos.dmytrominochkin.cloud/#](https://oos.dmytrominochkin.cloud/)

**Steps to reproduce**
1. Go to the "Переглянути всі" link near the "Найпопулярніші гуртки".
2. Pay attention to the "Пошук за напрямком" field on the left side.

**Actual result**
A dot is displayed next to the magnifying glass icon in the "Пошук за напрямком" field.
![Screenshot_8](https://user-images.githubusercontent.com/115226563/234386612-c2eff9c0-94e5-4cff-abd0-2fff4ef2e637.jpg)

**Expected result**
The magnifying glass icon in the "Пошук за напрямком" field is displayed without a dot.

**Labels to be added**
"Bug", Priority ("low"), Severity ("low"), Type ("UI").

**Comment by koliapatskal** [comment]
Fixed

**Comment by ViktoriiaHrytchyna** [comment]
Fixed
