### ISSUE TITLE
[Search] Different distance between checkboxes on the "Результати пошуку" page.

### ISSUE THREAD

**Issue by ViktoriiaHrytchyna** [ita-social-projects/OoS-Frontend#2068]
**Environment:** Windows 10, 64-bit, Google Chrome 107.0.5304.107.
**Reproducible:** always.

**Preconditions**
1.Go to [https://oos.dmytrominochkin.cloud/#](https://oos.dmytrominochkin.cloud/)

**Steps to reproduce**
1.Go to the "Переглянути всі" link near the "Найпопулярніші гуртки".
2.Pay attention to the filters "Напрямки" and "Вартість".

**Actual result**
Different distance between checkboxes on the "Результати пошуку" page.
![Screenshot_9](https://user-images.githubusercontent.com/115226563/234513239-afeb75c1-48b7-4bfc-b885-47c84ae86ac8.jpg)

**Expected result**
The distance between the checkboxes on the "Результати пошуку" page is the same.

**Labels to be added**
"Bug", Priority ("low"), Severity ("low"), Type ("UI").

**Comment by koliapatskal** [comment]
Fixed
