### ISSUE TITLE
[Personal cabinet] Error in the notification of successful editing on the "Інформація про заклад" page.

### ISSUE THREAD

**Issue by ViktoriiaHrytchyna** [ita-social-projects/OoS-Frontend#2069]
**Environment:** Windows 10, 64-bit, Google Chrome 107.0.5304.107.
**Reproducible:** always.

**Preconditions**
1.Go to [https://oos.dmytrominochkin.cloud/#](https://oos.dmytrominochkin.cloud/)
2.Log in as SP ("Email" = '[wadove3571@gam1fy.com](mailto:wadove3571@gam1fy.com)', "password" = 'Qazwsx789!')

**Steps to reproduce**
1.Go to the "Інформація про заклад" tab of SP cabinet (by clicking the button in the top right corner).
2.Click the "Редагувати" button.
3.Change any field to valid data on the "Редагування закладу" page and click the "Зберегти" button.
4.Pay attention to the notification about successful editing.

**Actual result**
Notification text: "Заклад успішно відредагована"
![Снимок экрана 2023-04-24 221153](https://user-images.githubusercontent.com/115226563/234518105-0dad526f-859c-493d-851f-e3c08e91cf07.jpg)

**Expected result**
Notification text: "Заклад успішно відредаговано"

**Labels to be added**
"Bug", Priority ("low"), Severity ("low"), Type ("UI").

**Comment by koliapatskal** [comment]
Fixed

**Comment by ViktoriiaHrytchyna** [comment]
Fixed
