### ISSUE TITLE
[Workshop] There is a heart icon for SP on the workshop cards.

### ISSUE THREAD

**Issue by ViktoriiaHrytchyna** [ita-social-projects/OoS-Frontend#2073]
**Environment:** Windows 10, 64-bit, Google Chrome 107.0.5304.107.
**Reproducible:** always.

**Preconditions**
1.Go to [https://oos.dmytrominochkin.cloud/#](https://oos.dmytrominochkin.cloud/)
2.Log in as SP ("Email" = '[wadove3571@gam1fy.com](mailto:wadove3571@gam1fy.com)', "password" = 'Qazwsx789!')

**Steps to reproduce**
1. Go to the main page with workshop cards.
2. Click on the 'heart icon' on the workshop card.

**Actual result**
There is a heart icon for SP on the workshop cards.

![Снимок экрана 2023-04-28 123254](https://user-images.githubusercontent.com/115226563/235111977-d184f744-51cc-451c-9af9-3e6dafcf6681.jpg)

**Expected result**
For SP, there is no heart icon on the workshop cards.

**Labels to be added**
"Bug", Priority ("low"), Severity ("low"), Type ("UI").

**Comment by koliapatskal** [comment]
Fixed

**Comment by ViktoriiaHrytchyna** [comment]
Fixed
