### ISSUE TITLE
[Personal cabinet] The "Форма власності" field of the "Інформація про заклад" tab can be edited.

### ISSUE THREAD

**Issue by ViktoriiaHrytchyna** [ita-social-projects/OoS-Frontend#2074]
**Environment:** Windows 10, 64-bit, Google Chrome 107.0.5304.107.
**Reproducible:** always.

**Preconditions**
1.Go to [https://oos.dmytrominochkin.cloud/#](https://oos.dmytrominochkin.cloud/)
2.Log in as SP ("Email" = '[wadove3571@gam1fy.com](mailto:wadove3571@gam1fy.com)', "password" = 'Qazwsx789!')

**Steps to reproduce**
1.Go to the "Інформація про заклад" tab of SP cabinet (by clicking the button in the top right corner).
2.Click the "Редагувати" button.
3.Pay attention to the "Форма власності" field.

**Actual result**
When editing the "Інформація про заклад" tab, the "Форма власності" field can be selected from the drop-down list of options for editing.
![Screenshot_21](https://user-images.githubusercontent.com/115226563/235115242-6eca2c7b-2655-4f4c-8e30-900dee444ca0.jpg)

**Expected result**
The "Форма власності" field of the "Інформація про заклад" tab is not editable.

**Labels to be added**
"Bug", Priority ("low"), Severity ("low"), Type ("UI").

**Comment by koliapatskal** [comment]
Fixed

**Comment by ViktoriiaHrytchyna** [comment]
Fixed
