### ISSUE TITLE
[Search] The spacing between buttons on the search page does not match the design.

### ISSUE THREAD

**Issue by ViktoriiaHrytchyna** [ita-social-projects/OoS-Frontend#2076]
**Environment:** Windows 10, 64-bit, Google Chrome 107.0.5304.107.
**Reproducible:** always.

**Preconditions**
1.Go to [https://oos.dmytrominochkin.cloud/#](https://oos.dmytrominochkin.cloud/)

**Steps to reproduce**
1. Click on the “Magnifying glass/Search” button of Search box on the Main page.
2. Pay attention to the "За рейтингом" and "Список/Карта" buttons in the right corner of the page.

**Actual result**
The spacing between buttons on the search page does not match the design.
![Screenshot_23](https://user-images.githubusercontent.com/115226563/235775218-2f6d39fe-9dbf-4636-9c38-4b69c2d05cb4.jpg)

**Expected result**
Between the "За рейтингом" and "Список/Карта" buttons in the right corner of the page, there should be a distance according to the design.
![Screenshot_24](https://user-images.githubusercontent.com/115226563/235776298-261be66f-a060-4ef2-ba18-6b3587bd2396.jpg)

**Labels to be added**
"Bug", Priority ("low"), Severity ("low"), Type ("UI").

**Comment by koliapatskal** [comment]
Fixed
