### ISSUE TITLE
[Techadmin] The institution's status "Заклад заблокований" does not meet the requirements.

### ISSUE THREAD

**Issue by ViktoriiaHrytchyna** [ita-social-projects/OoS-Frontend#2081]
**Environment:** Windows 10, 64-bit, Google Chrome 107.0.5304.107.
**Reproducible:** always.

**Preconditions**
1.Go to [https://oos.dmytrominochkin.cloud/#](https://oos.dmytrominochkin.cloud/)
2.Log in as Technical administrator ("Email" = '[admin@gmail.com](mailto:admin@gmail.com)', "password" = 'A12345a@')

**Steps to reproduce**
1.Go to "Адміністрування" on the top right corner drop down list.
2.Click on "Заклади" tab.
3.Pay attention to the status of the institution "IT Академія майбутнього", email "wadove3571@gam1fy.com".
4.Click the three dots next to the status.
5.Select "Заблокувати заклад" from the drop-down menu.
6.On the "Заблокувати надавача послуг?" page, enter the reason and click the "Підтвердити" button.
7.Pay attention to the successful blocking and the status of the institution.

**Actual result**
The institution's status is written in black and there is no icon in front of the status. The institution can be blocked again.
![Снимок экрана 2023-05-03 232958](https://user-images.githubusercontent.com/115226563/236186866-db0ab7f9-8c02-4d56-9e87-2ebeed668efc.jpg)

**Expected result**
If the institution already has the status "заклад заблокований", then the institution cannot be blocked again. The name of the status is written in red with an icon in front of the name.
![Screenshot_27](https://user-images.githubusercontent.com/115226563/236188101-cfae92c1-e66b-4f5a-9765-7daf004104ca.jpg)

**Labels to be added**
"Bug", Priority ("medium"), Severity ("medium"), Type ("UI, "Functional").

**Comment by koliapatskal** [comment]
Fixed

**Comment by ViktoriiaHrytchyna** [comment]
Fixed
