### ISSUE TITLE
[Personal cabinet] The message about blocking the institution does not meet the requirements.

### ISSUE THREAD

**Issue by ViktoriiaHrytchyna** [ita-social-projects/OoS-Frontend#2085]
**Environment:** Windows 10, 64-bit, Google Chrome 107.0.5304.107.
**Reproducible:** always.

**Preconditions**
1.Go to [https://oos.dmytrominochkin.cloud/#](https://oos.dmytrominochkin.cloud/)
2.The institution is blocked by Tech admin.
3.Log in as SP Log in as the SP of the blocked institution.

**Steps to reproduce**
1. 1.Go to the "Інформація про заклад" tab of SP cabinet (by clicking the button in the top right corner).
2. Pay attention to the message about blocking the institution.

**Actual result**
The color and text of the message do not meet the requirements.
![Screenshot_30](https://user-images.githubusercontent.com/115226563/236447489-2caa2826-576e-4097-8600-0e0dc68f0445.jpg)

**Expected result**
The blocking message should be red, the name of the status "Заклад заблокований" and the reason for the blocking should be written below.
![Screenshot_35](https://user-images.githubusercontent.com/115226563/236451184-9fdfbb7f-76fe-4444-bab6-deefbae509b0.jpg)

**Labels to be added**
"Bug", Priority ("medium"), Severity ("low"), Type ("UI, "Functional").

**Comment by koliapatskal** [comment]
Fixed

Styles have also been added for institutions with status "Needing Re-Confirmation"

**Comment by ViktoriiaHrytchyna** [comment]
Fixed
