### ISSUE TITLE
[Search] The location selection and search field is shifted to the left on the search page.

### ISSUE THREAD

**Issue by ViktoriiaHrytchyna** [ita-social-projects/OoS-Frontend#2087]
**Environment:** Windows 10, 64-bit, Google Chrome 107.0.5304.107.
**Reproducible:** always.

**Preconditions**
1.Go to [https://oos.dmytrominochkin.cloud/#](https://oos.dmytrominochkin.cloud/)

**Steps to reproduce**
1.Click on the “Magnifying glass/Search” button of Search box on the Main page.
2.Pay attention to the "За рейтингом" and "Список/Карта" buttons in the right corner of the page.

**Actual result**
The location selection and search field is shifted to the left.
![Screenshot_33](https://github.com/ita-social-projects/OoS-Frontend/assets/115226563/29ef04db-34e4-43bf-b406-8392e939dd3d)

**Expected result**
The location selection and search field is placed on the same level as the workshops.
![Screenshot_43](https://github.com/ita-social-projects/OoS-Frontend/assets/115226563/7a5ed2db-9814-4d34-bd83-4b5216a7c7af)

**Labels to be added**
"Bug", Priority ("low"), Severity ("low"), Type ("UI").

**Comment by koliapatskal** [comment]
Fixed
