### ISSUE TITLE
[Workshop] There is no "призупинити набір" button for the workshops of the service provider "комунальної" of the ownership form.

### ISSUE THREAD

**Issue by ViktoriiaHrytchyna** [ita-social-projects/OoS-Frontend#2088]
**Environment:** Windows 10, 64-bit, Google Chrome 107.0.5304.107.
**Reproducible:** always.

**Preconditions**
1.Registered Service Provider with the ownership form "комунальна".
2.The service provider has registered one or more workshops.

**Steps to reproduce**
1.Log in as a SP.
2.Go to the "Мої гуртки" tab of SP cabinet (by clicking the button in the top right corner).
3.Pay attention to the workshop page.

**Actual result**
There is no "призупинити набір" button on the workshop page near the "набір триває" status.
![Screenshot_40](https://github.com/ita-social-projects/OoS-Frontend/assets/115226563/92a7c356-1302-4749-8325-94925b16c41a)

**Expected result**
The "призупинити набір" button is placed on the workshop page next to the status "набір триває" for service providers of the communal form of ownership.
![Screenshot_42](https://github.com/ita-social-projects/OoS-Frontend/assets/115226563/bc707630-795d-4a1b-9d8f-213347dda50f)

**Labels to be added**
"Bug", Priority ("medium"), Severity ("medium"), Type ("UI, "Functional").

**Comment by koliapatskal** [comment]
Fixed.

The availability of a function depends on two conditions:
* The presence of a limit on the number of seats (if there is no limit, the function is absent)
* SP ownership. There was a problem with this, as some workshops kept the ownership state, despite the fact that the ownership was changed to communal. We fixed it. Now it should work as expected

**Comment by ViktoriiaHrytchyna** [comment]
Fixed
