### ISSUE TITLE
[Workshop] A 404 error is occurred when editing a workshop.

### ISSUE THREAD

**Issue by ViktoriiaHrytchyna** [ita-social-projects/OoS-Frontend#2090]
**Environment:** Windows 10, 64-bit, Google Chrome 107.0.5304.107.
**Reproducible:** always.

**Preconditions**
1.Registered Service Provider.
2.The service provider has registered one or more workshops.

**Steps to reproduce**
1.Log in as a SP.
2.Go to the "Мої гуртки" tab of SP cabinet (by clicking the button in the top right corner).
3.Click the "Редагувати" button on the workshop's card.
4.Change some information on the "Про гурток" tab and click the "Далі" button.
5.Go to the last tab "Викладачі" and press the button "Зберегти".
6.Pay attention to the error message.

**Actual result**
An error is occurred when editing a workshop.
![Снимок экрана 2023-05-12 135203](https://github.com/ita-social-projects/OoS-Frontend/assets/115226563/cc9940c4-65de-4897-8cb4-a6d9bbaf9049)
![Снимок экрана 2023-05-12 135302](https://github.com/ita-social-projects/OoS-Frontend/assets/115226563/faee1635-2b6b-4caa-8f8a-59d4c7848197)

**Expected result**
When editing the workshop, the error does not appear and the changed information is saved successfully.

**Labels to be added**
"Bug", Priority ("high"), Severity ("medium"), Type ("Functional"), "API" (for back-end bugs).

**Comment by koliapatskal** [comment]
Fixed

**Comment by ViktoriiaHrytchyna** [comment]
Fixed
