### ISSUE TITLE
[Workshop] The name of the city is missing in the address on the workshop card.

### ISSUE THREAD

**Issue by ViktoriiaHrytchyna** [ita-social-projects/OoS-Frontend#2099]
**Environment:** Windows 10, 64-bit, Google Chrome 107.0.5304.107.
**Reproducible:** always.

**Preconditions**
1.Registered Service Provider (email: [jigoc25090@klblogs.com](mailto:jigoc25090@klblogs.com), password: Qazwsx789!).
2.The SP has one or more workshops registered in any city except "Kиїв".

**Steps to reproduce**
1.Click on the “Magnifying glass/Search” button of Search box on the Main page.
2.Enter the location of the workshop (for example, "Миколаїв")
3.Enter the name of the workshop (for example, "Ластівка")
4.Pay attention to the workshop card.

**Actual result**
If the workshop is registered in any city other than Kyiv, then the name of the city is not displayed on the "Результати пошуку" page in the address of the workshop card.
![Screenshot_56](https://github.com/ita-social-projects/OoS-Frontend/assets/115226563/3d631825-770d-41ae-8458-a1f66c0bbf71)
![Screenshot_52](https://github.com/ita-social-projects/OoS-Frontend/assets/115226563/8ee35e7f-67e1-435d-bfd6-588f0651d9d9)

**Expected result**
In the workshop card, the address begins with the name of the city in which this workshop is registered.

**Labels to be added**
"Bug", Priority ("low"), Severity ("low"), Type ("UI").

**Comment by koliapatskal** [comment]
Fixed

**Comment by ViktoriiaHrytchyna** [comment]
Fixed
