### ISSUE TITLE
[Personal cabinet] There are no designations of territorial units in the personal cabinet in the "Населений пункт" field.

### ISSUE THREAD

**Issue by ViktoriiaHrytchyna** [ita-social-projects/OoS-Frontend#2102]
**Environment:** Windows 10, 64-bit, Google Chrome 107.0.5304.107.
**Reproducible:** always.

**Preconditions**
1.Go to [https://oos.dmytrominochkin.cloud/#](https://oos.dmytrominochkin.cloud/)
2.Registered Service Provider (email: [cepanaf253@duscore.com](mailto:cepanaf253@duscore.com), password: Qazwsx789!).

**Steps to reproduce**
1. Go to the "Інформація про заклад" tab of SP cabinet (by clicking the button in the top right corner).
2. Click on "Контакти" tab.
3. Pay attention to the "Населений пункт" field.

**Actual result**
There are no designations of territorial units, such as "область", "район", "отг" in the personal account in the "Населений пункт" field.
![Screenshot_58](https://github.com/ita-social-projects/OoS-Frontend/assets/115226563/e20f128e-732a-4fe7-98ab-c7b7d3b51f0d)
<img width="855" alt="image" src="https://github.com/ita-social-projects/OoS-Frontend/assets/115226563/098ec9ed-4eb8-4283-b05a-2fc09bfdcc9e">

**Expected result**
In the "Населений пункт" field, if there are different territorial units in the address, such as "область", "район", "отг", their designations should be displayed.

**Labels to be added**
"Bug", Priority ("low"), Severity ("low"), Type ("UI").

**Comment by koliapatskal** [comment]
Fixed

**Comment by ViktoriiaHrytchyna** [comment]
Fixed
