### ISSUE TITLE
[Notification] SP can`t see notifications when Parent applies to a workshop for himself.

### ISSUE THREAD

**Issue by ViktoriiaHrytchyna** [ita-social-projects/OoS-Frontend#2103]
**Environment:** Windows 10, 64-bit, Google Chrome 107.0.5304.107.
**Reproducible:** always.

**Preconditions**
1.Go to [https://oos.dmytrominochkin.cloud/#](https://oos.dmytrominochkin.cloud/)
2.Log in as a Parent.
3.Parent hasn`t applied to the workshop yet.
4.The Parent submitted an application to join the selected workshop (for example, "Ластівка")

**Steps to reproduce**
1.Log in as a SP.
2.Pay attention to the absence of a notification on the main page in the site header.
3.Go to the "Заявки" tab of SP cabinet (by clicking the button in the top right corner).

**Actual result**
SP can`t see notifications when Parent applies to a workshop for himself on the main page in the site header.
![Screenshot_60](https://github.com/ita-social-projects/OoS-Frontend/assets/115226563/fe7087bf-d411-45e6-9ed9-da5e810dca23)
![Screenshot_59](https://github.com/ita-social-projects/OoS-Frontend/assets/115226563/5f160267-6dcb-4202-aed7-6d1496af32b5)

**Expected result**
When Parent applies to a workshop for himself on the main page in the top right corner SP sees a bell with an orange circle next to it and the number of unread notifications in this circle.

**Labels to be added**
"Bug", Priority ("medium"), Severity ("low"), Type ("UI, "Functional").

**Comment by koliapatskal** [comment]
Fixed

**Comment by ViktoriiaHrytchyna** [comment]
Fixed
