### ISSUE TITLE
[Assistant, Admin] There is no "Це поле є обов'язковим." error when creating a workshop admin and assistant.

### ISSUE THREAD

**Issue by ViktoriiaHrytchyna** [ita-social-projects/OoS-Frontend#2107]
**Environment:** Windows 10, 64-bit, Google Chrome 107.0.5304.107.
**Reproducible:** always.

**Preconditions**
1.Go to https://oos.dmytrominochkin.cloud/#/
2.Log in as SP Email "[jigoc25090@klblogs.com](mailto:jigoc25090@klblogs.com)", Password "Qazwsx789!".
3.At least 1 workshop should exist in the SP Cabinet.

**Steps to reproduce**
1.Go to "Адміністрування" page by clicking in the top right corner drop-down list.
2.Click on "Додати" drop-down list.
3.Click on "Адміністратора гуртка" or "Заступника директора"
4.Fill in the "Телефон" and "Електронна пошта" fields.
5.Pay attention to the active "Далі" button.

**Actual result**
No error "Це поле є обов'язковим." when the "Прізвище" and "Ім'я" fields are empty when creating an administrator and a workshop assistant. The "Далі" button is active and when the button is pressed, the "Керування доступами" tab opens.
![Снимок экрана 2023-05-30 130925](https://github.com/ita-social-projects/OoS-Frontend/assets/115226563/81761ce2-4612-42ea-8e65-3519583e99b1)

**Expected result**
Error "Це поле є обов'язковим." when the "Прізвище" and "Ім'я" fields are empty when creating an administrator and a workshop assistant. The "Далі" button is disabled.

**Labels to be added**
"Bug", Priority ("high"), Severity ("high"), Type ("UI, "Functional").

**Comment by koliapatskal** [comment]
Fixed

**Comment by ViktoriiaHrytchyna** [comment]
Fixed
