### ISSUE TITLE
[Registration] There is no validation check of the "Контакти" tab when registering an institution.

### ISSUE THREAD

**Issue by ViktoriiaHrytchyna** [ita-social-projects/OoS-Frontend#2111]
**Environment:** Windows 10, 64-bit, Google Chrome 107.0.5304.107.
**Reproducible:** always.

**Preconditions**
1.Go to https://oos.dmytrominochkin.cloud/#/
2.Register a new service provider.
3."РЕЄСТРАЦІЯ НОВОГО ЗАКЛАДУ" page is opened.

**Steps to reproduce**
1. Fill in valid data in the mandatory field on the first page of the institution's registration.
2. Click on "Далі" button.
3. Fill all mandatory fields with invalid data in the 'Юридична адреса' section.
4. Leave empty checkbox 'Співпадає з юридичною адресою'.
5. Fill all mandatory fields with invalid data in the 'Фактична адреса' section.
6. Click on "Далі" button.

**Actual result**
There is no validation check of the "Вулиця" and "Будинок" fields of the "Контакти" tab when registering an institution.
![Screenshot_65](https://github.com/ita-social-projects/OoS-Frontend/assets/115226563/a937b4cb-a690-4f40-a529-7ec5a800c7b1)

**Expected result**
If you fill in the fields "Вулиця" and "Будинок" of the "Контакти" tab with incorrect data, a validation check is performed when you click the "Далі" button.

**Labels to be added**
"Bug", Priority ("medium"), Severity ("medium"), Type ("UI, "Functional"), "API" (for back-end bugs).

**Comment by koliapatskal** [comment]
Fixed

**Comment by koliapatskal** [comment]
@ViktoriiaHrytchyna, I changed the wrong maximum number of characters in the hint

**Comment by ViktoriiaHrytchyna** [comment]
Fixed
