### ISSUE TITLE
[Registration] Redirect to the main page when registering a new institution.

### ISSUE THREAD

**Issue by ViktoriiaHrytchyna** [ita-social-projects/OoS-Frontend#2112]
**Environment:** Windows 10, 64-bit, Google Chrome 107.0.5304.107.
**Reproducible:** always.

**Preconditions**
1.Go to https://oos.dmytrominochkin.cloud/#/
2.Register a new service provider.
3."РЕЄСТРАЦІЯ НОВОГО ЗАКЛАДУ" page is opened.

**Steps to reproduce**
1. Fill in valid data in the mandatory field on the all page of the institution's registration.
2. Click on "Зберегти" button.

**Actual result**
Upon successful registration of a new institution, the service provider is redirected to the main page of the site and sees the service notification "Заклад успішно створено".
![Снимок экрана 2023-06-02 123809](https://github.com/ita-social-projects/OoS-Frontend/assets/115226563/2bd42081-9e6b-47e1-80e2-84b48c853e3b)

**Expected result**
Upon successful registration of a new institution, the service provider is redirected to the "Інформація про заклад" page in the personal cabinet and sees the service notification "Заклад успішно створено" and the status of the institution "Очікує підтвердження".
![Screenshot_66](https://github.com/ita-social-projects/OoS-Frontend/assets/115226563/b59987e1-e764-408f-89b6-59f9d5f07d34)

**Labels to be added**
"Bug", Priority ("low"), Severity ("low"), Type ("Functional"), "API" (for back-end bugs).

**Comment by koliapatskal** [comment]
Fixed

**Comment by ViktoriiaHrytchyna** [comment]
Fixed

**Comment by ViktoriiaHrytchyna** [comment]
Fixed
