### ISSUE TITLE
[Personal cabinet] The service provider cannot send the message.

### ISSUE THREAD

**Issue by ViktoriiaHrytchyna** [ita-social-projects/OoS-Frontend#2113]
**Environment:** Windows 10, 64-bit, Google Chrome 107.0.5304.107.
**Reproducible:** always.

**Preconditions**
1.Go to https://oos.dmytrominochkin.cloud/#/
2.Log in as service provider.
3.SP has statements in his personal cabinet.

**Steps to reproduce**
1.Go to the "Заявки" tab of personal cabinet (by clicking the button in the top right corner).
2.Pay attention to the missing letter icons on the "Заявки" page.

**Actual result**
In the service provider's cabinet on the "Заявки" page, there is no possibility to send messages to contact users who have submitted applications for workshops.
![Снимок экрана 2023-06-06 132734](https://github.com/ita-social-projects/OoS-Frontend/assets/115226563/e2771866-7eef-4238-bb54-5aea2115ccce)

**Expected result**
In the service provider's cabinet  on the "Заявки" page, at the end of each submitted application, there is a letter icon for sending messages to users who have submitted applications for workshops.
![Снимок экрана 2023-06-07 121352](https://github.com/ita-social-projects/OoS-Frontend/assets/115226563/8c3da313-2403-4169-8ed5-20681ae96627)

**Labels to be added**
"Bug", Priority ("medium"), Severity ("medium"), Type ("UI, "Functional").

**Comment by doliinyk** [comment]
Fixed in #2198, #2223 and https://github.com/ita-social-projects/OoS-Backend/pull/1244

**Comment by ViktoriiaHrytchyna** [comment]
Fixed
