### ISSUE TITLE
[Personal cabinet] There is no reason for refusal of applications with status "Відмовлено".

### ISSUE THREAD

**Issue by ViktoriiaHrytchyna** [ita-social-projects/OoS-Frontend#2114]
**Environment:** Windows 10, 64-bit, Google Chrome 107.0.5304.107.
**Reproducible:** always.

**Preconditions**
1.Go to https://oos.dmytrominochkin.cloud/#/
2.Log in as service provider.
3.SP has statements in his personal cabinet with "Відмовлено" status.

**Steps to reproduce**
1.Go to the "Заявки" tab of personal cabinet (by clicking the button in the top right corner).
2. Pay attention to the application with the "Відмовлено" status.

**Actual result**
Applications with the "Відмовлено" status do not have a reason for refusal under the status.
And the application status is not placed in the center of the row.
![Screenshot_68](https://github.com/ita-social-projects/OoS-Frontend/assets/115226563/f1415ded-81a9-4afe-80f0-4cba63f021be)
![Screenshot_69](https://github.com/ita-social-projects/OoS-Frontend/assets/115226563/3f25421e-573f-420f-9e8b-997e798ba90b)

**Expected result**
The reason for the refusal is written under each "Відмовлено" status. The status of applications is placed in the center of the row according to the design.
![Снимок экрана 2023-06-07 12135](https://github.com/ita-social-projects/OoS-Frontend/assets/115226563/86562ed9-ebbc-4c05-ae2b-6d5d0b965834)

**Labels to be added**
"Bug", Priority ("low"), Severity ("low"), Type ("UI").

**Comment by koliapatskal** [comment]
Fixed the first part of the bug related to status alignment. The second part, after discussion with BA, decided to leave it as is.

**Comment by ViktoriiaHrytchyna** [comment]
Fixed
