### ISSUE TITLE
[Notification] There are no notifications about received messages in the header of the site.

### ISSUE THREAD

**Issue by ViktoriiaHrytchyna** [ita-social-projects/OoS-Frontend#2121]
**Environment:** Windows 10, 64-bit, Google Chrome 107.0.5304.107.
**Reproducible:** always.

**Preconditions**
1.Go to https://oos.dmytrominochkin.cloud/#/
2.Log in as Parent.
3.The father sent a message to the workshop (for example, "WWW" )

**Steps to reproduce**
1. Log in as the service provider of the workshop where the message was sent (sorira6718@ozatvn.com, pass: Qazwsx789!).
2. Pay attention to the bell in the header of the site.

**Actual result**
There are no notifications about received messages on the main page.
![Screenshot_87](https://github.com/ita-social-projects/OoS-Frontend/assets/115226563/df2b79f4-009d-4431-a9d5-62a793875795)
![Screenshot_88](https://github.com/ita-social-projects/OoS-Frontend/assets/115226563/d008411d-02b0-4177-9604-44040c78e70f)

**Expected result**
When messages are received, an orange circle with a number inside appears in the header of the site near the bell, indicating the number of received messages.

**Labels to be added**
"Bug", Priority ("medium"), Severity ("low"), Type ("UI, "Functional").

**Comment by doliinyk** [comment]
Might be duplicated in https://github.com/ita-social-projects/OoS-Frontend/issues/2294, will come with #2317
