### ISSUE TITLE
[Workshop] There is no information on the number of messages on the workshop card.

### ISSUE THREAD

**Issue by ViktoriiaHrytchyna** [ita-social-projects/OoS-Frontend#2122]
**Environment:** Windows 10, 64-bit, Google Chrome 107.0.5304.107.
**Reproducible:** always.

**Preconditions**
1.Go to https://oos.dmytrominochkin.cloud/#/
2.Log in as service provider.
3.SP has one or more workshops.

**Steps to reproduce**
1. Go to the "Мої гуртки" tab of personal cabinet (by clicking the button in the top right corner).
2. Pay attention to the workshop card.

**Actual result**
There is no information on the number of messages on the workshop card.
![Screenshot_91](https://github.com/ita-social-projects/OoS-Frontend/assets/115226563/39fd6439-2dd3-4ad6-a132-19b8ede5fd8a)

**Expected result**
Information about the number of messages received is displayed on the workshop card.
![Screenshot_92](https://github.com/ita-social-projects/OoS-Frontend/assets/115226563/69b5f970-05b5-416e-9364-125da5b68647)

**Labels to be added**
"Bug", Priority ("low"), Severity ("low"), Type ("UI").

**Comment by DKymachynskyi** [comment]
Fixed on [Backend](https://github.com/ita-social-projects/OoS-Backend/pull/1212)

**Comment by ViktoriiaHrytchyna** [comment]
Fixed
