### ISSUE TITLE
[Workshop] The "Вид спорту", "Назва виду спорта" fields are cleared when editing a workshop.

### ISSUE THREAD

**Issue by ViktoriiaHrytchyna** [ita-social-projects/OoS-Frontend#2126]
**Environment:** Windows 10, 64-bit, Google Chrome 107.0.5304.107..
**Reproducible:** sometimes.

**Preconditions**
1.Go to https://oos.dmytrominochkin.cloud/#/
2.Log in as service provider.
3.SP has one or more workshops subordinate to "Мінспорт".

**Steps to reproduce**
1.Go to the "Мої гуртки" tab of personal cabinet (by clicking the button in the top right corner).
2.Click on "Редагувати" button on the workshop card.
3.Click on "Далі" button.
4.Pay attention to the fields "Вид спорту", "Назва виду спорта".

**Actual result**
Sometimes when editing a workshop on the "Description" tab, the "Вид спорту" and "Назва виду спорта" fields are cleared.
![Screenshot_98](https://github.com/ita-social-projects/OoS-Frontend/assets/115226563/138dfba6-51aa-4e0c-a859-524012a18477)
![Screenshot_101](https://github.com/ita-social-projects/OoS-Frontend/assets/115226563/e64ffd9b-3e42-4164-b2cd-b24f2aa3d664)
![Screenshot_102](https://github.com/ita-social-projects/OoS-Frontend/assets/115226563/c7ed3fd3-a788-46e7-9d9a-5a3c931e8954)

**Expected result**
When opening the "Редагування гуртка" page, all previously filled information is displayed on all tabs.

**Labels to be added**
"Bug", Priority ("pri: medium"), Severity ("severity: medium"), Type ("UI, "Functional").

**Comment by koliapatskal** [comment]
Fixed

**Comment by ViktoriiaHrytchyna** [comment]
Fixed
