### ISSUE TITLE
[Personal cabinet] Previously entered information on the edit page is not pulled.

### ISSUE THREAD

**Issue by ViktoriiaHrytchyna** [ita-social-projects/OoS-Frontend#2134]
**Environment:** Windows 10, 64-bit, Google Chrome 107.0.5304.107.
**Reproducible:** always.

**Preconditions**
1.Go to https://oos.dmytrominochkin.cloud/#/
2.Log in as service provider (email: [jigoc25090@klblogs.com](mailto:jigoc25090@klblogs.com), pass: Qazwsx789!).

**Steps to reproduce**
1.Go to the "Адміністрування" tab of personal cabinet (by clicking the button in the top right corner).
2.Click on the three dots at the end of any table row.
3.Choose "Редагувати користувача" from the drop-down menu.
4.Pay attention to the page that appears.

**Actual result**
The fields of the editing page are empty, the previously entered information about the assistant or workshop administrator is not pulled.
![Screenshot_113](https://github.com/ita-social-projects/OoS-Frontend/assets/115226563/e17e62ba-e194-442e-b9ae-41055304cf3b)

**Expected result**
The fields of the editing page contain previously entered information about the assistant or workshop administrator.

**Labels to be added**
"Bug", Priority ("pri:medium "), Severity ("severity:low"), Type ("UI, "Functional").

**Comment by koliaBp** [comment]
Fixed

**Comment by ViktoriiaHrytchyna** [comment]
Fixed
