### ISSUE TITLE
[SP Edit page]User can't save personal information after making changes in the mandatory fields

### ISSUE THREAD

**Issue by Shveik861** [ita-social-projects/OoS-Frontend#2139]
**Environment:** Windows 10 Pro, Chrome Version 113.0.5672.129 (64 bit).
**Reproducible:** always.

**Preconditions**
The Service Provider has been already registered in the system
Log into OoS website as SP
Go to the 'ОСОБИСТА ІНФОРМАЦІЯ' tab of SP cabinet (by clicking the button in the top right corner)
Select the 'Edit' page of 'ОСОБИСТА ІНФОРМАЦІЯ' tab (by clicking the 'Редагувати' button)

**Steps to reproduce**
  1. Delete the data in 'Прізвище' field and leave this field empty
  2. Enter valid data in the 'Прізвище' field
  3. Repeat step 1 for mandatory fields
  4. Cancel the edit process by clicking the 'Скасувати' button
  5. Click the 'Скасувати' button in pop-up message
  6. Repeat step 4
  7. Click 'Підтвердити' button in pop-up message

**Actual result**
The 'Зберегти' button is still disabled after the data in the 'Прізвище' or 'Ім'я' fields has been changed

**Expected result**
The data in the 'Прізвище' or 'Ім'я fields has been changed, the 'Зберегти' button becomes enabled

**Labels to be added**
"Bug", Priority ("Medium"), Severity ("Medium"), Type ("Functional"),

**Comment by doliinyk** [comment]
@Shveik861 can't reproduce the bug, can you specify which account you are using and check that bug is still exists?
Also we can discuss it in Discord

**Comment by doliinyk** [comment]
Can't reproduce, might be fixed
