### ISSUE TITLE
[SP Edit page] In case of deleting the name of the city and returning it back, red color message is displayed

### ISSUE THREAD

**Issue by Shveik861** [ita-social-projects/OoS-Frontend#2148]
**Environment:** Windows 10 Pro, Chrome Version 113.0.5672.129 (64 bit).
**Reproducible:** always.

**Preconditions**
Follow the link https://oos.dmytrominochkin.cloud/#/
Log into OoS website as SP
Select «Мої гуртки» in the menu bar at the top right corner.
At least 1 workshop must be created.
Click on the “Pen” button of the existing workshop.
Select the “Контакти” tab at the top of the page.

**Steps to reproduce**
 1.Set the valid value into the “Місто“ field (e.g.Київ)

 2. Delete all data from "Місто" field and leave it empty

 3.Enter the same values again in "Місто" field

**Actual result**
The “Місто“ field is highlated in red color with message '''Це поле є обов'язковим''
![Defect1](https://github.com/ita-social-projects/OoS-Frontend/assets/134705867/977070cc-99da-4ac8-9b0d-e3b07ef9b150)

https://github.com/ita-social-projects/OoS-Frontend/assets/134705867/b5787c2b-2829-42f4-bfb8-1d0d3be402ae

**Expected result**
The “Місто“ field  аccepts input data
![Defect2](https://github.com/ita-social-projects/OoS-Frontend/assets/134705867/afc37146-3eca-4aad-a5d7-8d7f6fe7fd55)

**Labels to be added**
"Bug", Priority ("medium: "), Severity ("medium:"), Type ("Functional").

**Comment by doliinyk** [comment]
Have to be discussed about the mandatory selection of city/district of city even after user input

**Comment by doliinyk** [comment]
Fixed in https://github.com/ita-social-projects/OoS-Frontend/pull/2354
