### ISSUE TITLE
[Workshop] Information from another workshop is loaded when editing a workshop.

### ISSUE THREAD

**Issue by ViktoriiaHrytchyna** [ita-social-projects/OoS-Frontend#2150]
**Environment:** Windows 10, 64-bit, Google Chrome 107.0.5304.107..
**Reproducible:** always.

**Preconditions**
1.Go to https://oos.dmytrominochkin.cloud/#/
2.Log in as SP Email "[jigoc25090@klblogs.com](mailto:jigoc25090@klblogs.com)", Password "Qazwsx789!".

**Steps to reproduce**
1. Click on the “Magnifying glass/Search” button of Search box on the Main page.
2. Select any workshop and press the "Детальніше" button on the workshop card.
3. Go to the "Мої гуртки" tab of personal cabinet (by clicking the button in the top right corner).
4. Select any workshop on the "Мої гуртки" page and press the "Редагувати" button on the workshop card.
5. Pay attention to the information displayed on the editing page.

**Actual result**
The workshop edit page displays information from a previously viewed workshop.
https://drive.google.com/file/d/1i-OUe2Or478ZfxerijrCNMyFYUEIYWkA/view?usp=sharing

**Expected result**
When editing a workshop, the previously filled information about the workshop being edited is displayed on the page. Information from another previously viewed workshop cannot be uploaded.

**Labels to be added**
"Bug", Priority ("pri: high"), Severity ("severity: high"), Type ("UI, "Functional").

**Comment by koliaBp** [comment]
Fixed

**Comment by ViktoriiaHrytchyna** [comment]
Fixed
