### ISSUE TITLE
[SP: Create workshop, section "Про гурток"] The system accepts an invalid email. No error message appears.

### ISSUE THREAD

**Issue by OlenaYakubova** [ita-social-projects/OoS-Frontend#2152]
**Environment:** Windows 11 64 bit, Google Chrome 114.0.5735.199
**Reproducible:** always.

**Preconditions**
1. Follow the link https://oos.dmytrominochkin.cloud/#/
2. Log into OoS website as SP (e.g. 'email'="didiri7796@pelung.com", 'Password'="D@diri7796")
3. Select «Мої гуртки» in the menu bar at the top right corner.
4. Click on the “Додати гурток” button.

**Steps to reproduce**
1.  Fill in all mandatory fields in "Про гурток" section.
2. Set the invalid value (e. g. 0@0) into the “Електронна пошта“ field 

**Actual result**
No error message appears. The field is marked with a grey margin. "Далі" button is clickable.
![image](https://github.com/ita-social-projects/OoS-Frontend/assets/73597578/8ff2b765-daa6-4292-befe-0b1c728cbdc5)

**Expected result**
"Введіть коректний email." red colour Error message is displayed. The field is marked with a red margin.
"Далі" button is not clickable.

**User story and test case links**
[Test case]  (https://jira.softserve.academy/browse/OS-366)

**Labels to be added**
"Bug", Priority (Medium), Severity ("Medium"), Type "UI","Functional".

**Comment by doliinyk** [comment]
Fixed in #2166
