### ISSUE TITLE
[SP create workshop,"Контакти" section]The system validates non-existent values "Вулиця" and "Будинок" 

### ISSUE THREAD

**Issue by OlenaYakubova** [ita-social-projects/OoS-Frontend#2154]
**Environment:** Windows 11 64 bit, Google Chrome 114.0.5735.199
**Reproducible:** always.

**Preconditions**
1. Follow the link https://oos.dmytrominochkin.cloud/#/
2. Log into OoS website as SP (e.g. 'email'="andrii4437@gmail.com", 'Password'="Qwerty123!")
3. Select "Мої гуртки" in the menu bar at the top right corner.
4. Click on the "Додати гурток" button and fill in all mandatory fields in the "Про гурток" and "Опис"' sections.

**Steps to reproduce**
1. Fill in the field "Місто" with correct data (e. g. "Луцьк")
2. Fill in the field "Вулиця" with non-existent street name (e.g. "Просто собі вулиця")
3. Fill in the field "Будинок" with non-existent house number(e.g. "0безномера")

**Actual result**
1. Field "Вулиця" and 2. Field "Будинок": No error message appears. The fields are marked with a grey margin.
![image](https://github.com/ita-social-projects/OoS-Frontend/assets/73597578/5213c9b0-c530-4b79-bb23-0e2b6aa5edfe)

**Expected result**
1.  "Такої вулиці немає." red color error message is displayed
2.  "Такого будинку немає."  red color error message is displayed

**User story**
https://github.com/ita-social-projects/OoS-Backend/issues/55

[Test case] (https://jira.softserve.academy/browse/OS-368)

**Labels to be added**
"Bug", Priority ("Medium"), Severity ("Medium"), Type ("UI, "Functional"), "API".

**Comment by doliinyk** [comment]
Fixed in https://github.com/ita-social-projects/OoS-Frontend/pull/2354 (discussed only to show label that address not found)
