### ISSUE TITLE
[Create new service institution] The field “ІПН/ЄРДПУО”accepts incorrect registration data, "Реєстрація нового закладу" page, "Інформація про заклад" step

### ISSUE THREAD

**Issue by OlenaYakubova** [ita-social-projects/OoS-Frontend#2177]
**Environment:** Windows 11, 64; Google Chrome 114.0.5735.199
**Reproducible:** always

**Preconditions**
1. Go to [https://oos.dmytrominochkin.cloud/#](https://oos.dmytrominochkin.cloud/)
2. Click on "Увійти/Зареєструватися" button in top right corner of header
3. Click on "Зареєструватися" hyperlink
4. Click on "Надавач послуг" button
5. Fill all mandatory fields with valid data and tick all checkboxes
6. Click on "Зареєструватися" button
7. Сonfirm email address

**Steps to reproduce**
1. Fill in all required fields with correct data
2. Fill in the ЄДРПОУ field with incorrect data (special characters, letters)

**Actual result**
![image](https://github.com/ita-social-projects/OoS-Frontend/assets/73597578/5f34e326-1128-4ca4-abeb-9b1432d64c99)

**Expected result**
1. The margine of "ЄДРПОУ" field is red. "Ведіть коректний ЄДРПОУ" message is displayed under field. "Далі" button is not clikable.

**User story and test case links**

[Test case] https://jira.softserve.academy/browse/OS-95

**Labels to be added**
"Bug", Priority ("Medium "), Severity ("Medium"), Type ( "Functional").

**Comment by doliinyk** [comment]
Have a guess that bug exists in view in [this backend namespace](https://github.com/ita-social-projects/OoS-Backend/tree/develop/OutOfSchool/OutOfSchool.AuthCommon), so can't find it on frontend
