### ISSUE TITLE
[WORKSHOP] There is no text, that requires authorization on the site, when an unauthorized user clicks on the "Подати заяву" button.

### ISSUE THREAD

**Issue by Shliakhtych** [ita-social-projects/OoS-Frontend#2205]
**Environment:** Windows 10, 64-bit, Google Chrome 115.0.5790.171,
Windows 10, 64-bit, Microsoft Edge 114.0.1823.67.
**Reproducible:** always.

**Preconditions**

1. Go to (https://oos.dmytrominochkin.cloud/)
2. The chosen city is Ivano-Frankivsk.
3. There should be at least 1 workshop in the list.

**Steps to reproduce**
1. Choose a workshop.
2. Press the "Детальніше" button.
3. Press the "Подати заяву" button.

**Actual result**
Two buttons "Повернутися" and "Зареєструватися" are displayed on the screen. There is no message.
![image](https://github.com/ita-social-projects/OoS-Frontend/assets/134736243/94a5de0a-5332-4aa8-9bbc-756a1ccbe78e)

**Expected result**
A message is displayed on the screen that in order to continue, you need to log in to the site, as well as two buttons "Повернутися" and "Зареєструватися".
![image](https://github.com/ita-social-projects/OoS-Frontend/assets/134736243/a3486faa-aa7c-4193-b3b2-bdc5c7f2f971)

**User story and test case links**
E.g.: "User story 886
https://github.com/ita-social-projects/OoS-Backend/issues/886

**Labels to be added**
"Bug", Priority ("pri:Medium  "), Severity ("severity:Medium ").

**Comment by doliinyk** [comment]
Fixed in #2206
