### ISSUE TITLE
[UI] Сhild's card in Parent's cabinet. The age and the word "років" are inconsistent.

### ISSUE THREAD

**Issue by OlenaYakubova** [ita-social-projects/OoS-Frontend#2210]
**Environment:** Windows 11, 64; Chrome 115.0.5790.171
**Reproducible:** always.

**Preconditions**
1. Log in like a Parent
2. Thera are registered children from 11 to 14 years old

**Steps to reproduce**
1. Click on  the arrow opposite the name in the top right corner of the page
2.  Click on "Інформація про дітей" line of drop-down list

**Actual result**
![image](https://github.com/ita-social-projects/OoS-Frontend/assets/73597578/6914ea77-3134-4ac1-b3b2-aed6b097c89a)
**Expected result**
Should be "11, 12, 13, 14 років" 

**User story and test case links**

**Labels to be added**
"Bug", Priority ("pri: "Medium"), Severity ("Low"), Type ("UI, "Functional")

**Comment by doliinyk** [comment]
Fixed in #2212
