### ISSUE TITLE
[Personal cabinet] A parent sees incorrect wording when trying to change an unconfirmed email.

### ISSUE THREAD

**Issue by Shliakhtych** [ita-social-projects/OoS-Frontend#2218]
**Environment:** Windows 10, 64-bit, Google Chrome 114.0.5735.199,
Windows 10, 64-bit, Microsoft Edge 114.0.1823.67.
**Reproducible:** always.

**Preconditions**

1. Go to (https://oos.dmytrominochkin.cloud/)
2. The user is authorized as a parent.
3. The user's email must not be verified.

**Steps to reproduce**
1. Go to the "Особиста інформація" tab.
2. Click on "Змінити електронну адресу" button.
3. Fill in the "Старий емейл" field.
4. Fill in the "Новий емейл" field.
5. Click on "Зберегти" button.

**Actual result**
The inscription "Вказаний email  не співпадає з поточним" appears.
![image](https://github.com/ita-social-projects/OoS-Frontend/assets/134736243/469b66e7-3eda-4f4a-ae39-686ffb67486d)
![image](https://github.com/ita-social-projects/OoS-Frontend/assets/134736243/934ec2c3-301f-46ba-ad30-790837c06ff0)

**Expected result**
The inscription "Щоб мати змогу змінити емейл спершу потрібно підтвердити його." appears.

**Labels to be added**
"Bug", Priority ("pri: Medium"), Severity ("severity: Medium").

**Comment by Shliakhtych** [comment]
It should also be added that if the user clicked the "Змінити електронну пошту" button and filled in the "Старий емейл" and "Новий емейл" fields in the new window, then clicked the "Скасувати" button and then "Зберегти", then the wording in the window does not change.

**Comment by doliinyk** [comment]
The wording of the email mismatch is related to the backend
Case that it is possible to change the unconfirmed email still the frontend issue

**Comment by doliinyk** [comment]
Frontend side fixed in https://github.com/ita-social-projects/OoS-Frontend/pull/2362
