### ISSUE TITLE
[Notification] There is no redirect from the notifications page to the "Заявки" page.

### ISSUE THREAD

**Issue by ViktoriiaHrytchyna** [ita-social-projects/OoS-Frontend#2224]
**Environment:** Windows 10, 64-bit, Google Chrome 107.0.5304.107.
**Reproducible:** always.

**Preconditions**
1. Go to [https://oos.dmytrominochkin.cloud/#](https://oos.dmytrominochkin.cloud/)
2. Log in as Parent ("Email" = '[pidim28018@irebah.com](https://github.com/ita-social-projects/OoS-Backend/issues/pidim28018@irebah.com)', "password" = 'Qazwsx789!')
3. The father submitted an application to the workshop and recruitment to the workshop was closed.

**Steps to reproduce**
1. Log in as Parent.
2. Click on the bell in the upper right corner.
4. Click on the notification about the closing of the workshop recruitment.
5. Click on the link that appeared under the notification.

**Actual result**
Clicking on the link on the notifications page does not redirect to the "Заявки" page.
![Screenshot_2](https://github.com/ita-social-projects/OoS-Frontend/assets/115226563/a5d4b78d-ea27-4289-b537-f62083d6324b)

**Expected result**
When you click on the link on the notifications page, you will be redirected to the "Заявки" page.

**Labels to be added**
"Bug", Priority ("pri: low"), Severity ("severity: low"), Type ("Functional").

**Comment by Ultrafiolet4** [comment]
Could not repeat the bug, maybe exists some conditions to reproduce this problem?

**Comment by ViktoriiaHrytchyna** [comment]
https://drive.google.com/file/d/1JePiq7YpVGs_bcneqPre7vMt9jmmSl0g/view?usp=sharing

There is no redirection when the notification about the opening of the set or the closing of the set comes to the workshop to which the application was submitted.

**Comment by Ultrafiolet4** [comment]
Thanks for your responce) I'm sorry for bothering you, didn't know the type of notification.
