### ISSUE TITLE
[UI, Add more children] Spelling mistake

### ISSUE THREAD

**Issue by OlenaYakubova** [ita-social-projects/OoS-Frontend#2226]
**Environment:** Windows 11, 64 bit
Chrome 115.0.5790.171
**Reproducible:** always.

**Preconditions**
1. Go to https://oos.dmytrominochkin.cloud/
2. Log in as a Parent (e.g."Email" = 'parent@gmail.com', "password" = 'G23jukd!o')

**Steps to reproduce**
1. Click on Last name or arrow at the top right corner of page
2. Select "Інформація про дітей" tab from drop-down list
3.  Click on "Додати дитину" button

**Actual result**
Spelling mistake. Should be "По батькові"
 
![image](https://github.com/ita-social-projects/OoS-Frontend/assets/73597578/8c9acc80-fc4e-4bbc-9891-202287d1f446)

**Expected result**
Should be "По батькові"

**User story and test case links**
[Test case][#142](https://jira.softserve.academy/browse/OS-142)

**Labels to be added**
"Bug", Priority ("Medium"), Severity ("Trivial"), Type ("UI")

**Comment by doliinyk** [comment]
Fixed in #2228
