### ISSUE TITLE
[Search] Workshops that do not belong to the selected location are displayed on the search page.

### ISSUE THREAD

**Issue by ViktoriiaHrytchyna** [ita-social-projects/OoS-Frontend#2229]
**Environment:** Windows 10, 64-bit, Google Chrome 107.0.5304.107.
**Reproducible:** always.

**Preconditions**
1. Go to [https://oos.dmytrominochkin.cloud/#](https://oos.dmytrominochkin.cloud/)
2. Log in as Parent

**Steps to reproduce**
1. Click on the “Magnifying glass/Search” button of Search box on the Main page.
2. Enter the location of the "Кременчук" city. 
3. Enter the name of the "Водограй" workshop in the search bar and press Enter.

**Actual result**
On the search page, two workshops with the name "Водограй" were found, but one of them is in a different location.
![Screenshot_30](https://github.com/ita-social-projects/OoS-Frontend/assets/115226563/b3d96d62-a4d9-4e8f-8a3c-471fa8273776)

**Expected result**
On the search page, only workshops located in the selected location are found. Workshops from other locations, even if they have the same name, are not displayed.

**Labels to be added**
"Bug", Priority ("pri: medium"), Severity ("severity: low"), Type ("UI, "Functional"), "API" (for back-end bugs).

**Comment by doliinyk** [comment]
Fixed in #2246

**Comment by ViktoriiaHrytchyna** [comment]
Fixed
