### ISSUE TITLE
[Service Provider] There is no information about the workshop on the "Заявки" page

### ISSUE THREAD

**Issue by ViktoriiaHrytchyna** [ita-social-projects/OoS-Frontend#2232]
**Environment:** Windows 10, 64-bit, Google Chrome 107.0.5304.107.
**Reproducible:** always.

**Preconditions**
1. Go to [https://oos.dmytrominochkin.cloud/#](https://oos.dmytrominochkin.cloud/)
2. Log in as Service Provider.

**Steps to reproduce**
1. Go to "Заявки" on the top right corner drop down list.
2. Pay attention to the column with the name of the workshop.

**Actual result**
There is no information about the workshop on the "Заявки" page.
![Screenshot_3](https://github.com/ita-social-projects/OoS-Frontend/assets/115226563/a0c17e45-b36c-4984-9bee-9fd82070eefe)

**Expected result**
Information about the direction and the number of available places is displayed under the name of the workshop.
![Screenshot_10](https://github.com/ita-social-projects/OoS-Frontend/assets/115226563/2eef6079-7e90-4142-bd3d-085eeddc50ee)

**Labels to be added**
"Bug", Priority ("pri: low"), Severity ("severity: low"), Type ("UI").

**Comment by doliinyk** [comment]
Fixed

**Comment by ViktoriiaHrytchyna** [comment]
Fixed
