### ISSUE TITLE
[UI] Spelling mistake in radio button name, when parents apply for workshop

### ISSUE THREAD

**Issue by OlenaYakubova** [ita-social-projects/OoS-Frontend#2233]
**Environment:** Windows 11, 64 bit
Chrome 115.0.5790.171
**Reproducible:** always.

**Preconditions**
1. Go to https://oos.dmytrominochkin.cloud/#
2. Log in as a Parent (e. g. 'Емейл' - "Parent1@meta.ua"; 'Пароль' - "Parent!2")
3. Any Service Provider has at least one registered workshop with open selection.

**Steps to reproduce**
1. Go to workshop from Preconditions.
2. Click the "Детальніше" button at the bottom of the workshop card
3. Click on "Подати заявку" button

**Actual result**
In the window "Подати заяву", section "Подати дані про дитину" there is spelling mistake:
1. ![image](https://github.com/ita-social-projects/OoS-Frontend/assets/73597578/8aa762b7-0a58-40ae-ab78-b3896a8376c4)
In the window "Подати заяву", section "Подати дані про себе" there is spelling mistake:
2. ![image](https://github.com/ita-social-projects/OoS-Frontend/assets/73597578/3faf5fde-2bea-409d-a7df-b0f345d23941)

**Expected result**
Should be "протипоказів"

**Labels to be added**
"Bug", Priority ("Medium"), Severity ("Low"), Type ("UI").

**Comment by doliinyk** [comment]
Fixed in #2235
