### ISSUE TITLE
[UI, Edit Workshop administrator] Spelling mistake in the popup window

### ISSUE THREAD

**Issue by OlenaYakubova** [ita-social-projects/OoS-Frontend#2234]
Environment: Windows 11, 64 bit
Chrome 115.0.5790.171
Reproducible: always.

**Preconditions**
1. Go to https://oos.dmytrominochkin.cloud/#
2. Log in as a Service provider (e. g. 'Емейл' - "Provider1@meta.ua"; 'Пароль' - "Service!1")
3. Service Provider has at least one registered Workshop administrator.

**Steps to reproduce**
1. Click on the last name or arrow at the top right corner of page
2. Choose the "Адміністрування" string
3. Click on "Адміністратор гуртка" tab
4. Select the Workshop administrator from Preconditions
5. Click on the three vertical dots in the last column opposite the name of the Workshop administrator fron Precondition and choose "Редагувати користувача"
6. Edit some information and click "Далі" button.
7. Click on "Зберегти" button

**Actual result**
1. Spelling mistake on pop-up:
![image](https://github.com/ita-social-projects/OoS-Frontend/assets/73597578/cf995199-53bb-484e-8445-5d6049d83450)

2. After changing the language, from Ukrainian to English, the page name changes from "Edit workshop administrator" to "Add workshop administrator"

https://github.com/ita-social-projects/OoS-Frontend/assets/73597578/91356821-f7b7-46a7-9fd7-353c534ce111

**Expected result**
1. Should be "Ви впевнені, що хочете редагувати адміністратора гуртка?"
2. Should be "Edit workshop administrator"

**Labels to be added**
"Bug", Priority ("Medium"), Severity ("Low"), Type ("UI").

**Comment by doliinyk** [comment]
Fixed in #2235
