### ISSUE TITLE
[Info about provider] When pressing the F5 button, when editing information about the provider, the page does not return to its previous state.

### ISSUE THREAD

**Issue by Shliakhtych** [ita-social-projects/OoS-Frontend#2244]
**Environment:**  Windows 10, 64-bit, Google Chrome 116.0.5845.179,
Windows 10, 64-bit, Microsoft Edge 114.0.1823.67.
**Reproducible:** Always.

**Preconditions**

1. Go to https://oos.dmytrominochkin.cloud/#/.
2. Log in to the site as a service provider.

**Steps to reproduce**

1. Go to the "Information about the provider" page.
2. Click on the "Edit" button.
3. Press the F5 key.

**Actual result**
The page does not return to the previous state when pressing the F5 key.
![image](https://github.com/ita-social-projects/OoS-Frontend/assets/134736243/91c132a1-04c4-4c44-906f-1ba77c971eaf)

**Expected result**
Pressing the F5 key refreshes the page and returns to the previous state.

**Labels to be added**
"Bug", Priority ("pri: High"), Severity ("severity: High"), Type ("Functional").

**Comment by doliinyk** [comment]
Fixed in #2276
