### ISSUE TITLE
[Info about child, EN Localization] When changing the localization to EN, the localization for social groups is not indicated in the request to the backend.

### ISSUE THREAD

**Issue by Shliakhtych** [ita-social-projects/OoS-Frontend#2245]
**Environment:** Windows 10, 64-bit, Google Chrome 116.0.5845.179,
Windows 10, 64-bit, Microsoft Edge 114.0.1823.67.
**Reproducible:** Always.

**Preconditions**

1. Go to https://oos.dmytrominochkin.cloud/#/.
2. Log in to the site as a parent.
3. Select the English localization of the site.

**Steps to reproduce**

1. Go to the "Information about children" page.
2. Click on the "Add child" button.
3. Click on the drop-down list with social groups.

**Actual result**
Social groups are not localized, displayed in Ukrainian, although English localization is selected.
![image](https://github.com/ita-social-projects/OoS-Frontend/assets/134736243/609ba719-b5fa-4c9e-b11f-56c56e00b144)

**Expected result**
The father sees localized social groups.

**Labels to be added**
"Bug", Priority ("pri: Low"), Severity ("severity: Low"), Type ("Localization").

**Comment by doliinyk** [comment]
This is backend issue because untranslated social groups coming from backend by endpoint `/api/v1/SocialGroup/Get`.

**Comment by doliinyk** [comment]
Fixed in #2249

**Comment by doliinyk** [comment]
Completely fixed in #2274
