### ISSUE TITLE
 [Сhild Information] The "Зберегти" button works several times, and returns the browser pages back when you quickly click the "Зберегти" button several times.

### ISSUE THREAD

**Issue by Shliakhtych** [ita-social-projects/OoS-Frontend#2255]
**Environment:** Windows 10, 64-bit, Google Chrome 117.0.5938.88,
Windows 10, 64-bit, Microsoft Edge 114.0.1823.67.
**Reproducible:** always.

**Description**

When you quickly press the "Save" button, it works several times and returns the browser pages several pages back.

**Preconditions**

1. Go to (https://oos.dmytrominochkin.cloud/)
2. The user is authorized as a parent.
3. At least 1 child must be created.

**Steps to reproduce**

1. Go to the "Інформація про дітей" tab.
2. Select a child from the list and Click on the "Редагувати" button.
3. Quickly press the "Зберегти" button several times.

**Actual result**
The information is saved, the user returns several pages back.

VIDEO - https://app.screencast.com/eHZPgprOZmTn6

**Expected result**
The information is saved, the user returns to the "Особиста інформація" page.

**Labels to be added**
"Bug", Priority ("pri: High"), Severity ("severity: High").

**Comment by Shliakhtych** [comment]
The error is still there. The defect continues to reproduce.

**Comment by Ultrafiolet4** [comment]
Bug fixed in #2257 pull request
