### ISSUE TITLE
[Parent,SP roles] If you follow hyperlink-workshop's name from "Заявки" section, information about workshop is displayed incorrectly

### ISSUE THREAD

**Issue by OlenaYakubova** [ita-social-projects/OoS-Frontend#2261]
**Environment:** Windows 11, 64 bit
Chrome 117.0.5938.89
**Reproducible:** always.

**Preconditions**
1. Parent has at least 1 child, credentials: login - [dub@gmail.com](mailto:dub@gmail.com) password - Qwert1!
2. SP has at least 1 workshop, credentials: login - [kamin@gmail.com](mailto:kamin@gmail.com) password - Qwerty1!
3. At least one application with any status is in Parent's cabinet.
4. Log in as Parent

**Steps to reproduce**
1. Click on arrow or Last name at top right corner of the page
2. Select the 'Заявки' line from the drop-down list
3. Choose any hyperlink-workshop's name in the list of applications

**Actual result**
1. Flexbox isn't reproduce
2. Unable to switch between tabs
https://app.screencast.com/ihb7XI1tZUetg

**Expected result**
1. ![image](https://github.com/ita-social-projects/OoS-Frontend/assets/73597578/673cd21d-75bc-4f9b-b3b3-1c02e27e0256)
2. User can switch between tabs

**User story and test case links**
[Test case][#612](https://jira.softserve.academy/browse/OS-612)

**Labels to be added**
"Bug", Priority ("High"), Severity ("High"), Type ("Functional")

**Comment by Ultrafiolet4** [comment]
Bug fixed on backend
