### ISSUE TITLE
[Blocking] The service provider will get an error when trying to block the user.

### ISSUE THREAD

**Issue by Shliakhtych** [ita-social-projects/OoS-Frontend#2264]
**Environment:** Windows 10, 64-bit, Google Chrome 117.0.5938.92,
Windows 10, 64-bit, Microsoft Edge 114.0.1823.67. 
**Reproducible:** Always.

**Preconditions**

1. Go to (https://oos.dmytrominochkin.cloud/)
2. The user is authorized as a service provider.
3. The service provider must have at least one workshop.
4. At least 1 application must be sent to the created workshop.

**Steps to reproduce**

1. Go to the "APPLICATIONS" tab.
2. From the list of applications, select the application of the user you want to block.
3. Click on the mat-menu panel.
4. Click on the "Block the user" button.
5. Specify the blocking reason.

**Actual result**
The service provider sees an error message. The user is not blocked.

![image](https://github.com/ita-social-projects/OoS-Frontend/assets/134736243/b4e21910-9784-4679-a434-5bdf7fa07cd5)
![image](https://github.com/ita-social-projects/OoS-Frontend/assets/134736243/0f034deb-2017-4351-aa25-9d6c896758e0)

**Expected result**
The service provider sees a message about the successful blocking of the user.

**Labels to be added**
"Bug", Priority ("pri: Medium"), Severity ("severity:Medium"), Type ("Functional").

**Comment by doliinyk** [comment]
Can't reproduce, might be fixed
