### ISSUE TITLE
[UI] Interface elements are displayed and clickable when clicking on the burger menu button in the user's personal account if the user has the 750 screen extension installed.

### ISSUE THREAD

**Issue by Shliakhtych** [ita-social-projects/OoS-Frontend#2265]
**Environment:** Windows 10, 64-bit, Google Chrome 117.0.5938.92,
Windows 10, 64-bit, Microsoft Edge 114.0.1823.67.
**Reproducible:** always.

**Preconditions**

1. Go to (https://oos.dmytrominochkin.cloud/)
2. The user is authorized as a parent.
3. 750 screen extension installed.

**Steps to reproduce**
1. Go to the "Personal information" tab.
2. Click on the "Burger menu" button.

**Actual result**
A burger menu opens, interface elements shine through the interface, and are also clickable.
![image](https://github.com/ita-social-projects/OoS-Frontend/assets/134736243/b80336a7-c3e7-44ff-a1dc-8b895d9ca8e6)
![image](https://github.com/ita-social-projects/OoS-Frontend/assets/134736243/4f1379c7-3d4d-4646-96a3-d250f7814b57)

**Expected result**
The burger menu opens. All interface elements are aligned, written without errors, colors are reproduced according to the mockup.

**Labels to be added**
"Bug", Priority ("pri: Low"), Severity ("severity: Low"), Type ("UI").

**Comment by doliinyk** [comment]
Fixed in #2263
