### ISSUE TITLE
[Сhild Information] The "Save" button is active and is clicked when the user has not changed any information.

### ISSUE THREAD

**Issue by Shliakhtych** [ita-social-projects/OoS-Frontend#2267]
**Environment:** Windows 10, 64-bit, Google Chrome 117.0.5938.92,
Windows 10, 64-bit, Microsoft Edge 114.0.1823.67.
**Reproducible:** Always.

**Preconditions**

1. Go to https://oos.dmytrominochkin.cloud/#/.
2. Log in to the site as a parent.
3. At least one child must be created.

**Steps to reproduce**
1. Go to the "Information about children" page.
2. Select a child from the list and click the "Edit" button.

**Actual result**
The "Save" button is active and clickable even when the user has not changed any information.
![image](https://github.com/ita-social-projects/OoS-Frontend/assets/134736243/aac00efd-5224-473f-beab-f6244b07d5eb)

**Expected result**
The "Save" button is disabled until the user makes any changes.

**Labels to be added**
"Bug", Priority ("pri: Medium"), Severity ("severity: Medium").

**Comment by doliinyk** [comment]
Fixed in #2270
