### ISSUE TITLE
 [Personal cabinet] The user can save editing of personal information when there are spaces in the "First Name" and "Surname" fields.

### ISSUE THREAD

**Issue by Shliakhtych** [ita-social-projects/OoS-Frontend#2268]
**Environment:** Windows 10, 64-bit, Google Chrome 117.0.5938.92,
Windows 10, 64-bit, Microsoft Edge 114.0.1823.67.
**Reproducible:** Always.

**Preconditions**

1. Go to https://oos.dmytrominochkin.cloud/#/.
2. Log in to the site as a parent.

**Steps to reproduce**

1. Go to the "Personal information" page.
2. Click on the "Edit" button.
3. In the last name field, enter "Ба ть ко Ма ти".

**Actual result**
The user has the option to save the edit despite the fact that there are spaces in the "Name" fields. There are no error messages about the presence of spaces.
![image](https://github.com/ita-social-projects/OoS-Frontend/assets/134736243/dac1feaf-6d32-4220-ac5a-65a3003340b3)

**Expected result**
When entering a space in the "Name" field, the user sees the error message "Перевірте введені дані, використовуйте, будь ласка, тільки кирилицю та символи(', -)", and the save button becomes disabled.
![image](https://github.com/ita-social-projects/OoS-Frontend/assets/134736243/d2783730-dba9-42ca-a4ff-981221bf63b8)

**Labels to be added**
"Bug", Priority ("pri: Medium "), Severity ("severity:Medium ").

**Comment by doliinyk** [comment]
Fixed in #2270
