### ISSUE TITLE
[Сhild Information] The parent does not see an error message when editing children's personal information, if he entered a space in the "Name" field.

### ISSUE THREAD

**Issue by Shliakhtych** [ita-social-projects/OoS-Frontend#2269]
**Environment:** Windows 10, 64-bit, Google Chrome 117.0.5938.92,
Windows 10, 64-bit, Microsoft Edge 114.0.1823.67.
**Reproducible:** Always.

**Preconditions**

1. Go to https://oos.dmytrominochkin.cloud/#/.
2. Log in to the site as a parent.
3. At least one child must be created.

**Steps to reproduce**

1. Go to the "Information about children" page.
2. Select a child from the list and click the "Edit" button.
3. Enter the "Галя Валя" data in the "Name" field.

**Actual result**
The user does not see any error messages about the forbidden character. The "Save" button is active. But when clicking the save button, the edit is not saved, the user sees the error message "Unfortunately, an error has occurred".
![image](https://github.com/ita-social-projects/OoS-Frontend/assets/134736243/b1085b43-1d44-4800-874b-b61345438cdf)

**Expected result**
After entering a space in the field, the user sees the error message  "Перевірте введені дані, використовуйте, будь ласка, тільки кирилицю та символи(', -)". The "Save" button is disabled.

**Labels to be added**
"Bug", Priority ("pri: Medium"), Severity ("severity: Medium").

**Comment by doliinyk** [comment]
Fixed in #2270
