### ISSUE TITLE
[Service Provider] Invalid placeholder in field.

### ISSUE THREAD

**Issue by ViktoriiaHrytchyna** [ita-social-projects/OoS-Frontend#2272]
**Environment:** Windows 10, 64-bit, Google Chrome 107.0.5304.107.
**Reproducible:** always.

**Preconditions**
1. Go to [https://oos.dmytrominochkin.cloud/#](https://oos.dmytrominochkin.cloud/)
2. Log in as Service Provider.
3. SP doesn't have created workshops.

**Steps to reproduce**
1. Go to "Адміністрування" on the top right corner drop down list.
2. Click on "Додати" button.
3. Select "Адміністратора гуртка" from the drop-down list.
4. Fill in all mandatory fields of the "Особиста інформація" tab on the "Додати адміністратора гуртка" page.
5. Click on "Далі" button.
6. Pay attention to the field for selecting workshops for the administrator.

**Actual result**
In the field for selecting workshops for the administrator, if there are no workshops, an incorrect placeholder appears.
![image](https://github.com/ita-social-projects/OoS-Frontend/assets/115226563/f9218f5e-299f-452f-8ecc-d215735bc03e)

**Expected result**
The placeholder in the workshop selection field for the administrator in the absence of any workshops should be "0 workshops".

**Labels to be added**
"Bug", Priority ("pri: low"), Severity ("severity: low"), Type ("UI").

**Comment by doliinyk** [comment]
Fixed in #2275

**Comment by ViktoriiaHrytchyna** [comment]
Fixed
