### ISSUE TITLE
[Workshop] The service provider cannot save workshop edits if the "For free" radio button is selected.

### ISSUE THREAD

**Issue by Shliakhtych** [ita-social-projects/OoS-Frontend#2273]
**Environment:** Windows 10, 64-bit, Google Chrome 117.0.5938.92,
Windows 10, 64-bit, Microsoft Edge 114.0.1823.67.
**Reproducible:** Always.

**Preconditions**

1. Go to https://oos.dmytrominochkin.cloud/#/.
2. Log in to the site as a service provider.
3. The service provider must have at least one workshop set up.

**Steps to reproduce**

1. Go to the "My workshops" page.
2. Select a workshop from the list and click the "Edit" button.
3. Set the radio button to "For free".
4. Click on the button "Next" > "Next" > "Next" > "Save".

**Actual result**
The service provider sees an error message and cannot save the workshop edit.
![image](https://github.com/ita-social-projects/OoS-Frontend/assets/134736243/846b470e-a5a8-4969-b7fc-39e6781da869)
![image](https://github.com/ita-social-projects/OoS-Frontend/assets/134736243/7ad1c071-7141-49cf-8f18-e4bb82ebc72e)

**Expected result**
When the service provider clicks the "Save" button, he returns to the "My workshops" page and sees the message "The workshop has been updated successfully!"

**Labels to be added**
"Bug", Priority ("pri: Medium"), Severity ("severity: Medium").

**Comment by doliinyk** [comment]
Can't reproduce, might be fixed
