### ISSUE TITLE
[UI] Change "Емейл" to "Імейл"

### ISSUE THREAD

**Issue by OlenaYakubova** [ita-social-projects/OoS-Frontend#2279]
**Environment:** Windows 11, 64 bit
Chrome 117.0.5938.89
**Reproducible:** always.

**Steps to reproduce**
All words "Емейл" should be changed to "Імейл" (Login page, Change Email page and others)

**Actual result**
 ![image](https://github.com/ita-social-projects/OoS-Frontend/assets/73597578/e03c8a93-4156-42f7-a253-441fe5e63384)

**Expected result**
Shoul be "Імейл" (https://mon.gov.ua/storage/app/media/zagalna%20serednya/%202019.pdf С. 90)

**Labels to be added**
"Bug", Priority ("High"), Severity ("Trivial"), Type ("UI").

**Comment by doliinyk** [comment]
Label on screen exists on the backend (as auth view)
Entries in frontend will come with #2280

**Comment by doliinyk** [comment]
Fixed
