### ISSUE TITLE
[Role:RegionAdmin] "Адміністрування" tab does not meet requirements

### ISSUE THREAD

**Issue by OlenaYakubova** [ita-social-projects/OoS-Frontend#2282]
**Environment:** Windows 11, 64 bit
Chrome 115.0.5790.171
**Reproducible:** always.

**Preconditions**
1. Go to https://oos.dmytrominochkin.cloud/
2. Log in as Region Admin

**Steps to reproduce**
1. Go to "Адміністрування" tab
3. Click on "Адміністрування" link in Intertext navigation

**Actual result**
Information is displayed that should not be in the office of Region Admin
![image](https://github.com/ita-social-projects/OoS-Frontend/assets/73597578/42e2d678-22c0-49f2-8c5f-fb37683c5752)

**Expected result**
![image](https://github.com/ita-social-projects/OoS-Frontend/assets/73597578/02879210-2f1c-41a1-8d90-bd085c74b9fa)

**User story and test case links**

**Labels to be added**
"Bug", Priority ("Medium"), Severity ("Medium"), Type ("UI")

**Comment by doliinyk** [comment]
Fixed in #2283
