### ISSUE TITLE
[Blocked parent] The service provider sees an error message when trying to block a previously blocked user.

### ISSUE THREAD

**Issue by Shliakhtych** [ita-social-projects/OoS-Frontend#2287]
**Environment:** Windows 10, 64-bit, Google Chrome 118.0.5993.70,
Windows 10, 64-bit, Microsoft Edge 114.0.1823.67.
**Reproducible:** Always.

**Preconditions**

1. Go to https://oos.dmytrominochkin.cloud/#/.
2. Log in to the site as a service provider.
3. The service provider must receive at least one message from the user as a parent.
4. The user in the role of parent is already blocked by the provider.

**Steps to reproduce**

1. Go to the "message" page.
2. Select from the list of messages the user you want to block.
3. Click on the "Block the user" button.
4. Enter the blocking reason in the field and confirm.

**Actual result**
The service provider sees an error message if it tries to block an already blocked user.
![image](https://github.com/ita-social-projects/OoS-Frontend/assets/134736243/57780155-43c1-44a3-a998-b9d6308e5d13)

**Expected result**
The service provider user cannot press the block user button because it is not active because the parent user is already blocked.

**User story and test case links**
https://github.com/ita-social-projects/OoS-Backend/issues/454

Labels to be added
"Bug", Priority ("pri: Medium"), Severity ("severity: Medium"), Type ("Functional").

**Comment by doliinyk** [comment]
Fixed in https://github.com/ita-social-projects/OoS-Frontend/pull/2339

**Comment by Shliakhtych** [comment]
This bug still reproduces.

**Comment by doliinyk** [comment]
Well, it's because of property changed `isBlocked` to `isBlockedByProvider` on backend. Will be fixed

**Comment by doliinyk** [comment]
Completely fixed in https://github.com/ita-social-projects/OoS-Frontend/pull/2357, try to validate it again
