### ISSUE TITLE
[Blocked parent] Incorrect wording when unlocking a user as a parent by a service provider.

### ISSUE THREAD

**Issue by Shliakhtych** [ita-social-projects/OoS-Frontend#2288]
**Environment:** Windows 10, 64-bit, Google Chrome 118.0.5993.70,
Windows 10, 64-bit, Microsoft Edge 114.0.1823.67.
**Reproducible:** Always.

**Preconditions**

1. Go to https://oos.dmytrominochkin.cloud/#/.
2. Log in to the site as a service provider.
3. The service provider must receive at least one message from the user as a parent.
4. The user in the role of parent is already blocked by the provider.

**Steps to reproduce**

1. Go to the "Applications" page.
2. Go to the "Blocked" tab.
3. Select from the list the user you need to unblock.
4. Click on the "Unblock the user" button.

**Actual result**
The service provider sees an incorrect "User blocked successfully" notification.
![image](https://github.com/ita-social-projects/OoS-Frontend/assets/134736243/476e2fc2-4a7f-424f-83da-3047c492a018)
![image](https://github.com/ita-social-projects/OoS-Frontend/assets/134736243/53c60c04-b775-45a1-bd81-5af570e5227c)

**Expected result**
The service provider sees a "User successfully unlocked" notification.

**User story and test case links**
https://github.com/ita-social-projects/OoS-Backend/issues/454

**Labels to be added**
"Bug", Priority ("pri: Medium"), Severity ("severity: Medium"), Type ("Functional").

**Comment by doliinyk** [comment]
Appears to be fixed in #2296
