### ISSUE TITLE
[Message] There is no unread message marker on the "Повідомлення" page.

### ISSUE THREAD

**Issue by ViktoriiaHrytchyna** [ita-social-projects/OoS-Frontend#2292]
**Environment:** Windows 10, 64-bit, Google Chrome 107.0.5304.107.
**Reproducible:** always.

**Preconditions**
1. Go to [https://oos.dmytrominochkin.cloud/#](https://oos.dmytrominochkin.cloud/)
2. Log in as SP.
3. The service provider sent a message to the parent.

**Steps to reproduce**
1.  Log in as Parent.
2. Go to the "Повідомлення" page.
3. Pay attention to a new message from the service provider.

**Actual result**
The Parent does not have an unread message marker on the "Повідомлення" page.
![image](https://github.com/ita-social-projects/OoS-Frontend/assets/115226563/31a9360f-5f1b-427a-9040-960ac2f7dd27)

**Expected result**
When the service provider sends a new message to the parent, the parent sees a new message with an unread message marker (blue vertical bar) on the "Повідомлення" page.

**Labels to be added**
"Bug", Priority ("pri: low"), Severity ("severity: low"), Type ("UI").

**Comment by SergeyGSA** [comment]
This bug isn't reproduced anymore. @ViktoriiaHrytchyna Could you please validate it?

**Comment by OMGaranina** [comment]
@SergeyGSA There is a blocker to verify this bug.
1. The parent doesn`t get notifications about new messages. After opening the 'Messages' page as a parent there are no new unread messages. Notifications and new messages appeared after refreshing the page. Or (as was mentioned in 'steps to reproduce') after the user login as a parent after the message was sent from the service provider
2. The service provider, as well, doesn`t get notifications about new messages. But in this case, after opening the 'Messages' page, new message is displayed and marked as unread.

**Comment by OMGaranina** [comment]
Further improvements to the functionality of sending messages (according to the comment above)  are delayed.
