### ISSUE TITLE
[SP creates assistant/admin] After clicking the "Зберегти" button, the system does not show that a workshop administrator has been created.

### ISSUE THREAD

**Issue by OlenaYakubova** [ita-social-projects/OoS-Frontend#2299]
**Environment:**Windows 11, 64 bit  
Chrome 119.0.6045.105 
**Reproducible:** always.

**Preconditions**
1. Go to https://oos.dmytrominochkin.cloud/
2. Log in as a Service provider
3. Service provider has at list one workshop (for creating workshop administrator)

**Steps to reproduce**
1. Go to 'Адміністрування' tab
4. Click on 'Додати' button
5. Select "Provider deputy" or "Workshop admistrator" line from drop-down list
6. Fill in all mandatory fields
7. Click on "Далі" button
8. Select workshop (for "Workshop admistrator") 
9. Click on "Зберегти" button
10. Click on "Підтвердити" button on pop-ap

**Actual result**
After clicking the "Зберегти" button, the system does not show that a workshop administrator has been created. After second clicking on the "Зберегти" button pop-up "На жаль, виникла помилка" appears. User was created.
https://app.screencast.com/WSUtrFRv673Fm

**Expected result**

![image](https://github.com/ita-social-projects/OoS-Frontend/assets/73597578/ebd5c34f-fcd2-4b98-a0b8-ea646cb8fc79)

**User story and test case links**
User story #213
**Labels to be added**
"Bug", Priority ("High"), Severity ("Medium"), Type ("Functional")

**Comment by doliinyk** [comment]
Fixed in #2308
