### ISSUE TITLE
[Workshop administrator cabinet] In the cabinet of the workshop administrator "Редагувати" institution button is active.

### ISSUE THREAD

**Issue by OlenaYakubova** [ita-social-projects/OoS-Frontend#2300]
**Environment:** Windows 11, 64 bit 
Chrome 119.0.6045.105 
**Reproducible:** always.

**Preconditions**
1. Go to https://oos.dmytrominochkin.cloud/
2. Log in as Workshop administrator

**Steps to reproduce**
1. Go to 'Інформація про заклад' tab
2. Click on 'Редагувати' button

**Actual result**
 In the cabinet of the workshop administrator, "Редагувати" institution button is active.
![image](https://github.com/ita-social-projects/OoS-Frontend/assets/73597578/c629b3e2-98ba-4f2a-83fe-83dec4678db7)

**Expected result**
Workshop administrator takes action according to the roles and permissions matrix: 
[Permissions matrix](https://docs.google.com/spreadsheets/d/1FBjayqgq5KQyZNRu5aY3q_RgPMi4tvjwNbjR3iekge0/edit#gid=404315089)

**User story and test case links**
User stories [#523](https://github.com/ita-social-projects/OoS-Backend/pull/523#issuecomment-1019294165)

**Labels to be added**
"Bug", Priority ("Medium"), Severity ("Medium"), Type ("UI")

**Comment by doliinyk** [comment]
~~Fixed in #2308~~

**Comment by doliinyk** [comment]
Fixed in https://github.com/ita-social-projects/OoS-Frontend/pull/2323
