### ISSUE TITLE
[Worckshop page] Amoung of workshops on "Інші гуртки закладу" tab are displayed incorectly

### ISSUE THREAD

**Issue by OlenaYakubova** [ita-social-projects/OoS-Frontend#2305]
**Environment:** Windows 11, 64
Chrome 119.0.6045.160
**Reproducible:** always.

**Preconditions**
1. Go to https://oos.dmytrominochkin.cloud/
2. Log in as Service provider
3. Service Provider has at least two workshops

**Steps to reproduce**
1. Go to 'Мої гуртки' tab
2. Click on 'Детальніше' icon (next to the name of the workshop card)
4. Select "Інші гуртки закладу" tab on Workshop page

**Actual result**
The current workshop is displayed on "Інші гуртки закладу" tab.
![image](https://github.com/ita-social-projects/OoS-Frontend/assets/73597578/b4d0c702-3ff2-43a5-b8e2-65b2f574df61)

**Expected result**
The current workshop is not displayed on "Інші гуртки закладу" tab.  All other workshops of Service provider from precondition should be displayed on "Інші гуртки закладу", apart from current workshop.
(https://www.figma.com/file/YRYP4zAAchOyYMgdoeP782/MoE-%7C-Dev-Team?type=design&node-id=1-1364&mode=design&t=D86vqz10UZCHXWPa-0)

**User story and test case links**
E.g.: "User story #100
[Test case]([#100 Story](https://github.com/ita-social-projects/OoS-Frontend/issues/100))"

**Labels to be added**
"Bug", Priority ("High"), Severity ("Medium"), Type ("UI'', "Functional").

**Comment by doliinyk** [comment]
Fixed in #2306
