### ISSUE TITLE
[Blocked parent] The red mark is missing on the left of the message history on the "Messages" page.

### ISSUE THREAD

**Issue by Shliakhtych** [ita-social-projects/OoS-Frontend#2311]
**Environment:** Windows 10, 64-bit, Google Chrome 118.0.5993.70,
Windows 10, 64-bit, Microsoft Edge 114.0.1823.67.
**Reproducible:** always.

**Preconditions**

1. Go to https://oos.dmytrominochkin.cloud/#/.
2. Log in to the site as a parent.
3. The user as a parent has sent at least one message to the service provider.
4. The user in the role of parent is already blocked by the provider.

**Steps to reproduce**

1. Go to the "Messages" page.
2. Pay attention to the mark on the left of the history of correspondence with the service provider.

**Actual result**
There is no red mark indicating that the user is blocked on the left side of the history of correspondence with the service provider.

![image](https://github.com/ita-social-projects/OoS-Frontend/assets/134736243/6b11b65b-f485-4fd7-bd91-f4e321201bc7)

**Expected result**
The red mark indicating that the user is blocked is on the left of the history of correspondence with the service provider.

![image](https://github.com/ita-social-projects/OoS-Frontend/assets/134736243/1a9a80e7-17cb-459a-a21b-eef8d2c6c810)

**Notes**
1. Pay attention to the fact that there is also no inscription "Blocked" on the message.

![image](https://github.com/ita-social-projects/OoS-Frontend/assets/134736243/1a2e6756-92a0-4503-9953-d99c09c34dbc)

**User story and test case links**
https://github.com/ita-social-projects/OoS-Backend/issues/454

**Labels to be added**
"Bug", Priority ("pri: Medium"), Severity ("severity: Medium"), Type ("UI").

**Comment by Shliakhtych** [comment]
This bug still reproduces.

**Comment by doliinyk** [comment]
Seems to be fixed in https://github.com/ita-social-projects/OoS-Frontend/pull/2357
