### ISSUE TITLE
 [SP creates assistant/admin] The service provider sees a standard error message after clicking the "Save" button and entering an already occupied email.

### ISSUE THREAD

**Issue by Shliakhtych** [ita-social-projects/OoS-Frontend#2313]
**Environment:** Windows 10, 64-bit, Google Chrome 118.0.5993.70,
Windows 10, 64-bit, Microsoft Edge 114.0.1823.67.
**Reproducible:** always.

**Preconditions**

1. Go to https://oos.dmytrominochkin.cloud/;
2. Log in as a Service provider;
3. The service provider has at least one workshop (for creating a workshop administrator).

**Steps to reproduce**

1. Go to 'Адміністрування' tab;
2. Click on 'Додати'  button;
3. Select "Provider deputy"  from a drop-down list;
4. Fill in all mandatory fields (Enter an already occupied email in the email field);
5. Click on "Далі" button;
6. Click on the "Зберегти" button;
7. Click on the "Підтвердити" button on pop-ap;
8. Pay attention to the message that the service provider sees.

**Actual result**
 The standard message " Unfortunately, an error has occurred" appears on the screen. The service provider does not understand where the error is.  
![image](https://github.com/ita-social-projects/OoS-Frontend/assets/134736243/05922a26-cebe-48b8-91b2-1b3e0eea5c0e)

**Expected result**
The service provider sees a "Please enter another email" notification.

**Labels to be added**
"Bug", Priority ("pri: Medium"), Severity ("severity: Medium"), Type ("UI").

**Comment by doliinyk** [comment]
Fixed in https://github.com/ita-social-projects/OoS-Frontend/pull/2347
