### ISSUE TITLE
[Ministry Administrator cabinet] There is an unnecessary tab in the cabinet of Ministry administrator

### ISSUE THREAD

**Issue by OlenaYakubova** [ita-social-projects/OoS-Frontend#2315]
**Environment:** Windows 11, 64 bit
Chrome 119.0.6045.160
**Reproducible:** always.

**Preconditions**
1. Go to https://oos.dmytrominochkin.cloud/#/
2. Log in as Ministry administrator

**Steps to reproduce**
1. Go to 'Адміністрування' tab
2. Click on 'Напрямки' subtab

**Actual result**
"Напрямки" subtub is displayed
![image](https://github.com/ita-social-projects/OoS-Frontend/assets/73597578/a101d911-5185-4fe2-9d5a-a7ee0f3def2d)

**Expected result**
Subtub "Напрямки" shouldn't be in the cabinet of Ministry Administrator
![image](https://github.com/ita-social-projects/OoS-Frontend/assets/73597578/3363fcfc-fbc8-4c9b-9db1-1e32565e3ff5)

**User story and test case links**
[Mock-up][# Figma](https://www.figma.com/file/YRYP4zAAchOyYMgdoeP782/MoE-%7C-Dev-Team?type=design&node-id=8639-8353&mode=design&t=IAfVDRKnPni2DP1Y-0)

**Labels to be added**
"Bug", Priority ("High"), Severity ("High"), Type ("UI")

**Comment by doliinyk** [comment]
Fixed in #2319
