### ISSUE TITLE
[Tech-Admin cabinet; Directions] In the English-language version of the site, part of the information is displayed in Ukrainian

### ISSUE THREAD

**Issue by OlenaYakubova** [ita-social-projects/OoS-Frontend#2316]
**Environment:** Windows 11, 64 bit
Chrome 119.0.6045.160
**Reproducible:** always.

**Preconditions**
1) Go to https://oos.dmytrominochkin.cloud/#/
2) Select EN version of site (by clicking combo box next to language icon)
3) Log in as Tech-Admin

**Steps to reproduce**
1. Go to 'Адміністрування' tab
2. Click on 'Напрямки' subtab

**Actual result**
A part of information on "Напрямки"  subtab is displayed in Ukrainian
![image](https://github.com/ita-social-projects/OoS-Frontend/assets/73597578/8b59f7a7-5084-444a-9f10-c84b5dae7f77)
Click on subtabs "МКПІ", "Мінспорт", "МОН":
![image](https://github.com/ita-social-projects/OoS-Frontend/assets/73597578/cac4cd92-ae8b-443a-91ef-46c8583c92cd)
![image](https://github.com/ita-social-projects/OoS-Frontend/assets/73597578/e7ab5191-1615-4d4d-a908-3d601fa238dc)
![image](https://github.com/ita-social-projects/OoS-Frontend/assets/73597578/fd970918-abc6-4049-97b3-f25637f71860)

**Expected result**
Buttons, column names and placeholders in the English version of site should be in English.

**User story and test case links**
E.g.: "User story #100
[Test case]([#100 Story](https://github.com/ita-social-projects/OoS-Frontend/issues/100))"

**Labels to be added**
"Bug", Priority ("Medium"), Severity ("Low"), Type ("UI").

**Comment by SergeyGSA** [comment]
The subtabs names (МКІП, Мінспорт, МОН) and column names will be in Ukrainian in the near future
