### ISSUE TITLE
[SP Deputy and workshop Administrator cabinets] Server error after clicking "Додати досягнення" link

### ISSUE THREAD

**Issue by OlenaYakubova** [ita-social-projects/OoS-Frontend#2320]
**Environment:** Windows 11, 64 bit
Chrome 120.0.6099.71
**Reproducible:** always.

**Preconditions**
1. Go to https://oos.dmytrominochkin.cloud/
2. Log in as a Service provider deputy
3. Service provider from preconditions has at least one workshop

**Steps to reproduce**
1. Go to 'Мої гуртки' tab
2. Click on 'Додати досягнення' link on workshop card

**Actual result**
Server error after clicking "Додати досягнення" link in servise provider deputy and workshop administrator cabinets. 
![image](https://github.com/ita-social-projects/OoS-Backend/assets/73597578/275560cc-f96b-428c-89ec-67ac4a152adc)

**Expected result**
Service provider deputy can add achievements

**User story and test case links**
E.g.: "User story ita-social-projects/OoS-Backend#456 
(Mock up)[Figma](https://www.figma.com/file/YRYP4zAAchOyYMgdoeP782/MoE-%7C-Dev-Team?type=design&node-id=9204-13542&mode=design&t=m0tryTlnt0iSBFTj-0)

**Labels to be added**
"Bug", Priority ("High"), Severity ("High"), Type ("Functional").

**Comment by doliinyk** [comment]
Seems to be fixed in https://github.com/ita-social-projects/OoS-Backend/pull/1374
