### ISSUE TITLE
[Message button] The send message button is disabled when the parent goes to the workshop recording page.

### ISSUE THREAD

**Issue by Shliakhtych** [ita-social-projects/OoS-Frontend#2346]
**Environment:** Windows 10, 64-bit, Google Chrome 107.0.5304.107.
**Reproducible:** always.

**Preconditions**

1. Go to [https://oos.dmytrominochkin.cloud/#](https://oos.dmytrominochkin.cloud/);
2.  It is necessary to have a workshop in which all places are occupied.

**Steps to reproduce**
1. Log in as a Parent;
2. On the main page, find a workshop in which all places are occupied.
3. Click on the button "more details".
4. Pay attention to the "send message" button.

**Actual result**
The send message button is disabled if there are no free seats in the workshop.
![image](https://github.com/ita-social-projects/OoS-Frontend/assets/134736243/63e50026-e8dc-41b6-98e9-9ec0340ad4c5)

**Expected result**
The parent can send a message to the workshop.

**Labels to be added**
"Bug", Priority ("pri: Medium "), Severity ("severity: Medium "), Type ("Functional").

**Comment by doliinyk** [comment]
Fixed in https://github.com/ita-social-projects/OoS-Frontend/pull/2362
