### ISSUE TITLE
[Workshop's Administrator cabinet] "Administration" tab is unnecessary

### ISSUE THREAD

**Issue by OlenaYakubova** [ita-social-projects/OoS-Frontend#2372]
**Environment:** Windows 11, 64 bit
Chrome121.0.6167.140
**Reproducible:** always.

**Preconditions**
1. Go to https://oos.dmytrominochkin.cloud/
2. Log in as Workshop's Administrator

**Steps to reproduce**
1. Click on on the last name or the arrow in the upper right corner of the page
2. Choose 'Адміністрування' line from dropdown list

**Actual result**
In Workshop's Administrator cabinet is "Administration" tab, but Workshop's Administrator doesn't have permissions to view other Administrators
![image](https://github.com/ita-social-projects/OoS-Frontend/assets/73597578/600c356a-2bc8-4271-9e6f-3e7c81aed45e)

**Expected result**
Workshop's Administrator should not have "Адміністрування" tab

**User story and test case links**
[Roles and Permissions Matrix](https://docs.google.com/spreadsheets/d/1yD1PH5b-4RjtNjNkTZYhOERCRvD3aFK71KVL2noImAw/edit?pli=1#gid=404315089)

**Labels to be added**
"Bug", Priority ("Medium"), Severity ("Medium"), Type ("UI").

**Comment by doliinyk** [comment]
Fixed in https://github.com/ita-social-projects/OoS-Frontend/pull/2371
