### ISSUE TITLE
[Information about SP] 'Опис' field doesn't reflect information in a form as was entered previously after saving

### ISSUE THREAD

**Issue by SyrvatkaTetiana** [ita-social-projects/OoS-Frontend#2420]
**Environment:** Windows 11 Home, browser: Google Chrome 122.0.6261.112
**Reproducible:** Always
**Build found:** "commit [43f4534]"

**Preconditions**
1. The site https://oos.dmytrominochkin.cloud/#/ is opened
2. User is registered as SP

**Steps to reproduce**
1. Go to 'Кабінет надавача послуг'
2. Click on 'Інформація про заклад'
3. Click on 'Опис'
4. Click on 'Редагувати'
5. Fill in 'Назва розділу' 
6. In text field 'Опис' enter every new sentence/information from new lines (E.g. Відділення математики
                                                                                                                                 Відділення економіки
                                                                                                                                 Відділення фізики і астрономії
                                                                                                                                 Відділення філософії та суспільствознавства)
7. Click on 'Зберегти' button

**Actual result**
Information in 'Опис' field is displayed all in one line

**Expected result**
Information is displayed as was entered and saved previously. Every new sentence/info starts from new line/displays in a column)

<img width="403" alt="image" src="https://github.com/ita-social-projects/OoS-Frontend/assets/151456891/d21d4c79-45d6-46a3-8f94-23c0fe5f7df1">

<img width="383" alt="image" src="https://github.com/ita-social-projects/OoS-Frontend/assets/151456891/3bc18299-5422-4036-9a21-39dd84b8396e">

<img width="553" alt="image" src="https://github.com/ita-social-projects/OoS-Frontend/assets/151456891/d1004cf2-9840-45ba-949c-5f0f63506c04">

**Comment by SyrvatkaTetiana** [comment]
@Kazumen can you please double ckeck one more time? An issue was not yet fixed. The result is the same and information in 'Опис' field is displayed all in one line.

**Comment by Kazumen** [comment]
Yes, I apologize, it turned out that I fixed the description of the workshop, not about provider
