### ISSUE TITLE
[Notifications] Text of the notification 'Набір до гуртка закрито'  change to 'Набір до гуртка призупинено'

### ISSUE THREAD

**Issue by OMGaranina** [ita-social-projects/OoS-Frontend#2451]
**Environment:** OS Windows 11Pro Version 23H2, OS Windows 11Pro Version 23H2
**Reproducible:** always
**Build found:** commit [4b76003](https://github.com/ita-social-projects/OoS-Frontend/commit/4b7600379dbd137517e715ff177799eb0a9c25d3)

**Preconditions**
1. The site 'Позашкілля' https://oos.dmytrominochkin.cloud is opened
2. The user is logged in as a service provider with a Common type of institution ownership
3. The workshop_1 with a limited number of places is created
4. The Parent_1 is applied to the workshop_1

**Steps to reproduce**
1. Click on the 'Призупинити набір' button on the workshop_1 card
2. Log in as the Parent_1
3. Click on the 'Notification' button in the header
4. Observe the text of the notification about closing the recruitment to the workshop

**Actual result**
The text of the notification is "Набір до гуртка закрито"
![image](https://github.com/ita-social-projects/OoS-Frontend/assets/95030828/3c9d16e0-a794-4216-ba8f-e57b00cd67e2)

**Expected result**
The text of the notification is "Набір до гуртка призупинено". 

**User story and test case links**
[User story #206](https://github.com/ita-social-projects/OoS-Backend/issues/206)

**Comment by AkunaPatlata** [comment]
@OMGaranina do we also need to change the english version?

**Comment by OMGaranina** [comment]
@AkunaPatlata No changes are needed in English version.
