### ISSUE TITLE
[Edit workshop] 'Це поле є обов'язковим' error message doesn't appear after removing the cursor from all required fields in 'Викладачі' section

### ISSUE THREAD

**Issue by SyrvatkaTetiana** [ita-social-projects/OoS-Frontend#2453]
**Environment:** Windows 11 Home, browser: Google Chrome 123.0.6312.106
**Reproducible:** always
**Build found:** "commit [c5b942b](https://github.com/ita-social-projects/OoS-Frontend/commit/c5b942b743027995c3f735631d7a6566a70e6216)"

**Preconditions**
1.The site https://oos.dmytrominochkin.cloud/#/ is opened
2. User is registered as SP

**Steps to reproduce**
1. Go to 'Кабінет надавача послуг'
2. Click on 'Мої гуртки'
3. Click on 'Edit workshop' icon
4. Fill in all required fileds in 'Про гурток' section
5. Click on 'Далі' button
6. Repeat steps 4, 5 with  'Опис' section
7. Repeat steps 4, 5 with 'Контакти' section
8. Click on 'Додати ще одного викладача' button
9. Place the cursor in 'Прізвище', 'Ім'я', 'Опис'  fields (don't type any symbols)

**Actual result**
'Це поле є обов'язковим' error message is not displaying under required fields

**Expected result**
'Це поле є обов'язковим' error message appears under all required fields ('Прізвище', 'Ім'я', 'Стать', 'Дата народження', 'Опис' )
'Це поле має містити мінімум одну літеру' notification appears under 'Опис'  field

<img width="472" alt="image" src="https://github.com/ita-social-projects/OoS-Frontend/assets/151456891/bfd45894-a051-40c1-9f8c-9e16296926ff">

<img width="416" alt="image" src="https://github.com/ita-social-projects/OoS-Frontend/assets/151456891/3d6361e9-e619-4039-a9d8-7aefa97fe637">

**Comment by SergeyGSA** [comment]
@SyrvatkaTetiana In our case, we can't show the error message 'Це поле є обов'язковим' under the field 'Стать' because we can show this error message only when user click the button 'Зберегти', but in this form the button 'Зберегти' is disabled until the form become valid. In this form, the red asterisk is placed near the field 'Стать', and I suppose it is enough for user's understanding.
