### ISSUE TITLE
[Selection window] Interaction with the description in any selection window scrolls down whole page/closes selection window

### ISSUE THREAD

**Issue by WVNTICXRV** [ita-social-projects/OoS-Frontend#2487]
**Environment:** Windows 10, 64-bit, Google Chrome 121.0.6167.86.
**Reproducible:** always

**Preconditions**
The site 'Позашкілля' https://oos.dmytrominochkin.cloud/ is opened
The user is logged in as a service provider or parent

**Steps to reproduce**
1. Click on any selection window, like "district select", "Achievement type select", etc.
2. Select any aviable position;
3. Select description of that position;
4. Scroll down while the cursor is on the description text;
5. Select description text

**Expected result**
After scrolling down, window rolls down and other positions are seen, after scrolling down the description of the previous position is closed, next position with the description appeared.

**Actual result**
The main page scrolled down. The district selection window doesn't move, when description text is selected, shuts down the selection window.

**Labels to be added**
"Bug", Priority ("pri: Low"), Severity ("severity: Minor"), Type ("UI").

**Comment by AkunaPatlata** [comment]
#2404
