### ISSUE TITLE
[UI; SP cabinet] No clarification of the "Blocked" status in info tooltip

### ISSUE THREAD

**Issue by OlenaYakubova** [ita-social-projects/OoS-Frontend#2497]
**Environment:** Windows 11, 64 bit
Google Chrome 124.0.6367.61
Reproducible: always.

**Preconditions**
1. Go to https://oos.dmytrominochkin.cloud/
2. Log in as Service provider

**Steps to reproduce**
1. Click on the arrow in right top corner of page
2. Select "Заявки" line from drop down list
3. Click on "i" icon (info-menu) befor "всі гуртки" filter

**Actual result**
There is no clarification of the "Blocked" status in the Application Statuses.
![image](https://github.com/ita-social-projects/OoS-Frontend/assets/73597578/b809c4e1-fc19-47dc-931c-1fa798ec4b2a)

**Expected result**
Clarification of the "Blocked" status is in the Application Statuses in Service Provider cabinet 
Should be "Заблоковано" - "Користувача заблоковано" like:
![image](https://github.com/ita-social-projects/OoS-Frontend/assets/73597578/a00a3b5a-1a09-4908-822a-6f33784cf3e9)

**User story and test case links**
(Figma)[https://www.figma.com/file/YRYP4zAAchOyYMgdoeP782/MoE-%7C-Dev-Team?type=design&node-id=0-1&mode=design&t=Bfz9yxJ5gU6N1TlB-0]

**Labels to be added**
"Bug", Priority ("Low"), Severity ("Low"), Type ("UI").

**Comment by AkunaPatlata** [comment]
@OlenaYakubova I requested access to figma. Now waiting for you to open it to me:)
