### ISSUE TITLE
[Edit User profile] 'Телефон' field accepts more than 9 required numbers

### ISSUE THREAD

**Issue by SyrvatkaTetiana** [ita-social-projects/OoS-Frontend#2523]
**Environment:** Windows 11 Home, browser: Google Chrome 124.0.6367.119
**Reproducible:** Always
**Build found:** "commit [7ca68b4](https://github.com/ita-social-projects/OoS-Frontend/commit/7ca68b403e0201254787bdac233b8ae6ff76ec47)"

**Preconditions**
1. The site https://oos.dmytrominochkin.cloud/#/ is opened
2. User is registered as Parent/SP 
3. 'Кабінет користувача' is opened

**Steps to reproduce**
1. Go to 'Особиста інформація'  
2. Click on 'Редагувати' button
3. Enter more than 9 numbers in  'Телефон' field 

**Actual result**
'Телефон' field accepts more than 9 numbers

**Expected result**
System doesn't allow to enter more than 9 numbers in 'Телефон' field 

<img width="356" alt="image" src="https://github.com/ita-social-projects/OoS-Frontend/assets/151456891/02ff4418-d525-407f-88aa-5a59b10307e5">

**Comment by Kazumen** [comment]
We can't fix this bug, because the number input is international, so we cannot limit the number to only 9 digits.
