### ISSUE TITLE
[Header / Menu] The burger menu, the name of the menu tab, notification indicator are not aligned properly

### ISSUE THREAD

**Issue by OMGaranina** [ita-social-projects/OoS-Frontend#2549]
**Environment:** OS Windows 11Pro Version 23H2, Browser Chrome Version 124.0.6367.119
   Device: iPhone 12 pro
**Reproducible:** always
**Build found:** commit [0333898](https://github.com/ita-social-projects/OoS-Frontend/commit/0333898b24899fd602fec13018d80f9afd47a1b6)

**Preconditions**
1. The site "Позашкілля" https://oos.dmytrominochkin.cloud is opened
2.  User is logged in
3. The user has at least one unread notification

**Steps to reproduce**
1. Click on the burger menu in the header
2. NB! Observe the notification indicator near the "Сповіщення" tab
3. Click on one of the menu tabs, e.g. "Особиста інформація"
4. NB! Observe elements in the header

**Actual result**
1. The notification indicator is shifted down relative to "Сповіщення" tab. The bell icon and the hole "Сповіщення" tab is shifted to the right relative to the other tabs in the menu
![image](https://github.com/ita-social-projects/OoS-Frontend/assets/95030828/219dcbb0-8fbd-44ff-8116-5aa36b065bbc)

2. The arrow button, the tab name, and the burger menu in the header are not aligned
![image](https://github.com/ita-social-projects/OoS-Frontend/assets/95030828/20b103e8-c459-4292-83f5-14d10246c00f)

**Expected result**
The elements "Сповіщення", the notification indicator in the menu, the arrow icon, the tab name, and the burger menu in the header are aligned

**User story and test case links**
https://www.figma.com/design/YRYP4zAAchOyYMgdoeP782/MoE-%7C-Dev-Team?node-id=4832-1327&t=dU6e38hZSMkZ66vR-0

**Comment by Shliakhtych** [comment]
The bug has been fixed.
![image](https://github.com/user-attachments/assets/ef899e09-e13e-416c-8cc2-1601254ddb0c)
![image](https://github.com/user-attachments/assets/2b05a202-9be3-4812-aec5-6b51b9d9349f)
