### ISSUE TITLE
[Workshop page / Application tab] The indents of the paragraphs and the buttons are not even

### ISSUE THREAD

**Issue by OMGaranina** [ita-social-projects/OoS-Frontend#2550]
**Environment:** OS Windows 11Pro Version 23H2, Browser Firefox Version 126.0 / Device: iPhone 12/13+Pro, iOS 14.6
**Reproducible:** always
**Build found:** commit [0333898](https://github.com/ita-social-projects/OoS-Frontend/commit/0333898b24899fd602fec13018d80f9afd47a1b6)

**Preconditions**
1. The site "Позашкілля" https://oos.dmytrominochkin.cloud/ is opened
2. User is logged in as a service provider
3. The service provider has at least one application to the workshop

**Case 1**
**Steps to reproduce**
1. Tap on the burger menu
2. Tap on the "Мої гуртки" tab
4. Tap on the 'Details' button to open the workshop page
5. Observe the schedule section

**Actual result**
The indents between paragraphs are not equal
Note! The same behaviour for desktop and mobile versions. 
![image](https://github.com/ita-social-projects/OoS-Frontend/assets/95030828/0005053e-3502-4124-ac04-1b54e4ee891e)

**Expected result**
The indents between paragraphs are equal
https://www.figma.com/design/YRYP4zAAchOyYMgdoeP782/MoE-%7C-Dev-Team?node-id=8646-5816&t=dU6e38hZSMkZ66vR-0

**Case 2**
1. Tap on the burger menu
2. Tap on the "Заявки" tab
3. Tap on the kebab menu on the application card
4. Tap on the "Заблокувати користувача" button
6. Observe the "Підтвердити", "Скасувати" buttons
7. Close the dialog window
8. Click on the "Відмовити" button on the application card
9.  Observe the "Підтвердити", "Скасувати" buttons

**Actual result**
The "Підтвердити", "Скасувати" buttons are shifted relatively each other
![image](https://github.com/ita-social-projects/OoS-Frontend/assets/95030828/6eddd3f8-b6b2-4921-91bd-a584e67f7697)

![image](https://github.com/ita-social-projects/OoS-Frontend/assets/95030828/ff07d74e-5c0a-461e-a3e5-37d6d9df27ea)

**Expected result**
The "Підтвердити", "Скасувати" buttons are aligned

**User story and test case links**

**Comment by Shliakhtych** [comment]
The bug has been fixed.
![image](https://github.com/user-attachments/assets/c3bc20e1-1662-4e69-9363-c40ae96441ca)
![image](https://github.com/user-attachments/assets/6ee85497-d567-42eb-835b-720fe2de04b4)
![image](https://github.com/user-attachments/assets/5dd2677d-6de2-4985-a362-031abbad5c76)
