### ISSUE TITLE
[Create/Update workshop] The buttons 'Скасувати', 'Зберегти' are shifted to the right in the timepicker window 

### ISSUE THREAD

**Issue by OMGaranina** [ita-social-projects/OoS-Frontend#2571]
**Environment:** OS Windows 11Pro Version 23H2, Browser Chrome Version 125.0.6422.114,
**Device:** iPhone 12 Pro
**Reproducible:** always
**Build found:** commit [b2b405b](https://github.com/ita-social-projects/OoS-Frontend/commit/b2b405b25be2673cff0aaa8a1ddd3b46788ebcdd)

**Preconditions**
1. The site 'Позашкілля' https://oos.dmytrominochkin.cloud/ is opened
2. The user is logged in as a service provider

**Steps to reproduce**
1. Click on the dropdown button near the username in the header
2. Click on the 'Мої гуртки' link
3. Click on the 'Додати гурток' button
4. In the 'Розклад занять' section click on the 'Від' field
5. Observe the placement of the 'Скасувати', 'Зберегти' buttons in the time picker pop up window
6. Click on the 'Скасувати' button
7. Click on the 'До' field in the same section
8. Observe the placement of the 'Скасувати', 'Зберегти' buttons in the time picker pop up window

**Actual result**
The buttons 'Скасувати', 'Зберегти' are shifted to the right. There is no space between the buttons. The scroll bar appears under the buttons.
![image](https://github.com/ita-social-projects/OoS-Frontend/assets/95030828/ac318ea6-3979-4a7e-9404-b4e8d347fff0)

**Expected result**
The buttons are centered. There is space between the buttons. The scroll bar is not displayed.

**User story and test case links**

**Comment by Shliakhtych** [comment]
The bug has been fixed.
![image](https://github.com/user-attachments/assets/f33715ff-fa8a-44fd-9ee4-665428400197)
