### ISSUE TITLE
[Search page] The ‘List’ page doesn’t scroll up after clicking on the ‘Переглянути всі’ button on the Main page.

### ISSUE THREAD

**Issue by oksanakushnir** [ita-social-projects/OoS-Frontend#2573]
**Environment:** Windows 11 Version 22H2, Chrome Version 125.0.6422.142
**Reproducible:** always
**Build found:**  "commit fdcaee0"

**Preconditions**
1.	The site https://oos.dmytrominochkin.cloud/#/ is opened

**Steps to reproduce**
1.	Scroll to the ‘Найпопулярніші гуртки’ section
2.	Click on the ‘Переглянути всі’ button

**Actual result**
The page doesn’t scroll up to the beginning of the section.

https://github.com/ita-social-projects/OoS-Frontend/assets/130609090/5b33ae3b-ee83-4a7b-8d12-fdc2de491016

**Expected result**
The page should be pre-scrolled to the begin.

**User story and test case links**
User story #166

**Labels to be added**
"Bug", Priority ("priority: Low "), Severity ("severity: Minor"), Type ("UI").

**Comment by Shliakhtych** [comment]
The bug has been fixed.
