### ISSUE TITLE
[Edit Workshop Admin] Phone number for Ukraine is saved sucessfully after adding redundant 10th digit

### ISSUE THREAD

**Issue by SyrvatkaTetiana** [ita-social-projects/OoS-Frontend#2578]
**Environment:** Windows 11 Home, browser: Google Chrome 125.0.6422.142
**Reproducible:** Always.
**Build found:**  "commit [5e3f71a](https://github.com/ita-social-projects/OoS-Frontend/commit/5e3f71a75710f389bfb9d0a6a512ad8afa40152b)"

**Preconditions**
1. The site https://oos.dmytrominochkin.cloud/#/ is opened
2. User is registered as SP
3. SP already has registered Admins

**Steps to reproduce**
1. Go to 'Кабінет надавача'
2. Click on 'Адміністрування'
3. Click on kebab menu and choose 'Редагувати користувача'
4. Add the 10th number '0' to Ukraine phone number
5. Click on 'Далі' and 'Зберегти'
6. Click on 'Підтвердити'

**Actual result**
1. "Пошук країни за назвою або кодом телефону" text is cropped in the search field
2. New phone number is saved succesfully

**Expected result**
1. Search field is wide enought for the whole text
2. "Введіть коректний номер телефону" appears red message after one enters '0' as the 10th number

<img width="237" alt="image" src="https://github.com/ita-social-projects/OoS-Frontend/assets/151456891/d427577d-48cf-4566-9058-586527b672ac">

https://github.com/ita-social-projects/OoS-Frontend/assets/151456891/09ab3ae8-fce7-4ce4-9091-c2248e6535b6

**Comment by Kazumen** [comment]
Because there are regional phones that have a possible 10 digits, we can insert another zero
