### ISSUE TITLE
[New workshop application form] The button '+Додати ще дитину' should be disabled if the parent already has 20 children

### ISSUE THREAD

**Issue by OMGaranina** [ita-social-projects/OoS-Frontend#2583]
**Environment:** OS Windows 11Pro Version 23H2, Browser Chrome Version 125.0.6422.114
**Reproducible:** always
**Build found:** commit [5e3f71a](https://github.com/ita-social-projects/OoS-Frontend/commit/5e3f71a75710f389bfb9d0a6a512ad8afa40152b)

**Preconditions**
1. The site 'Позашкілля' https://oos.dmytrominochkin.cloud  is opened
2. The user is logged in as a Parent
3. The parent has 20 registered children

**Steps to reproduce**
1. Click on the 'Детальніше' button on the workshop card
2. Click on the 'Подати заявку' button
3. Hover over the '+Додати ще одну дитину' button
4. Click on the '+Додати ще одну дитину' button

**Actual result**
The '+Додати ще одну дитину' button is active. The arrow cursor changed to the pointer. After clicking on the button the 'Додати дані про дитину' form is opened.

https://github.com/ita-social-projects/OoS-Frontend/assets/95030828/eff40f7d-bc7e-4f32-a26b-d5ad473b0f1e

**Expected result**
The '+Додати ще одну дитину' button is disabled. The arrow cursor is not changing to the pointer. After clicking on the button '+Додати ще одну дитину' any actions are not initiated. Near the '+Додати ще одну дитину' button add an information button 'i'. After clicking on the 'i' button the pop-up message appeared 'Можливо додати не більш, ніж 20 дітей'
<img width="950" alt="більше20" src="https://github.com/ita-social-projects/OoS-Frontend/assets/95030828/b0d7f2ee-19a4-49c3-88ef-002170cea19e">

**User story and test case links**
[User story#1012](https://github.com/ita-social-projects/OoS-Backend/issues/1012)

**Comment by Shliakhtych** [comment]
The bug has been fixed.
![image](https://github.com/user-attachments/assets/7592b388-4840-43a2-b4b5-d5ccfaa3b309)
