### ISSUE TITLE
[Workshop/Images] Image carousel on workshop images

### ISSUE THREAD

**Issue by doliinyk** [ita-social-projects/OoS-Frontend#2599]
**Reproducible:** always
**Build found:** reproducible on develop per 6ac0418

**Preconditions**
Create some workshop.

**Steps to reproduce**
1. Enable images feature or observe it is enabled.
2. Try to add images for workshop.
3. Observe image functionality.

**Actual result**
Carousel is exactly broken on workshop details page.
Images features may not be available.

**Expected result**
Carousel and image features are working.

**Comment by witolDark** [comment]
#2611
