### ISSUE TITLE
[Workshop card] The full workshop title does not appear when hovering over the truncated title

### ISSUE THREAD

**Issue by Shliakhtych** [ita-social-projects/OoS-Frontend#2608]
**Environment:** Windows 11, 64-bit, Google Chrome v.126.0.6478.182.
**Reproducible:** Always.

**Build found:**  a38c809

**Preconditions**

1. Go to https://oos.dmytrominochkin.cloud/;
2. On the main page, there should be a workshop with a truncated title.

**Steps to reproduce**

1. Go to the main page;
2. Find the workshop with the truncated title;
3. Hover over the truncated title;
4. Note the result.

**Actual result**
The full workshop title does not display after hovering over the truncated title due to its excessive length.
![image](https://github.com/user-attachments/assets/be57558d-8ace-41f2-8dae-0b8949d8ad61)
![image](https://github.com/user-attachments/assets/cef203a3-7a69-4f9d-8541-f79b3491072d)

**Expected result**
When hovering over the truncated title, a tooltip with the full name appears.

**Labels to be added**
"Bug", Priority (Priority: Low"), Severity ("Severity: Minor"), Type ("UI").

**Comment by doliinyk** [comment]
https://github.com/ita-social-projects/OoS-Frontend/pull/2548 might break this
