### ISSUE TITLE
[Workshop/Create] Required field missed error message during workshop creation.

### ISSUE THREAD

**Issue by oksanakushnir** [ita-social-projects/OoS-Frontend#2615]
**Environment:** Windows 11 Version 22H2, Chrome Version 125.0.6422.142
**Reproducible:** Always
**Build found:** "commit eddcd03"

**Preconditions**
1.	The site https://oos.dmytrominochkin.cloud/#/ is opened
2.	Provider is registered.

**Steps to reproduce**
1.	Open the provider information.
2.	Click on the “Мої гуртки” tab.
3.	Click on the “Додати гурток” button.
4.	Scroll to the “Розклад занять” section.
5.	Select few days in toggle.
6.	Enter start time, leave end time unfilled.

**Actual result**
The required end time field does not display an error message.
![2024-07-29_14-10-22](https://github.com/user-attachments/assets/18f95cf5-529d-4277-8872-70abd913b153)

**Expected result**
The required end time field should display an error message.

**Labels to be added**
"Bug", Priority ("Medium"), Severity ("Medium"), Type ("Functional")

**Comment by Shliakhtych** [comment]
The bug has been fixed.
![image](https://github.com/user-attachments/assets/9d8de229-2449-43bf-8e97-d49477dc91fe)
