### ISSUE TITLE
[Search] Search filed does not accept Ukrainian і, ї, є

### ISSUE THREAD

**Issue by DmyMi** [ita-social-projects/OoS-Frontend#2652]
Search filed validation counts Ukrainian letters `і, ї, є` as special symbols and does not allow to enter them.

Need to rewrite validation logic (and check other Ukrainian letters)

<img width="637" alt="image" src="https://github.com/user-attachments/assets/da05fcf7-71cb-4326-a636-64738354c7a2">

**Comment by Liuboff** [comment]
Done
