### ISSUE TITLE
Tab styling is broken for some cases

### ISSUE THREAD

**Issue by litvinets** [ita-social-projects/OoS-Frontend#583]
After routing, styling for tabs is broken
![image](https://user-images.githubusercontent.com/27493959/138750319-7ce7d9ab-3174-43f6-80c0-43ef07c4247b.png)
![image](https://user-images.githubusercontent.com/27493959/138750356-db80c7ba-0ac3-49cf-a9bd-fd45eab171ba.png)

**Comment by gmakeev** [comment]
The style of the tabs has been fixed after doing the "Submit Application".
Other risky places in the create-application.component.scss and navigation-tabs.scss files have been wrapped by property ':host ::ng-deep'.
