### ISSUE TITLE
Main Page Style Fix

### ISSUE THREAD

**Issue by litvinets** [ita-social-projects/OoS-Frontend#646]
1. Category cards should be pinned to the left side of the page. 
2. Workshop cards should be pinned to the left side of the page. 
3. Search field should be bigger according to the design.
4. User name should be the same font-size as other navigation titles in header-section,
5. There should be no margin for cards on the left side.
6. For the specific resolution, we have 'almost' one extra row. It should be either removed, or added new workshops there.
![image](https://user-images.githubusercontent.com/27493959/142208260-4b884a64-d9f1-40f6-9595-f6e65d314da5.png)

**Comment by gmakeev** [comment]
Items of Task's list
3. Search field should be bigger according to the design.
4. User name should be the same font-size as other navigation titles in header-section,
have been done.

Other items of list have been added to other tasks.
