### ISSUE TITLE
Registration Page Style Fix

### ISSUE THREAD

**Issue by litvinets** [ita-social-projects/OoS-Frontend#651]
1. Change the font-size of the title according to the design
![image](https://user-images.githubusercontent.com/27493959/142211491-76c06fba-0baf-43e9-9e14-b0eddc0f9ce2.png)
2. Change black color to the one we use in designs
3. Apply the proper font-family

**Comment by dmitryy90** [comment]
Fix eye icon on login page

**Comment by gmakeev** [comment]
Styles of Registration and SignIn pages have been fixed.
