### ISSUE TITLE
[Create workshop] - error If  ` or - char in the address 

### ISSUE THREAD

**Issue by dmitryy90** [ita-social-projects/OoS-Frontend#734]

**Comment by litvinets** [comment]
fix validation for these cases: 
![image](https://user-images.githubusercontent.com/27493959/149139084-737d496f-ba17-4875-a543-e245851ebe56.png)
![image](https://user-images.githubusercontent.com/27493959/149139133-c21718fc-b970-4f6c-bc21-fd2a0c1431e0.png)
![image](https://user-images.githubusercontent.com/27493959/149139305-21369ac7-2279-46c0-a161-f4a6b7e2b3f7.png)

**Comment by chorandrey** [comment]
Merged solution PR https://github.com/ita-social-projects/OoS-Frontend/pull/767
