### ISSUE TITLE
[Registration form] Page is changing localisation, after error in input field.

### ISSUE THREAD

**Issue by ladikdadik** [ita-social-projects/OoS-Frontend#790]
**Environment:** Windows 10 x64(86), Opera GX 82.0.4227.50
**Reproducible:** always
**Build found:** gcp-0.0.49

**Preconditions**
Go to Registration form, pick either user or service provider.
Example : 
![image](https://user-images.githubusercontent.com/97900899/150509359-8e9f3b6a-8ed6-48ab-b2d5-72ca39c58fcf.png)

**Steps to reproduce**
1. Input correct data to all fields except phone (you can use photo as an example)
2. Tick both checkboxes
3. Click on "Registration" button
4. Pay attention to localisation on page

**Actual result**
Localisation of page was changed from Ukrainian to English.

**Expected result**
Localisation of page is not changing after error in input.

**Labels to be added**
"Bug", Priority ("pri: Low"), Severity ("severity: Minor"), Type ("Localisation").

**Attachment**
Page, after error was occured :
![image](https://user-images.githubusercontent.com/97900899/150510154-39b6827a-623c-44f9-a87c-0d0400758511.png)

**Comment by litvinets** [comment]
fixed!
