### ISSUE TITLE
[Personal-cabinet] - OwnershipType info about provider/ edit provider

### ISSUE THREAD

**Issue by litvinets** [ita-social-projects/OoS-Frontend#830]
1)Add ownership type
 ![image](https://user-images.githubusercontent.com/27493959/151576357-0b67eaba-46e0-4495-85f4-d2a0c326ba1c.png)
2) Fix workshop update. When you click to edit, then you should see the ownership type as already selected
![image](https://user-images.githubusercontent.com/27493959/151576508-28d7244d-7741-404b-895c-091c0ccb64f7.png)

**Comment by perepichai** [comment]
This was fixed in my PR which I merged to develop today. Check, please.

**Comment by Olya-web7** [comment]
Sorry, didn't see it was assigned
