### ISSUE TITLE
[Administration] - navigation tab

### ISSUE THREAD

**Issue by litvinets** [ita-social-projects/OoS-Frontend#835]
There are two navigation tabs, so the first one should always highlight the active tab, doesn't matter which tab is selected in the second navigation bar
![image](https://user-images.githubusercontent.com/27493959/151579185-c74c9557-a2d4-4504-a90a-04a34f1da58c.png)
![image](https://user-images.githubusercontent.com/27493959/151579231-ff27d707-127a-4f64-b38d-1f2839aa4e84.png)
![image](https://user-images.githubusercontent.com/27493959/151579262-c6314026-a13d-4c91-ac35-1a929cc96122.png)

**Comment by LeraKornienko** [comment]
done
