### ISSUE TITLE
[Change-email/password] - button "Save" should be in ukraininan

### ISSUE THREAD

**Issue by litvinets** [ita-social-projects/OoS-Frontend#838]
Should translate everything, including button "save"
![image](https://user-images.githubusercontent.com/27493959/151583658-79659c11-ab42-481c-8a42-e8af164be969.png)
![image](https://user-images.githubusercontent.com/27493959/151583790-f62dafcc-e08c-41a5-9fba-8d79aa33311f.png)

**Comment by perepichai** [comment]
It seems to me that this markup comes from the backend.
