### ISSUE TITLE
[Add child] No error messages are displayed when entering invalid data in 'Прізвище', 'Ім'я', 'По-батькові', 'Місце навчання' fields

### ISSUE THREAD

**Issue by AnnaDidiaieva** [ita-social-projects/OoS-Frontend#850]
**Environment:** Windows 10 Corporate LTSC 64-bit, Google Chrome v97.0.4692.99
**Reproducible:** always
**Build found:** Frontend: gcp-0.0.50, Backend: gcp-0.0.101

**Preconditions**
1. Follow link https://oos.dmytrominochkin.cloud/#/
2. Log into system as parent: 'Email'="dub@gmail.com", 'Password'="Qwert1!".
3. Select "Інформація про дитину"  in the menu bar at the top right corner.
4. Click the "Додати дитину" button.

**Steps to reproduce**
1. Set incorrect value (1. Анастасіяанастасіяанастасіяанас; 2. Only spaces) in the 'Прізвище' field.
2. Set incorrect value (1. Анастасіяанастасіяанастасіяанас; 2. Only spaces) in the 'Ім'я' field.
3. Set incorrect value (1. Анастасіяанастасіяанастасіяанас; 2. Only spaces) in the 'По-батькові' field.
4. Set incorrect value (1. Less than 10 characters; 2. More than 256 characters) in the 'Місце навчання (заклад)' field.

**Actual result**
There are no error messages displayed when entering incorrect values in 'Прізвище', 'Ім'я', 'По-батькові', 'Місце навчання (заклад)' fields.
1. Анастасіяанастасіяанастасіяанас
![Длинное имя](https://user-images.githubusercontent.com/97879289/151816615-e9cc1247-4be7-43ab-a236-6040275b082b.jpg)
2. Only spaces
![Пробелы в значениях](https://user-images.githubusercontent.com/97879289/151816627-3deae134-036f-4a37-ab60-7d317bf3107b.jpg)
3. Less than 10 characters in the 'Місце навчання (заклад)' field.
![Заклад](https://user-images.githubusercontent.com/97879289/151822337-b5a98f01-6ca7-4a73-aa33-5af194f794c2.jpg)
4. More than 256 characters in the 'Місце навчання (заклад)' field.
![Заклад1](https://user-images.githubusercontent.com/97879289/151822265-59d85f85-f06f-4948-8fee-3a75c60539cd.jpg)

**Expected result**
The error messages are displayed when entering incorrect values in 'Прізвище', 'Ім'я', 'По-батькові', 'Місце навчання (заклад)' fields.
![cnjh](https://user-images.githubusercontent.com/97879289/151818744-42cff609-7a55-493a-bdce-9e015ce45928.jpg)
![1](https://user-images.githubusercontent.com/97879289/151823682-1fce8dc9-929d-4efb-a399-9d77b8d81efc.jpg)

**User story and test case links**
User story #43
Test case: https://jira.softserve.academy/browse/OS-186

**Labels to be added**
Bug, pri: high, severity: major, functional
.

**Comment by AnnaDidiaieva** [comment]
Always reproducible also while editing child's information

**Comment by AnnaDidiaieva** [comment]
**[Add child] No error messages are displayed when the 'Прізвище', 'Ім'я', 'По-батькові' fields are filled by only spaces**

Environment: Windows 10 Corporate LTSC 64-bit, Google Chrome v97.0.4692.99
Reproducible: always (also while editing child's information)
Build found: Frontend: gcp-0.0.53, Backend: gcp-0.0.106

**Preconditions**
1. Follow link https://oos.dmytrominochkin.cloud/#/
2. Log into system as parent: 'Email'="[dub@gmail.com](mailto:dub@gmail.com)", 'Password'="Qwert1!".
3. Select "Інформація про дитину" in the menu bar at the top right corner.
4. Click the "Додати дитину" button.

**Steps to reproduce**
1. Set incorrect value (Only spaces) in the 'Прізвище' field.
2. Set incorrect value (Only spaces) in the 'Ім'я' field.
3. Set incorrect value (Only spaces) in the 'По-батькові' field.

**Actual result**
There are no error messages displayed when entering incorrect values in 'Прізвище', 'Ім'я', 'По-батькові' fields.
https://user-images.githubusercontent.com/97879289/152987734-967c4ba7-6fc1-4b2c-8d6f-b73e514d81a4.mp4

**Expected result**
The error messages are displayed when entering incorrect values in 'Прізвище', 'Ім'я', 'По-батькові' fields.
![151818744-42cff609-7a55-493a-bdce-9e015ce45928](https://user-images.githubusercontent.com/97879289/152987758-cc3e8823-c266-4a8d-9c3d-44f032d9dc7c.jpg)

**User story and test case links**
User story https://github.com/ita-social-projects/OoS-Frontend/issues/43
Test case: https://jira.softserve.academy/browse/OS-186

**Labels to be added**
Bug, pri: high, severity: major, functional

**Comment by kokole110** [comment]
bug has been fixed, the code is ready to be retested once deployed

**Comment by AnnaDidiaieva** [comment]
Verified
