### ISSUE TITLE
[Add child] The 'Додати ще одну дитину' button stays enabled when mandatory fields are empty

### ISSUE THREAD

**Issue by AnnaDidiaieva** [ita-social-projects/OoS-Frontend#861]
**Environment:** Windows 10 Corporate LTSC 64-bit, Google Chrome v97.0.4692.99
**Reproducible:** always
**Build found:** Frontend: gcp-0.0.50, Backend: gcp-0.0.101

**Preconditions**
1. Follow link https://oos.dmytrominochkin.cloud/#/
2. Log into system as parent: 'Email'="dub@gmail.com", 'Password'="Qwert1!".
3. Select "Інформація про дитину" in the menu bar at the top right corner.
4. Click on the "Додати дитину" button.

**Steps to reproduce**
Take a look at the "Додати ще одну дитину" button,

**Actual result**
The 'Додати ще одну дитину' button is enabled when mandatory fields are empty.
![додати непра](https://user-images.githubusercontent.com/97879289/152010310-05b73077-fe9c-4b65-8ecb-a909ed6df784.jpg)

**Expected result**
The 'Додати ще одну дитину' button should be disabled when mandatory fields are empty.
![додати ще](https://user-images.githubusercontent.com/97879289/152010336-8677fcdf-971e-448f-be6c-8f7a55f1d458.jpg)

**User story and test case links**
User story #43
Test case: https://jira.softserve.academy/browse/OS-190

**Labels to be added**
Bug, pri: medium, severity: major, functional, UI

**Comment by kokole110** [comment]
bug has been fixed
close https://github.com/ita-social-projects/OoS-Frontend/issues/861

**Comment by AnnaDidiaieva** [comment]
Verified
