### ISSUE TITLE
[Add child UI] The 'Скасувати' and 'Зберегти' buttons are not displayed correctly

### ISSUE THREAD

**Issue by AnnaDidiaieva** [ita-social-projects/OoS-Frontend#864]
**Environment:** Windows 10 Corporate LTSC 64-bit, Google Chrome v97.0.4692.99
**Reproducible:** always (also while editing child's information)
**Build found:** Frontend: gcp-0.0.50, Backend: gcp-0.0.101

**Preconditions**
1. Follow link https://oos.dmytrominochkin.cloud/#/
2. Log into system as parent: 'Email'="dub@gmail.com", 'Password'="Qwert1!".
3. Select "Інформація про дитину" in the menu bar at the top right corner.
4. Click on the "Додати дитину" button.

**Steps to reproduce**
Look at the buttons at the bottom of the 'ДОДАТИ ДАНІ ПРО ДИТИНУ' page.

**Actual result**
The 'Скасувати' and 'Зберегти' buttons are not displayed in uppercase letters.
![UI кнопки](https://user-images.githubusercontent.com/97879289/152149800-eb9cb3ac-2bb6-49c6-b0ec-7fd6ff41bc6a.jpg)

**Expected result**
The 'Скасувати' and 'Зберегти' buttons should be displayed in uppercase letters according to the mock-up.
![кнопки есть](https://user-images.githubusercontent.com/97879289/152150578-3667614b-566e-4328-9746-2e082d803638.jpg)

**User story and test case links**
User story #43
Test case: https://jira.softserve.academy/browse/OS-176

**Labels to be added**
Bug, pri: low, severity: minor, UI

**Comment by kokole110** [comment]
bug has been fixed
close https://github.com/ita-social-projects/OoS-Frontend/issues/864

**Comment by AnnaDidiaieva** [comment]
Verified
