### ISSUE TITLE
[Add child UI] The 'Стать' field's radio buttons are not displayed correctly

### ISSUE THREAD

**Issue by AnnaDidiaieva** [ita-social-projects/OoS-Frontend#865]
**Environment:** Windows 10 Corporate LTSC 64-bit, Google Chrome v97.0.4692.99
**Reproducible:** always (also while editing child's information)
**Build found:** Frontend: gcp-0.0.50, Backend: gcp-0.0.101

**Preconditions**
1. Follow link https://oos.dmytrominochkin.cloud/#/
2. Log into system as parent: 'Email'="dub@gmail.com", 'Password'="Qwert1!".
3. Select "Інформація про дитину" in the menu bar at the top right corner.
4. Click on the "Додати дитину" button.

**Steps to reproduce**
Look at the 'Стать' field's radio buttons on the 'ДОДАТИ ДАНІ ПРО ДИТИНУ' page.

**Actual result**
The 'Стать' field's radio button is displayed as a blue circle inside a white circle.
![1314](https://user-images.githubusercontent.com/97879289/152153704-f177ac82-b3c6-4e3e-a4ff-e5dce3f1759d.jpg)

**Expected result**
The 'Стать' field's radio button is displayed as a white circle inside a blue circle.
![Стать как надо](https://user-images.githubusercontent.com/97879289/152153188-347185fd-f673-4f7a-b41d-a3f622ac53ae.jpg)

**User story and test case links**
User story #43
Test case: https://jira.softserve.academy/browse/OS-176

**Labels to be added**
Bug, pri: low, severity: minor, UI

**Comment by kokole110** [comment]
bug has been fixed
close https://github.com/ita-social-projects/OoS-Frontend/issues/865

**Comment by AnnaDidiaieva** [comment]
Verified
