### ISSUE TITLE
[Add child UI] Incorrect indents on the 'ДОДАТИ ДАНІ ПРО ДИТИНУ' page

### ISSUE THREAD

**Issue by AnnaDidiaieva** [ita-social-projects/OoS-Frontend#866]
**Environment:** Windows 10 Corporate LTSC 64-bit, Google Chrome v97.0.4692.99
**Reproducible:** always
**Build found:** Frontend: gcp-0.0.50, Backend: gcp-0.0.101

**Preconditions**
1. Follow link https://oos.dmytrominochkin.cloud/#/
2. Log into system as parent: 'Email'="dub@gmail.com", 'Password'="Qwert1!".
3. Select "Інформація про дитину" in the menu bar at the top right corner.
4. Click on the "Додати дитину" button.

**Steps to reproduce**
Look at the indents before 'Стать' text and around 'Додати ще одну дитину' button on the 'ДОДАТИ ДАНІ ПРО ДИТИНУ' page.

**Actual result**
There are no indents before 'Стать' text and around 'Додати ще одну дитину' button on the 'ДОДАТИ ДАНІ ПРО ДИТИНУ' page.
![расстояние](https://user-images.githubusercontent.com/97879289/152155758-6adcb1a9-c8ef-4b2a-8b69-ff6f3862ac02.jpg)
No indents before 'Стать' text are also reproducible while editing child's information.

**Expected result**
There should be indents before 'Стать' text and around 'Додати ще одну дитину' button on the 'ДОДАТИ ДАНІ ПРО ДИТИНУ' page according to the mock-up.
![расстояние как надо](https://user-images.githubusercontent.com/97879289/152155751-b1a5ef8f-b535-4559-8a3c-c8e9065b98a7.jpg)

**User story and test case links**
User story #43
Test case: https://jira.softserve.academy/browse/OS-176

**Labels to be added**
Bug, pri: very low, severity: trivial, UI

**Comment by kokole110** [comment]
bug has been fixed
close https://github.com/ita-social-projects/OoS-Frontend/issues/866

**Comment by AnnaDidiaieva** [comment]
Verified
