### ISSUE TITLE
[Edit child UI] Unnecessary text at the top of the 'РЕДАГУВАТИ ДАНІ ПРО ДИТИНУ' page

### ISSUE THREAD

**Issue by AnnaDidiaieva** [ita-social-projects/OoS-Frontend#867]
**Environment:** Windows 10 Corporate LTSC 64-bit, Google Chrome v97.0.4692.99
**Reproducible:** always
**Build found:** Frontend: gcp-0.0.50, Backend: gcp-0.0.101

**Preconditions**
1. Follow link https://oos.dmytrominochkin.cloud/#/
2. Log into system as parent: 'Email'="dub@gmail.com", 'Password'="Qwert1!".
3. Select "Інформація про дитину" in the menu bar at the top right corner. At least 1 child must be created.
4. Click on the "Pen" button of the created child.

**Steps to reproduce**
Look at the top of the 'РЕДАГУВАТИ ДАНІ ПРО ДИТИНУ' page.

**Actual result**
The 'РЕДАГУВАТИ ДАНІ ПРО ДИТИНУ' page has unnecessary text.
![q42](https://user-images.githubusercontent.com/97879289/152158105-be62da9c-bf4a-4d59-9365-a8e732249f44.jpg)

**Expected result**
The 'РЕДАГУВАТИ ДАНІ ПРО ДИТИНУ' page shouldn't have any extra text according to the mock-up.
![123](https://user-images.githubusercontent.com/97879289/152158089-0f5d8669-920d-488e-b496-d216d08f4b71.jpg)

**User story and test case links**
User story #43
Test case: https://jira.softserve.academy/browse/OS-177

**Labels to be added**
Bug, pri: low, severity: minor, UI

**Comment by kokole110** [comment]
bug has been fixed
close https://github.com/ita-social-projects/OoS-Frontend/issues/867

**Comment by AnnaDidiaieva** [comment]
Verified
