### ISSUE TITLE
[Add child UI] Error messages contain spelling mistakes

### ISSUE THREAD

**Issue by AnnaDidiaieva** [ita-social-projects/OoS-Frontend#868]
**Environment:** Windows 10 Corporate LTSC 64-bit, Google Chrome v97.0.4692.99
**Reproducible:** always (also while editing child's information and in the 'Ім'я', 'По-батькові' fields)
**Build found:** Frontend: gcp-0.0.50, Backend: gcp-0.0.101

**Preconditions**
1. Follow link https://oos.dmytrominochkin.cloud/#/
2. Log into system as parent: 'Email'="dub@gmail.com", 'Password'="Qwert1!".
3. Select "Інформація про дитину" in the menu bar at the top right corner.
4. Click on the "Додати дитину" button.

**Steps to reproduce**

1. Set invalid data "111" in the 'Прізвище' field.
2. Сlick on the empty space outside the 'Прізвище' field.
3. Look at the error message after 'Прізвище' field. 

**Actual result**
The error message contains spelling mistakes.
![Орфография](https://user-images.githubusercontent.com/97879289/152160440-490d349f-ed4f-44b2-91da-99e921e0b83a.jpg)

**Expected result**
The error message should not contain spelling mistakes and have to be displayed as "Перевірте введені **дані**. Використовуйте**, будь ласка,** тільки кирилицю та символи ( ' - ) ".
![213](https://user-images.githubusercontent.com/97879289/152160433-c2f004e9-f395-41dd-b503-04d04499b76c.jpg)
Note: the user story #213 also has these spelling mistakes.

**User story and test case links**
User story #43, #213
Test case: https://jira.softserve.academy/browse/OS-176

**Labels to be added**
Bug, pri: very low, severity: trivial, UI

**Comment by kokole110** [comment]
bug has been fixed
close https://github.com/ita-social-projects/OoS-Frontend/issues/868

**Comment by AnnaDidiaieva** [comment]
Verified
