### ISSUE TITLE
[Add child UI] The footer is absent on the page when the browser window is resized

### ISSUE THREAD

**Issue by AnnaDidiaieva** [ita-social-projects/OoS-Frontend#870]
**Environment:**  Windows 10 Corporate LTSC 64-bit, Google Chrome v97.0.4692.99
**Reproducible:** always (also while editing child's information and in the Parent Cabinet)
**Build found:** Frontend: gcp-0.0.50, Backend: gcp-0.0.101

**Preconditions**
1. Follow link https://oos.dmytrominochkin.cloud/#/
2. Log into system as parent: 'Email'="dub@gmail.com", 'Password'="Qwert1!".
3. Select "Інформація про дитину" in the menu bar at the top right corner.
4. Click on the "Додати дитину" button.

**Steps to reproduce**
1. Resize the browser window to 200%.
2. Scroll to the bottom of the 'ДОДАТИ ДАНІ ПРО ДИТИНУ' page to the footer.

**Actual result**
The footer is absent on the 'ДОДАТИ ДАНІ ПРО ДИТИНУ' page when the browser window is resized to 200%.
https://user-images.githubusercontent.com/97879289/152213152-6089e07a-1c0f-458e-a920-fd41c98019ce.mp4

**Expected result**
The footer is displayed at the 'ДОДАТИ ДАНІ ПРО ДИТИНУ' page. 
![aenth](https://user-images.githubusercontent.com/97879289/152213191-0a1d66b5-4427-433c-b79d-6602810cf7ac.jpg)

**User story and test case links**
User story #43
Test case: https://jira.softserve.academy/browse/OS-176

**Labels to be added**
Bug, pri: medium, severity: major, UI

**Comment by kokole110** [comment]
bug has been fixed

**Comment by AnnaDidiaieva** [comment]
Verified
