### ISSUE TITLE
[Log in] The ‘Відновити пароль’ page does not meet the design

### ISSUE THREAD

**Issue by hanna-lenko** [ita-social-projects/OoS-Frontend#891]
**Environment:** Win10 v21H2 64-bit, Firefox v 97.0
**Reproducible:** always
**Build found:** frontend: gcp-0.0.53, backend: gcp-0.0.112

**Preconditions**
- Go to OoS (https://oos.dmytrominochkin.cloud/#/)
- Click on the ‘Увійти/Зареєструватися’ button

**Steps to reproduce**
Click on ‘Забули пароль?’ button

**Actual result**
A user is redirected to the page ‘Відновити пароль’ with English and Ukrainian names of the fields and buttons, no footer and header are displayed
![image](https://user-images.githubusercontent.com/97878413/153585880-fe75ca0e-1caf-4c2f-a9e4-2bd74b4dd9b8.png)

**Expected result**
A user is redirected to the page ‘Відновити пароль’ that meets the design
https://www.figma.com/file/YRYP4zAAchOyYMgdoeP782/MoE-%7C-Dev-Team?node-id=4006%3A722 
Note: there is a typo on the design – instead ‘Відновити паролю’ it shall be ‘Відновити пароль’

**User story and test case links**
User story [#313](https://github.com/ita-social-projects/OoS-Backend/issues/313 )
User story [#45](https://github.com/ita-social-projects/OoS-Backend/issues/45 )
Test case [OS-299](https://jira.softserve.academy/browse/OS-299 )

**Labels to be added**
"Bug", "pri: medium", "severity:minor"), Type "UI"

**Comment by hanna-lenko** [comment]
@Olya-web7 The text is inconsistent with the design (highlighted on the screen below), could you please fix

![image](https://user-images.githubusercontent.com/97878413/154985904-7bd18654-87df-4ec1-be22-a0769b329a60.png)

**Comment by Olya-web7** [comment]
![image](https://user-images.githubusercontent.com/79056080/162935692-2c99edd7-f7b9-453c-86a7-155218d9e2d1.png)

**Comment by hanna-lenko** [comment]
Verified and closed
