### ISSUE TITLE
Only 8 children's cards can fit per page

### ISSUE THREAD

**Issue by OksanaGuz** [ita-social-projects/OoS-Frontend#893]
**Environment:** macOS Big Sur 11.5.1, Chrome version 97.0.4692.71.
**Reproducible:** always
**Build found:** l[gcp-0.0.112](https://github.com/ita-social-projects/OoS-Backend/releases/tag/gcp-0.0.112)
[gcp-0.0.53](https://github.com/ita-social-projects/OoS-Frontend/releases/tag/gcp-0.0.53)

**Preconditions**

1. Open link https://oos.dmytrominochkin.cloud/#
2. Log in like a Parent role (for exp.: [vladshkrebtan@gmail.com](mailto:vladshkrebtan@gmail.com), password : Shkrebtan1!)
3. Go to "Інформація про дитину" point in to "Особиста інформація" menu.
4. More than 8 children exist in the Parent account

**Steps to reproduce**
1.  Pay attention to the number of cards that can fit on the page

**Actual result**
Only 8 cards can fit on the page

https://user-images.githubusercontent.com/97882565/153593051-45b00146-ace6-4d4d-802f-87e0ff826066.mov

**Expected result**
The number of cards as much as the screen can afford

**Labels to be added**
"Bug", Priority ("pri: medium"), Severity ("severity:minor"), Type ("UI")

**Comment by OksanaGuz** [comment]
@Olya-web7 Bug is still reproducible

https://user-images.githubusercontent.com/97882565/154951324-9eb66637-22f3-47c3-aa0f-3d258fc97110.mov

**Comment by Olya-web7** [comment]
![Позашкілля - Google Chrome](https://user-images.githubusercontent.com/79056080/160815808-52d29df5-90b6-4b3a-8184-1b25755a36fd.jpg)
please check, now number of cards as much as the screen can afford

**Comment by OksanaGuz** [comment]
@Olya-web7 
I have a screen width of 1400 pixels.
With zoom 100% + hard reload - 3 cards are placed in a row, 8 cards are shown on the page in total.

https://user-images.githubusercontent.com/97882565/160845886-80ed3bb3-b46c-4f66-a68a-ee24b6c1b8d5.mov

With zoom 75% + hard reload - 5 cards fit in a row, 10 cards are shown on the page in total.
<img width="1250" alt="Снимок экрана 2022-03-30 в 16 18 16" src="https://user-images.githubusercontent.com/97882565/160845923-b30dc6ee-945d-40f7-bb11-794452824e01.png">

With zoom 67% + hard reload - 5 cards are placed in a row, 12 cards are shown on the page in total.
<img width="1127" alt="Снимок экрана 2022-03-30 в 16 20 19" src="https://user-images.githubusercontent.com/97882565/160846001-583bb9a7-c1e1-470d-889c-9030916a40ee.png">

With zoom 50% + hard reload - 8 cards fit in a row, a total of 16 cards are shown on the page.
<img width="1366" alt="Снимок экрана 2022-03-30 в 16 23 05" src="https://user-images.githubusercontent.com/97882565/160846073-502f475a-548c-4df2-b9a4-bcb3019d4ad5.png">

**Comment by LeraKornienko** [comment]
It was discussed with BA, that workshops, child, directions should not change dynamically on screen resizing. It Was decided to create a drop-down, where user can choose amount of cards on the page, that is comfortable for his/her screen size. Please check functionality jf this new feature.
https://github.com/ita-social-projects/OoS-Frontend/issues/1115

**Comment by litvinets** [comment]
![image](https://user-images.githubusercontent.com/27493959/171738295-8bcf1daa-3ed1-4a5b-896d-3a09b16b51ed.png)

**Comment by litvinets** [comment]
![image](https://user-images.githubusercontent.com/27493959/171738354-34d39790-9ca2-4906-81e1-07e57285488c.png)

**Comment by OksanaGuz** [comment]
Verified.
