### ISSUE TITLE
['Редагування закладу' page] 'Область', 'Місто', 'Район' fields are not displayed correctly

### ISSUE THREAD

**Issue by AnnaDidiaieva** [ita-social-projects/OoS-Frontend#899]
**Environment:** Windows 10 Corporate LTSC 64-bit, Google Chrome v98.0.4758.82
**Reproducible:** always
**Build found:** Frontend: gcp-0.0.53, Backend: gcp-0.0.112

**Preconditions**
1. Follow link https://oos.dmytrominochkin.cloud/#/
2. Log into system as a SP (e.g. 'email'="[tester2@gmail.com](mailto:tester2@gmail.com)", 'Password'="1qaz@WSX").
3. Select 'Інформація про заклад' in the menu bar at the top right corner.
4. Click on the 'Редагувати' button in the 'Контакти' section of the 'ІНФОРМАЦІЯ ПРО ЗАКЛАД' tab.

**Steps to reproduce**
1. Look at the 'Область', 'Місто', 'Район' fields in the 'Юридична адреса' section.
2. Look at the 'Область', 'Місто', 'Район' fields in the 'Фактична адреса' section.

**Actual result**
1) The 'Область', 'Місто', 'Район' fields in the 'Юридична адреса' section are not displayed as drop-down boxes.
![дропов нет 1](https://user-images.githubusercontent.com/97879289/153625385-a3999fa3-7d12-466b-8357-a40658bbda1e.jpg)
2) The 'Область', 'Місто', 'Район' fields in the 'Фактична адреса' section are not displayed as drop-down boxes.
![дропов нет 2](https://user-images.githubusercontent.com/97879289/153625392-cf26b953-a7cc-494d-99ed-1ced3af21f8b.jpg)

**Expected result**
1) The 'Область', 'Місто', 'Район' fields in the 'Юридична адреса' section have to be displayed as drop-down boxes.
![дропдауны](https://user-images.githubusercontent.com/97879289/153625411-9a1acdfd-a49d-491e-af79-2929b2385205.jpg)
2) The 'Область', 'Місто', 'Район' fields in the 'Фактична адреса' section have to be displayed as drop-down boxes.
![фактичные дропбоксы](https://user-images.githubusercontent.com/97879289/153625426-17e1d3d3-241e-4cf3-bf02-3385f82c86d7.jpg)

**User story and test case links**
User story https://github.com/ita-social-projects/OoS-Backend/issues/312
Test case: [OS-284](https://jira.softserve.academy/browse/OS-284)

**Labels to be added**
Bug, pri: medium, severity: minor, UI

**Comment by litvinets** [comment]
@perepichai  add only autocomplete dropdown to **city field**, the rest leave as it is

**Comment by litvinets** [comment]
@AnnaDidiaieva currently only autocomplete for city field is available.
Verify it, please. When the development of others autocomplete (for street, region etc) will be available let's create new task
