### ISSUE TITLE
['Редагування закладу' page] 'Тип закладу' drop-down box is not displayed

### ISSUE THREAD

**Issue by AnnaDidiaieva** [ita-social-projects/OoS-Frontend#901]
**Environment:** Windows 10 Corporate LTSC 64-bit, Google Chrome v98.0.4758.82
**Reproducible:** always
**Build found:** Frontend: gcp-0.0.53, Backend: gcp-0.0.112

**Preconditions**
1. Follow link https://oos.dmytrominochkin.cloud/#/
2. Log into system as a SP (e.g. 'email'="[tester2@gmail.com](mailto:tester2@gmail.com)", 'Password'="1qaz@WSX").
3. Select 'Інформація про заклад' in the menu bar at the top right corner.
4. Click on the 'Редагувати' button in the 'Опис' section of the 'ІНФОРМАЦІЯ ПРО ЗАКЛАД' tab.

**Steps to reproduce**
Look at the 'Опис' section of the 'Редагування закладу' page.

**Actual result**
'Тип закладу' drop-down box is not displayed at the 'Опис' section of the 'Редагування закладу' page.
![ФФ](https://user-images.githubusercontent.com/97879289/153637132-80472fe0-61e1-4797-9f23-5c2a1d4153a1.jpg)

**Expected result**
'Тип закладу' drop-down box is displayed at the 'Опис' section of the 'Редагування закладу' page.
![ФФФ](https://user-images.githubusercontent.com/97879289/153637153-c46614dd-f4d8-4756-b040-55f1df6f668d.jpg)
![тип какие есть](https://user-images.githubusercontent.com/97879289/153635233-f578cee3-24b5-42aa-b3fc-1426f8ec4e66.jpg)

**User story and test case links**
User story [OS-263](https://jira.softserve.academy/browse/OS-263)
Test case: [OS-285](https://jira.softserve.academy/browse/OS-285)

**Labels to be added**
Bug, pri: medium, severity: major, UI

**Comment by litvinets** [comment]
fixed

**Comment by AnnaDidiaieva** [comment]
Verified
