### ISSUE TITLE
['Редагування закладу' page] Incorrect validation of the 'ІПН' field with correct data

### ISSUE THREAD

**Issue by AnnaDidiaieva** [ita-social-projects/OoS-Frontend#903]
**Environment:** Windows 10 Corporate LTSC 64-bit, Google Chrome v98.0.4758.82
**Reproducible:** always
**Build found:** Frontend: gcp-0.0.53, Backend: gcp-0.0.112

**Preconditions**
1. Follow link https://oos.dmytrominochkin.cloud/#/
2. Log into system as a SP (e.g. 'email'="[tester2@gmail.com](mailto:tester2@gmail.com)", 'Password'="1qaz@WSX").
3. Select 'Інформація про заклад' in the menu bar at the top right corner.
4. Click on the 'Редагувати' button of the 'ІНФОРМАЦІЯ ПРО ЗАКЛАД' tab.

**Steps to reproduce**
Set valid data (АН637898000) in the 'ІПН' field.

**Actual result**
'ІПН' field is not filled with the set value. Red color error message "Введіть 10 цифр з ІПН.
У випадку внесення паспортних даних введіть 2 перші букви кирилиці та 6 цифр або 9 цифр" is displayed.
![инн баг](https://user-images.githubusercontent.com/97879289/153643239-d084750c-5cfe-4399-aedc-3fac9978022c.jpg)

**Expected result**
'ІПН' field is filled with the set value. 
![инн ка](https://user-images.githubusercontent.com/97879289/153643253-e873f531-283d-400b-8cc6-dd63d12e8635.jpg)

**User story and test case links**
User story https://github.com/ita-social-projects/OoS-Backend/issues/213
Test case: [OS-280](https://jira.softserve.academy/browse/OS-280)

**Labels to be added**
Bug, pri: high, severity: major, functional

**Comment by AnnaDidiaieva** [comment]
@Olya-web7 
Reproducible: always
Test data: АН637898000
The data is valid because there are 2 alphabetic and 9 numeric characters.
Please check the 'ІПН' field validation.

**Comment by AnnaDidiaieva** [comment]
Verified

**Comment by AnnaDidiaieva** [comment]
@Olya-web7 

**Environment:** Windows 10 Corporate LTSC 64-bit, Google Chrome v99.0.4844.74
**Reproducible:** always
**Build found:** Frontend: gcp-0.0.56, Backend: gcp-0.0.120

**Preconditions**
1. Follow link https://oos.dmytrominochkin.cloud/#/
2. Log into system as a SP (e.g. 'email'="tester2@gmail.com, 'Password'="1qaz@WSX").
3. Select 'Інформація про заклад' in the menu bar at the top right corner.
4. Click on the 'Редагувати' button of the 'ІНФОРМАЦІЯ ПРО ЗАКЛАД' tab.

**Steps to reproduce**
Set valid data (QzАи 63780mФ00 №` '-) in the 'ІПН' field.

**Actual result**
'ІПН' field is not filled with the set value. Red color error message "Перевірте введені дані. Використовуйте, будь ласка, тільки кирилицю та символи ( ' - )" is displayed.
![1](https://user-images.githubusercontent.com/97879289/159481408-a6b5716b-af8b-49d4-8b2e-b540e5853c0f.jpg)

**Expected result**
'ІПН' field is filled with the set value.
![12](https://user-images.githubusercontent.com/97879289/159481480-7d927c6f-21df-43ee-acd7-161bedffcea2.jpg)

**User story and test case links**
**User story** https://github.com/ita-social-projects/OoS-Backend/issues/213
**Test case**: [OS-280](https://jira.softserve.academy/browse/OS-280)

**Labels to be added**
Bug, pri: high, severity: major, functional

**Comment by Olya-web7** [comment]
checked, it is working
![image](https://user-images.githubusercontent.com/79056080/163377363-eba1cbdc-660a-4d21-bb68-8d4e2c7cc7f4.png)

**Comment by AnnaDidiaieva** [comment]
Verified
