### ISSUE TITLE
['Інформація про заклад' section] Spelling mistake exists in the name of the field

### ISSUE THREAD

**Issue by AnnaDidiaieva** [ita-social-projects/OoS-Frontend#904]
**Environment:** Windows 10 Corporate LTSC 64-bit, Google Chrome v98.0.4758.82
**Reproducible:** always (also on the 'Редагування закладу' page)
**Build found:** Frontend: gcp-0.0.53, Backend: gcp-0.0.112

**Preconditions**
1. Follow link https://oos.dmytrominochkin.cloud/#/
2. Log into system as a SP (e.g. 'email'="[tester2@gmail.com](mailto:tester2@gmail.com)", 'Password'="1qaz@WSX").
3. Select 'Інформація про заклад' in the menu bar at the top right corner.

**Steps to reproduce**
Look at the 'Інформація про заклад' section.

**Actual result**
'Форма власності' field contains spelling mistake.
![орф1](https://user-images.githubusercontent.com/97879289/153648118-bdd9b953-f7b4-4860-9493-66314e85a94a.jpg)

**Expected result**
'Форма власності' field should not contain spelling mistakes.
![орф1а](https://user-images.githubusercontent.com/97879289/153648145-1c8a6864-dcfc-43e0-9d5b-0a9dbb597c39.jpg)

**User story and test case links**
User story https://github.com/ita-social-projects/OoS-Backend/issues/236
Test case: [OS-276](https://jira.softserve.academy/browse/OS-276)

**Labels to be added**
Bug, pri: very low, severity: trivial, UI

**Comment by AnnaDidiaieva** [comment]
@Olya-web7
Reproducible: always

**Actual result**
![1](https://user-images.githubusercontent.com/97879289/159482612-211abe51-155c-4ab3-95bd-24e0ae424f53.jpg)

**Expected result**
![12](https://user-images.githubusercontent.com/97879289/159482689-c6de98da-2071-4f3a-a76d-d0d2146e410d.jpg)

Please check the spelling of the word 'власності'.

**Comment by litvinets** [comment]
fixed

**Comment by AnnaDidiaieva** [comment]
Verified
