### ISSUE TITLE
['Редагування закладу' page] Incorrect behavior is displayed when entering invalid data in the 'ПІБ керівника', 'Засновник' fields

### ISSUE THREAD

**Issue by AnnaDidiaieva** [ita-social-projects/OoS-Frontend#907]
**Environment:** Windows 10 Corporate LTSC 64-bit, Google Chrome v98.0.4758.82
**Reproducible:** always
**Build found:** Frontend: gcp-0.0.53, Backend: gcp-0.0.112

**Preconditions**
1. Follow link https://oos.dmytrominochkin.cloud/#/
2. Log into system as a SP (e.g. 'email'="[tester2@gmail.com](mailto:tester2@gmail.com)", 'Password'="1qaz@WSX").
3. Select 'Інформація про заклад' in the menu bar at the top right corner.
4. Click on the 'Редагувати' button of the 'ІНФОРМАЦІЯ ПРО ЗАКЛАД' tab.

**Steps to reproduce**
1. Set invalid data (1. More than 50 Cyrillic symbols; 2. Only spaces) in the 'ПІБ керівника' field.
2. Set invalid data (1. More than 30 Cyrillic symbols; 2. Only spaces) in the 'Засновник' field.

**Actual result**
There is no error message displayed when entering invalid data in the 'ПІБ керівника' field.
![кер ерор1](https://user-images.githubusercontent.com/97879289/153666086-0c918256-a4c2-4f56-b8ae-db19d1d4be84.jpg)
![кер ерор2](https://user-images.githubusercontent.com/97879289/153666089-9b54c107-c7f9-4b5e-b162-2031efb854f5.jpg)
There is no error message displayed when entering invalid data in the 'Засновник' field.
![засно ерор1](https://user-images.githubusercontent.com/97879289/153666097-6859d75b-c948-48e2-b986-f9e3e8a62f0d.jpg)
![засн ерор2](https://user-images.githubusercontent.com/97879289/153666128-0db75fd9-4993-4207-a095-02a7c58c12e9.jpg)

**Expected result**
The red color error message "Перевірте введені дані. Використовуйте, будь ласка, тільки кирилицю та символи ( ' - )" is displayed.
![11](https://user-images.githubusercontent.com/97879289/153666389-04a7456d-8739-4a04-bb65-b0b89edcfcc5.jpg)
![22](https://user-images.githubusercontent.com/97879289/153666396-96431be7-b805-4f57-b030-25e69cc5cec4.jpg)
![33](https://user-images.githubusercontent.com/97879289/153666490-82bf6f06-bd1d-42bb-af83-d5a2f9af2f44.jpg)

**User story and test case links**
User story https://github.com/ita-social-projects/OoS-Backend/issues/213
Test case: [OS-291](https://jira.softserve.academy/browse/OS-291)

**Labels to be added**
Bug, pri: medium, severity: minor, functional

**Comment by AnnaDidiaieva** [comment]
@Olya-web7
Reproducible: always
Test data: Only spaces
The data is invalid. Please check the 'ПІБ керівника' and 'Засновник' fields validation.

**Comment by Olya-web7** [comment]
![image](https://user-images.githubusercontent.com/79056080/161226013-e1576129-3eed-42ed-9c74-1568f2e46c1d.png)

**Comment by AnnaDidiaieva** [comment]
Verified
