### ISSUE TITLE
['Інформація про заклад' tab] Incorrect indents are displayed

### ISSUE THREAD

**Issue by AnnaDidiaieva** [ita-social-projects/OoS-Frontend#909]
**Environment:** Windows 10 Corporate LTSC 64-bit, Google Chrome v98.0.4758.82
**Reproducible:** always (also on 'Редагування закладу' pages)
**Build found:** Frontend: gcp-0.0.53, Backend: gcp-0.0.112

**Preconditions**
1. Follow link https://oos.dmytrominochkin.cloud/#/
2. Log into system as a SP (e.g. 'email'="[tester2@gmail.com](mailto:tester2@gmail.com)", 'Password'="1qaz@WSX").
3. Select 'Інформація про заклад' in the menu bar at the top right corner.

**Steps to reproduce**
1. Look at the indent before 'Форма власності' text in 'Інформація про заклад' section.
2. Look at the indents around 'Юридична адреса', after '128A-' and 'Фактична адреса' texts in 'Контакти' section.
3. Look at the indent before 'Статус' text in 'Опис' section.

**Actual result**
1. There is no indent before 'Форма власності' text in 'Інформація про заклад' section.
![отступ1](https://user-images.githubusercontent.com/97879289/153727097-d2037cbd-3618-4fb6-a84d-1c96a11e862d.jpg)
2. There are no indents around 'Юридична адреса', after '128A-' and 'Фактична адреса' texts in 'Контакти' section.
![отступ2](https://user-images.githubusercontent.com/97879289/153727100-c55960f8-b376-426a-a517-be2d78f44ee1.jpg)
3. There is no indent before 'Статус' text in 'Опис' section.
![отступ3](https://user-images.githubusercontent.com/97879289/153727106-18219cc1-0bf0-4920-b640-168e46ae2542.jpg)

**Expected result**
1. There should be indent before 'Форма власності' text in 'Інформація про заклад' section according to the mock-up.
![отступ1а](https://user-images.githubusercontent.com/97879289/153727111-af978c27-f6a4-4483-a424-d03394f96e81.jpg)
2. There should be indents around 'Юридична адреса', after '128A-' and 'Фактична адреса' texts in 'Контакти' section  according to the mock-up.
![отступ2а](https://user-images.githubusercontent.com/97879289/153727113-853cc653-5f52-4fda-9df1-0285ac9f3456.jpg)
3. There should be indent before 'Статус' text in 'Опис' section according to the mock-up.
![отступ3а](https://user-images.githubusercontent.com/97879289/153727115-5316fc01-cefa-4141-9a5e-3564818a2dc3.jpg)
The photo block is hidden at the moment. 'Тип закладу' field is not implemented for now.

**User story and test case links**
User story https://github.com/ita-social-projects/OoS-Backend/issues/312
Test case: [OS-276](https://jira.softserve.academy/browse/OS-276)

**Labels to be added**
Bug, pri: very low, severity: trivial, UI

**Comment by litvinets** [comment]
fixed

**Comment by AnnaDidiaieva** [comment]
Verified
