### ISSUE TITLE
[Search field] The previously entered search results are not displayed in the ‘Search’ field

### ISSUE THREAD

**Issue by hanna-lenko** [ita-social-projects/OoS-Frontend#912]
**Environment:** Win10 v21H2 64-bit, Chrome v 98.0.4758.82
**Reproducible:** always
**Build found:** frontend: gcp-0.0.53, backend: gcp-0.0.112

**Preconditions**
- Go to OoS (https://oos.dmytrominochkin.cloud/#/)
- Log into system (e.g. 'Email'="dub@gmail.com", 'Password'="Qwert1!")
- Do the search with 5-10 words (e.g. "гопак", "танці", "гурток" "курси", "спорт", “фізика”) 

**Steps to reproduce**
1. Click on the ‘Search’ field

**Actual result**
The ‘Search’ field contains a placeholder with a grey-colored text: “Введіть назву або тип гуртка”, no previously entered search results are displayed

**Expected result**
By clicking on the ‘Search’ field, the previously entered search results (5-10) are displayed

**User story and test case links**
User stories [#23](https://github.com/ita-social-projects/OoS-Backend/issues/23), [#213](https://github.com/ita-social-projects/OoS-Backend/issues/213)
Test case [OS-265](https://jira.softserve.academy/browse/OS-265)

**Labels to be added**
"Bug", "pri: low", "severity: minor", Type "Functional"

**Comment by litvinets** [comment]
fixed

**Comment by litvinets** [comment]
save previous search results in local/session storage

**Comment by litvinets** [comment]
fixed!

**Comment by litvinets** [comment]
fixed
