### ISSUE TITLE
[Search field] No error message displayed when entering invalid data into the ‘Search’ field

### ISSUE THREAD

**Issue by hanna-lenko** [ita-social-projects/OoS-Frontend#916]
**Environment:** Win10 v21H2 64-bit, Chrome v 98.0.4758.82
**Reproducible:** always
**Build found:** frontend: gcp-0.0.53, backend: gcp-0.0.112

**Preconditions**
- Follow link https://oos.dmytrominochkin.cloud/#/
- Log into system as parent: 'Email'="dub@gmail.com", 'Password'="Qwert1!".
- "Київ" region is selected

**Steps to reproduce**
1. Set invalid data into the search field:
- one char (‘ь’)
- two chars (‘as’)
- only spaces
- special not-allowed chars (‘@#*&%$’)

2. Click the ‘Search’ button

**Actual result**
The search is performed, no error message displayed

![image](https://user-images.githubusercontent.com/97878413/153849725-de8e7df0-c6d1-489f-a247-20780d7991a0.png)

**Expected result**
"Перевірте введені дані" error message is displayed

**User story and test case links**
User stories [#23](https://github.com/ita-social-projects/OoS-Backend/issues/23), [#213](https://github.com/ita-social-projects/OoS-Backend/issues/213)
Test case [OS-264](https://jira.softserve.academy/browse/OS-264)

**Labels to be added**
"Bug", "pri: medium", "severity: minor", Type "Functional"

**Comment by litvinets** [comment]
It was discussed with BA that it is not relevant anymore
