### ISSUE TITLE
['Опис' section] The data is not displayed correctly

### ISSUE THREAD

**Issue by AnnaDidiaieva** [ita-social-projects/OoS-Frontend#923]
**Environment:** Windows 10 Corporate LTSC 64-bit, Google Chrome v98.0.4758.82
**Reproducible:** always
**Build found:** Frontend: gcp-0.0.53, Backend: gcp-0.0.112

**Preconditions**
1. Follow link https://oos.dmytrominochkin.cloud/#/
2. Log into system as a SP (e.g. 'email'="[tester2@gmail.com](mailto:tester2@gmail.com)", 'Password'="1qaz@WSX").
3. Select 'Інформація про заклад' in the menu bar at the top right corner.

**Steps to reproduce**
Look at the 'Опис' section.

**Actual result**
'Опис' text is not displayed according to the mock-up.
![юай слова2](https://user-images.githubusercontent.com/97879289/153879369-91ae6d05-7fb0-48a6-9192-f959cf9085db.jpg)

**Expected result**
The 'Опис' should be displayed as 'Про заклад' according to the mock-up.
![юай слова2а](https://user-images.githubusercontent.com/97879289/153879533-26ad71ac-b742-4292-8ac0-ed568d1d7a98.jpg)

**User story and test case links**
User story https://github.com/ita-social-projects/OoS-Backend/issues/236
Test case: [OS-276](https://jira.softserve.academy/browse/OS-276)

**Labels to be added**
Bug, pri: very low, severity: trivial, UI

**Comment by OksanaGuz** [comment]
Bug is already fixed. https://github.com/ita-social-projects/OoS-Frontend/issues/984
