### ISSUE TITLE
['Редагування закладу' page] Buttons are not displayed correctly

### ISSUE THREAD

**Issue by AnnaDidiaieva** [ita-social-projects/OoS-Frontend#924]
**Environment:** Windows 10 Corporate LTSC 64-bit, Google Chrome v98.0.4758.82
**Reproducible:** always
**Build found:** Frontend: gcp-0.0.53, Backend: gcp-0.0.112

**Preconditions**
1. Follow link https://oos.dmytrominochkin.cloud/#/
2. Log into system as a SP (e.g. 'email'="[tester2@gmail.com](mailto:tester2@gmail.com)", 'Password'="1qaz@WSX").
3. Select 'Інформація про заклад' in the menu bar at the top right corner.
4. Click on the 'Редагувати' button of the 'ІНФОРМАЦІЯ ПРО ЗАКЛАД' tab.

**Steps to reproduce**
Look at the buttons at the bottom of the 'Редагування закладу' pages.

**Actual result**
1. 'Зберегти' button is not displayed according to the mock-up.
![зберегти нет](https://user-images.githubusercontent.com/97879289/153881115-8f232f06-cb4b-4d77-83cb-f7a0cc7da9f5.jpg)
2. 'Скасувати', 'Назад', 'Далі', 'Зберегти' buttons are not displayed in uppercase letters.
![кнопки на сайтк](https://user-images.githubusercontent.com/97879289/153881975-65bd8a7f-483e-471a-9948-c790783935db.jpg)

**Expected result**
1. The 'Завершити' button should be displayed as 'Зберегти' according to the mock-up.
![зберегти есть](https://user-images.githubusercontent.com/97879289/153881139-5f8746c3-3f9a-480f-91af-f0d96bb1d935.jpg)
2. The 'Скасувати', 'Назад', 'Далі', 'Зберегти' buttons should be displayed in uppercase letters according to the mock-up.
![кнопки должні](https://user-images.githubusercontent.com/97879289/153881956-8e8387a1-2caa-4573-9359-199e51269fac.jpg)

**User story and test case links**
User story https://github.com/ita-social-projects/OoS-Backend/issues/236
Test case: [OS-277](https://jira.softserve.academy/browse/OS-277)

**Labels to be added**
Bug, pri: very low, severity: trivial, UI

**Comment by AnnaDidiaieva** [comment]
@perepichai 
The bug is still reproducible.
Please check the 'Зберегти' 'Скасувати', 'Назад', 'Далі', buttons UI. Expected result: 1) The 'Завершити' button should be displayed as 'Зберегти' according to the mock-up. 2) All buttons should be displayed in uppercase letters according to the mock-up.

**Comment by perepichai** [comment]
@AnnaDidiaieva try again, please. There was deploying issue

**Comment by AnnaDidiaieva** [comment]
Verified
