### ISSUE TITLE
[Search page] The ‘Введіть назву гуртка, школи’ placeholder is cut off in the ‘Search’ field 

### ISSUE THREAD

**Issue by hanna-lenko** [ita-social-projects/OoS-Frontend#927]
**Environment:** Win10 v21H2 64-bit, Chrome v 98.0.4758.82
**Reproducible:** always
**Build found:** frontend: gcp-0.0.53, backend: gcp-0.0.112

**Preconditions**

- Go to OoS (https://oos.dmytrominochkin.cloud/#/)
- Log into system as Parent (e.g. 'Email'="dub@gmail.com", 'Password'="Qwert1!")
- Go to the main page and click ‘Найпопулярніші гуртки’ hyperlink for UI verification of the ‘Search’ page.

**Steps to reproduce**

1. Check that the ‘Search’ field contains a placeholder with a grey-colored text: ‘Введіть назву гуртка, школи’

**Actual result**
The ‘Введіть назву гуртка, школи’ placeholder is cut off in the ‘Search’ field

![image](https://user-images.githubusercontent.com/97878413/154034277-6ba60b39-3ac6-497d-ba4e-52b3e83d9e66.png)

**Expected result**
The ‘Введіть назву гуртка, школи’ placeholder is displayed completely
The design: https://www.figma.com/file/YRYP4zAAchOyYMgdoeP782/MoE-%7C-Dev-Team?node-id=1%3A3537 

![image](https://user-images.githubusercontent.com/97878413/154034396-b53a7066-9e80-48bb-ab0d-8ae3112307bb.png)

**User story and test case links**
User story [#23](https://github.com/ita-social-projects/OoS-Backend/issues/23)
Test case [OS-260](https://jira.softserve.academy/browse/OS-260)

**Labels to be added**
"Bug", "pri: very low", "severity: trivial", Type "UI"

**Comment by hanna-lenko** [comment]
Verified, closed

**Comment by hanna-lenko** [comment]
@litvinets The bug is reproduced again

**Comment by OksanaGuz** [comment]
Verified.
