### ISSUE TITLE
[Search page] The typo in ‘Очистити фільтри’ button on the ‘Search’ page

### ISSUE THREAD

**Issue by hanna-lenko** [ita-social-projects/OoS-Frontend#928]
**Environment:** Win10 v21H2 64-bit, Chrome v 98.0.4758.82
**Reproducible:** always
**Build found:** frontend: gcp-0.0.53, backend: gcp-0.0.112

**Preconditions**
- Go to OoS (https://oos.dmytrominochkin.cloud/#/)
- Log into system as Parent (e.g. 'Email'="dub@gmail.com", 'Password'="Qwert1!")
- Go to the main page and click ‘Найпопулярніші гуртки’ hyperlink for UI verification of the ‘Search’ page.

**Steps to reproduce**
1. Verify spelling.

**Actual result**
The ‘Очистити фільтри’ button does not meet the design

![image](https://user-images.githubusercontent.com/97878413/154036170-a3618a8d-0b91-4faf-a84a-e77e7bb213df.png)

**Expected result**
The word ‘фільтри’ - all lowercase letters 
The design: https://www.figma.com/file/YRYP4zAAchOyYMgdoeP782/MoE-%7C-Dev-Team?node-id=1%3A3537 

**User story and test case links**
User story [#23](https://github.com/ita-social-projects/OoS-Backend/issues/23)
Test case [OS-260](https://jira.softserve.academy/browse/OS-260)

**Labels to be added**
"Bug", "pri: very low", "severity: trivial", Type "UI"

**Comment by hanna-lenko** [comment]
The same defect in the 'Обрати вік' field

![image](https://user-images.githubusercontent.com/97878413/154064963-89405264-fcad-4ca6-9c74-186c99ae28e8.png)

**Comment by litvinets** [comment]
fixede!

**Comment by hanna-lenko** [comment]
Verified and closed
