### ISSUE TITLE
['Редагування закладу' page] The data is not displayed correctly in the 'Інформація про заклад' section

### ISSUE THREAD

**Issue by AnnaDidiaieva** [ita-social-projects/OoS-Frontend#929]
**Environment:** Windows 10 Corporate LTSC 64-bit, Google Chrome v98.0.4758.82
**Reproducible:** always
**Build found:** Frontend: gcp-0.0.53

**Preconditions**
1. Follow link https://oos.dmytrominochkin.cloud/#/
2. Log into system as a SP (e.g. 'email'="[tester2@gmail.com](mailto:tester2@gmail.com)", 'Password'="1qaz@WSX").
3. Select 'Інформація про заклад' in the menu bar at the top right corner.
4. Click on the 'Редагувати' button of the 'ІНФОРМАЦІЯ ПРО ЗАКЛАД' tab.

**Steps to reproduce**
Look at the 'Інформація про заклад' section of the 'Редагування закладу' page.

**Actual result**
'ЄДРПОУ/ІПН' text is not displayed according to the mock-up.
![юай слова3](https://user-images.githubusercontent.com/97879289/154041759-7d3bd231-ef46-4756-a73e-e7d16ad95dd7.jpg)

**Expected result**
The 'ІПН' should be displayed as 'ЄДРПОУ/ІПН' according to the mock-up.
![юай слова3а](https://user-images.githubusercontent.com/97879289/154041745-63554ad8-8b41-4fa6-8ba5-f3971c37f828.jpg)

**User story and test case links**
User story https://github.com/ita-social-projects/OoS-Backend/issues/236
Test case: [OS-277](https://jira.softserve.academy/browse/OS-277)

**Labels to be added**
Bug, pri: very low, severity: trivial, UI

**Comment by perepichai** [comment]
this is because when "Тип організації" is "ФОП" then "ІПН" is displayed, if no then "ЄДРПОУ". We have to decide if we need to apply this logic everywhere. What do you think @litvinets ?

**Comment by AnnaDidiaieva** [comment]
Verified
