### ISSUE TITLE
['Редагування закладу' page] The data is not displayed correctly in the 'Опис' section

### ISSUE THREAD

**Issue by AnnaDidiaieva** [ita-social-projects/OoS-Frontend#930]
**Environment:** Windows 10 Corporate LTSC 64-bit, Google Chrome v98.0.4758.82
**Reproducible:** always
**Build found:** Frontend: gcp-0.0.53

**Preconditions**
1. Follow link https://oos.dmytrominochkin.cloud/#/
2. Log into system as a SP (e.g. 'email'="[tester2@gmail.com](mailto:tester2@gmail.com)", 'Password'="1qaz@WSX").
3. Select 'Інформація про заклад' in the menu bar at the top right corner.
4. Click on the 'Редагувати' button in the 'Опис' section of the 'ІНФОРМАЦІЯ ПРО ЗАКЛАД' tab.

**Steps to reproduce**
Look at the 'Опис' section of the 'Редагування закладу' page.

**Actual result**
There is no character counter with a maximum of 2000 symbols to the right of the 'Опис' field.
![нет цифры описа1](https://user-images.githubusercontent.com/97879289/154043188-52c0aa07-a9a8-4db1-948f-b678cd8e92b6.jpg)

**Expected result**
There is a character counter with a maximum of 2000 symbols to the right of the 'Опис' field.
![нет цифры описа](https://user-images.githubusercontent.com/97879289/154043207-5f5ba452-3e58-4a38-b970-fe4f598943a4.jpg)

**User story and test case links**
User story https://github.com/ita-social-projects/OoS-Backend/issues/236
Test case: [OS-277](https://jira.softserve.academy/browse/OS-277)

**Labels to be added**
Bug, pri: very low, severity: trivial, UI

**Comment by LeraKornienko** [comment]
done

**Comment by AnnaDidiaieva** [comment]
Verified
