### ISSUE TITLE
[Workshop page] Indent of the text from the logo is different from the rest in unit "Контакти"

### ISSUE THREAD

**Issue by ladikdadik** [ita-social-projects/OoS-Frontend#933]
**Environment:** Windows 10 x86(64), Opera GX 82.0.4227.50
**Reproducible:** always
**Build found:** Frontend: gcp-0.0.50, Backend: gcp-0.0.101

**Preconditions**
1. Go to main page https://oos.dmytrominochkin.cloud/#/
2. Find section/group with link to school`s website

**Steps to reproduce**
1. Go to details, by clicking on "Детальніше" button
2. Pay attention to indent of text from the logo in hyperlink to school`s website

![image](https://user-images.githubusercontent.com/97900899/154046186-c76328cb-6678-4839-835d-ac9fe7e3df52.png)
![image](https://user-images.githubusercontent.com/97900899/154046197-bf8ca924-edc5-4749-bf46-2dc510750cb1.png)

**Actual result**
The indent of text from the logo in hyperlink to school`s website is shorter than indent of rest elements in unit "Контакти"

**Expected result**
The indent of text from the logo in hyperlink to school`s website is the same to rest elements in unit "Контакти"

**User story and test case links**
"User story #58" https://github.com/ita-social-projects/OoS-Backend/issues/58
[Test case] (https://jira.softserve.academy/browse/OS-192)

**Labels to be added**
"Bug", Priority ("pri: "), Severity ("severity:"), Type ("UI, "Functional"), "API" (for back-end bugs).

**Comment by hanna-lenko** [comment]
Verified and closed
