### ISSUE TITLE
['Редагування закладу' page] Mandatory fields are not displayed correctly

### ISSUE THREAD

**Issue by AnnaDidiaieva** [ita-social-projects/OoS-Frontend#934]
**Environment:** Windows 10 Corporate LTSC 64-bit, Google Chrome v98.0.4758.82
**Reproducible:** always
**Build found:** Frontend: gcp-0.0.53

**Preconditions**
1. Follow the link https://oos.dmytrominochkin.cloud/#/
2. Log into system as a SP (e.g. 'email'="[tester2@gmail.com](mailto:tester2@gmail.com)", 'Password'="1qaz@WSX").
3. Select 'Інформація про заклад' in the menu bar at the top right corner.
4. Click on the 'Редагувати' button of the 'ІНФОРМАЦІЯ ПРО ЗАКЛАД' tab.

**Steps to reproduce**
Look at red asterisks of the 'Редагування закладу' pages.

**Actual result**
There are gaps between the field names and the red asterisks.
![1фф](https://user-images.githubusercontent.com/97879289/154044583-da36d2e5-3601-450e-ad98-a53a97cd58bd.jpg)
![1в](https://user-images.githubusercontent.com/97879289/154044605-f25f7a89-6c9b-4ea5-9f96-1f88f1747edc.jpg)

**Expected result**
There shouldn't be any gaps between the field names and the red asterisks according to the mock-up.
![12а](https://user-images.githubusercontent.com/97879289/154044705-57cacca1-8a19-4638-92ca-8e4899633324.jpg)
![а](https://user-images.githubusercontent.com/97879289/154046408-4291a71f-0f63-4c69-a864-13f93ac2e7be.jpg)

**User story and test case links**
User story https://github.com/ita-social-projects/OoS-Backend/issues/236
Test case: [OS-277](https://jira.softserve.academy/browse/OS-277)

**Labels to be added**
Bug, pri: very low, severity: trivial, UI

**Comment by LeraKornienko** [comment]
done

**Comment by AnnaDidiaieva** [comment]
Verified
