### ISSUE TITLE
[Search page] The allocation of the ‘Workshop’ cards on the page does not meet the design

### ISSUE THREAD

**Issue by hanna-lenko** [ita-social-projects/OoS-Frontend#938]
**Environment:** Win10 v21H2 64-bit, Chrome v 98.0.4758.82
**Reproducible:** always
**Build found:** frontend: gcp-0.0.53, backend: gcp-0.0.112

**Preconditions**
- Go to OoS (https://oos.dmytrominochkin.cloud/#/)
- Log into system as Parent (e.g. 'Email'="dub@gmail.com", 'Password'="Qwert1!")
- Go to the main page and click ‘Найпопулярніші гуртки’ hyperlink for UI verification of the ‘Search’ page.

**Steps to reproduce**
1. Check the allocation of the ‘Workshop’ cards on the page

**Actual result**
The 8 ‘Workshop’ cards are displayed on the page (100% scale, screen resolution 1920 x 1080)
 
![image](https://user-images.githubusercontent.com/97878413/154068785-249855aa-ba1e-4644-a16b-86fa89004daa.png)

**Expected result**
The 9 ‘Workshop’ cards are displayed on the page
The design: https://www.figma.com/file/YRYP4zAAchOyYMgdoeP782/MoE-%7C-Dev-Team?node-id=1%3A3537  

![image](https://user-images.githubusercontent.com/97878413/154068835-532b5cab-4cb5-4420-bb0f-1268a27d8fae.png)

**User story and test case links**
User story [#23](https://github.com/ita-social-projects/OoS-Backend/issues/23)
Test case [OS-260](https://jira.softserve.academy/browse/OS-260)

**Labels to be added**
"Bug", "pri: very low", "severity: trivial", Type "UI"

**Comment by litvinets** [comment]
please, verify this story according to the new approach that we will display the amount of the cards according to the dropdown selection. check this issue 
https://github.com/ita-social-projects/OoS-Frontend/issues/1115

**Comment by litvinets** [comment]
also cards decided to be centered according to the BA

**Comment by OksanaGuz** [comment]
Verified.
