### ISSUE TITLE
[City] Wrong search results for incorrect city

### ISSUE THREAD

**Issue by OksanaGuz** [ita-social-projects/OoS-Frontend#939]
**Environment:** macOS Big Sur 11.5.1; Chrome version 97.0.4692.71
**Reproducible:** always

**Preconditions**
Follow link https://oos.dmytrominochkin.cloud/#/

**Steps to reproduce**
1. Set "Київ" city
2. Click on Search button
3. Type in the city field "укм2"
4. Click on Search button

**Actual result**
No error message. Search results for previous search is shown (For Kyiv location).

<img width="1378" alt="Снимок экрана 2022-02-15 в 15 27 10" src="https://user-images.githubusercontent.com/97882565/154071263-4e445943-2e6c-4c0d-a595-f3d3d64d1c2c.png">

**Expected result**
No search results for non-existent city.

**User story and test case links**
https://github.com/ita-social-projects/OoS-Backend/issues/41

**Labels to be added**
"Bug", Priority ("pri: low"), Severity ("severity: minor"), Type  "Functional")

**Comment by litvinets** [comment]
fixed!

**Comment by OksanaGuz** [comment]
Verified.
