### ISSUE TITLE
[Search page] The inconsistent pagination appears when searching for a workshop

### ISSUE THREAD

**Issue by hanna-lenko** [ita-social-projects/OoS-Frontend#940]
**Environment:** Win10 v21H2 64-bit, Chrome v 98.0.4758.82
**Reproducible:** always
**Build found:** frontend: gcp-0.0.53, backend: gcp-0.0.112

**Preconditions**
- Go to OoS (https://oos.dmytrominochkin.cloud/#/)
- Log into system as Parent (e.g. 'Email'="dub@gmail.com", 'Password'="Qwert1!")
- "Київ" region is selected
- Go to the main page and click ‘Найпопулярніші гуртки’ hyperlink 

**Steps to reproduce**
1.	Set ‘танці’ in the search field
2.	Click ‘Search’ button

**Actual result**
The 10 workshops are found, the pagination is broken – no workshop cards are displayed on pages 3-9
 
![image](https://user-images.githubusercontent.com/97878413/154072542-7758562b-1493-47fb-b7f3-7320265bd0fb.png)

![image](https://user-images.githubusercontent.com/97878413/154072560-72df752b-1a34-47a8-8e30-c624fae0301e.png)

**Expected result**
There are 2 pages with workshop cards

**User story and test case links**
User story [#23](https://github.com/ita-social-projects/OoS-Backend/issues/23)
Test case [OS-260](https://jira.softserve.academy/browse/OS-260)

**Labels to be added**
"Bug", "pri: low", "severity: minor", Type "UI"

**Comment by perepichai** [comment]
seems it was a backend issue. Now it works as expected.

**Comment by hanna-lenko** [comment]
Verified and closed
