### ISSUE TITLE
[UI] Markers on the map moving in wrong position

### ISSUE THREAD

**Issue by OksanaGuz** [ita-social-projects/OoS-Frontend#941]
**Environment:** macOS Big Sur 11.5.1; Chrome version 97.0.4692.71
**Reproducible:** always.

**Preconditions**

1. Follow link https://oos.dmytrominochkin.cloud/#/
2. Set "Київ" city
3. Click on Search button

**Steps to reproduce**
1. Click on the Map view.
2. Zoom out the map.
3. Take a look to the markers position.

**Actual result**
Kyiv Markers are located on the border with Belarus

<img width="959" alt="Снимок экрана 2022-02-15 в 15 39 37" src="https://user-images.githubusercontent.com/97882565/154073305-e9828284-a152-450b-b7e5-974b696b95bb.png">

**Expected result**
Markers are located in appropriate position

**Labels to be added**
"Bug", Priority ("pri: medium"), Severity ("severity: minor"), Type ("UI").

**Comment by litvinets** [comment]
I think this bug is not relevant anymore and can be closed.

**Comment by ViktoriiaHrytchyna** [comment]
This bug is not relevant anymore.
