### ISSUE TITLE
[Map] The incorrect name of the Crimea territory on the map when searching for a workshop

### ISSUE THREAD

**Issue by hanna-lenko** [ita-social-projects/OoS-Frontend#944]
**Environment:** Win10 v21H2 64-bit, Chrome v 98.0.4758.82
**Reproducible:** always
**Build found:** frontend: gcp-0.0.53, backend: gcp-0.0.114

**Preconditions**
- Go to OoS (https://oos.dmytrominochkin.cloud/#/)
- Go to the 'Search' page by clicking 'Переглянути всі' near 'Найпопулярніші гуртки'

**Steps to reproduce**
1. Select the map view by clicking 'Карта' button
2. Zoom in the map and go to the Crimea territory

**Actual result**
The incorrect name of the Crimea territory is displayed on the map. The name of settlements and other objects is in Russian while settlements in Khersonska oblast is in Ukrainian.

![image](https://user-images.githubusercontent.com/97878413/154310337-068fc38d-1527-47db-b0b9-b5ade98532d8.png)

![image](https://user-images.githubusercontent.com/97878413/154310358-da5dbe95-38d7-41ec-9f70-4a82fb5ce832.png)

**Expected result**
The Crimea is marked as the territory of Ukraine, all settlements and objects on the map are in Ukrainian

**User story and test case links**
User story [#23](https://github.com/ita-social-projects/OoS-Backend/issues/23)
Test case [OS-271](https://jira.softserve.academy/browse/OS-271)

**Labels to be added**
"Bug", "pri: very high", "severity: trivial"

**Comment by ViktoriiaHrytchyna** [comment]
This bug is not reproduced.
