### ISSUE TITLE
[Add child UI] The "ПІДТРИМКА" tab is absent on the page when the browser window is resized

### ISSUE THREAD

**Issue by AnnaDidiaieva** [ita-social-projects/OoS-Frontend#964]
**Environment:** Windows 10 Corporate LTSC 64-bit, Google Chrome v98.0.4758.102
**Reproducible:** always (also while adding child's information)
**Build found:** Frontend: gcp-0.0.54, Backend: gcp-0.0.115

**Preconditions**
1. Follow link https://oos.dmytrominochkin.cloud/#/
2. Log into system as parent: 'Email'="[dub@gmail.com](mailto:dub@gmail.com)", 'Password'="Qwert1!".
3. Select "Інформація про дитину" in the menu bar at the top right corner.
4. Click on the "Додати дитину" button.

**Steps to reproduce**
1. Resize the browser window to 200%.
2. Look at the header.

**Actual result**
The "ПІДТРИМКА" tab is absent on the 'ДОДАТИ ДАНІ ПРО ДИТИНУ' page when the browser window is resized to 200%.
https://user-images.githubusercontent.com/97879289/155177897-3d01aafb-ce9d-4e36-b9f0-67325c182cc8.mp4

**Expected result**
The "ПІДТРИМКА" tab is displayed at the 'ДОДАТИ ДАНІ ПРО ДИТИНУ' page.
![dwjdf](https://user-images.githubusercontent.com/97879289/155177847-a40915d2-b660-4390-bd1a-4163f6bbd34a.jpg)

**User story and test case links**
User story https://github.com/ita-social-projects/OoS-Frontend/issues/43
Test case: https://jira.softserve.academy/browse/OS-176

**Labels to be added**
Bug, pri: medium, severity: major, UI

**Comment by litvinets** [comment]
Fixed!
![image](https://user-images.githubusercontent.com/27493959/158156929-52f195e7-f80c-4cb6-be58-6ac2278bfb00.png)
