### ISSUE TITLE
[Add child] The 'ЗБЕРЕГТИ' button stays enabled when mandatory fields are empty

### ISSUE THREAD

**Issue by AnnaDidiaieva** [ita-social-projects/OoS-Frontend#965]
**Environment:** Windows 10 Corporate LTSC 64-bit, Google Chrome v98.0.4758.102
**Reproducible:** always
**Build found:** Frontend: gcp-0.0.54, Backend: gcp-0.0.115

**Preconditions**
1. Follow link https://oos.dmytrominochkin.cloud/#/
2. Log into system as parent: 'Email'="[dub@gmail.com](mailto:dub@gmail.com)", 'Password'="Qwert1!".
3. Select "Інформація про дитину" in the menu bar at the top right corner. 
4. Click on the "Додати дитину" button.

**Steps to reproduce**
1. Mark the "Додаючи дані про дитину я погоджуюсь з правилами користування та надаю згоду на обробку персональних даних" checkbox. 
2. Look at the 'ЗБЕРЕГТИ' button at the bottom of the page.

**Actual result**
The button 'ЗБЕРЕГТИ' is enabled when mandatory fields are empty.
![dccc](https://user-images.githubusercontent.com/97879289/155186280-a3da2d2d-93ab-46ca-801e-45e9d3d078ab.jpg)

**Expected result**
The button 'ЗБЕРЕГТИ' should be disabled when mandatory fields are empty.
![akmcakcmskdmc](https://user-images.githubusercontent.com/97879289/155186340-02f890f3-0edf-428e-8229-2e12f9c9afad.jpg)

**User story and test case links**
User story https://github.com/ita-social-projects/OoS-Frontend/issues/43
Test case: https://jira.softserve.academy/browse/OS-183

**Labels to be added**
Bug, pri: low, severity: minor, UI

**Comment by AnnaDidiaieva** [comment]
@Olya-web7 
The bug is still reproducible.
Please check the 'ЗБЕРЕГТИ' button's behavior. Expected result: The button 'ЗБЕРЕГТИ' should be disabled when mandatory fields are empty.

**Comment by Olya-web7** [comment]
![Позашкілля - Google Chrome](https://user-images.githubusercontent.com/79056080/160813844-3242206f-ac6e-4981-9be4-2e1985689ed2.jpg)

Please check, it should work

**Comment by AnnaDidiaieva** [comment]
@Olya-web7
The bug is still reproducible.
Please check the 'ЗБЕРЕГТИ' button's behavior without entering any data in the fields, only mark the "Додаючи дані про дитину я погоджуюсь з правилами користування та надаю згоду на обробку персональних даних" checkbox. The 'ЗБЕРЕГТИ' button is enabled. Expected result: The button 'ЗБЕРЕГТИ' should be disabled when mandatory fields are empty.
