### ISSUE TITLE
[Markers on the map] The appearance of the markers does not meets the design

### ISSUE THREAD

**Issue by OksanaGuz** [ita-social-projects/OoS-Frontend#970]
**Environment:** macOS Big Sur 11.5.1; Chrome version 99.0.4844.51.
**Reproducible:** always
**Build found:** 
[gcp-0.0.116](https://github.com/ita-social-projects/OoS-Backend/releases/tag/gcp-0.0.116)
[gcp-0.0.55](https://github.com/ita-social-projects/OoS-Frontend/releases/tag/gcp-0.0.55)

**Preconditions**

1. Follow link https://oos.dmytrominochkin.cloud/#/**

**Steps to reproduce**

1. Select "Київ" location
2. Click on Search button
3. Click on map view
4. Select any map marker
5. Take a look to the appearance of the markers

**Actual result**
The appearance of the markers does not meets the design
<img width="972" alt="Снимок экрана 2022-03-07 в 16 41 35" src="https://user-images.githubusercontent.com/97882565/157055586-41c0e199-291c-431d-84e7-afae4afffcf8.png">

**Expected result**
Markers appearance according to design.

<img width="642" alt="Снимок экрана 2022-03-07 в 16 41 56" src="https://user-images.githubusercontent.com/97882565/157055650-570e3946-97d2-475b-bca4-d73335ad6769.png">

**User story and test case links**
User story https://github.com/ita-social-projects/OoS-Backend/issues/92
Test case https://jira.softserve.academy/browse/OS-349

**Labels to be added**
"Bug", Priority ("pri: low"), Severity ("severity: trivial"), Type ("UI")

**Comment by LeraKornienko** [comment]
done
