### ISSUE TITLE
[Sp cabinet] "Тип закладу" block is missing in the description of institution

### ISSUE THREAD

**Issue by OksanaGuz** [ita-social-projects/OoS-Frontend#977]
**Environment:** macOS Big Sur 11.5.1; Chrome version 99.0.4844.51.
**Reproducible:** always.
**Build found:** 
[gcp-0.0.116](https://github.com/ita-social-projects/OoS-Backend/releases/tag/gcp-0.0.116)
[gcp-0.0.55](https://github.com/ita-social-projects/OoS-Frontend/releases/tag/gcp-0.0.55)

**Preconditions**

1. Follow link https://oos.dmytrominochkin.cloud/#/
2. Log in as SP Email: kamin@gmail.com; Password: Qwerty1!

**Steps to reproduce**
1. Go to "ОСОБИСТА ІНФОРМАЦІЯ" page by clicking in the top right corner drop-down list.
2. Click on "Інформація про заклад" tab.
3. Go to "Опис" section.

**Actual result**
"Статус" block is present instead of "Тип закладу" block.

<img width="694" alt="Снимок экрана 2022-03-09 в 18 56 18" src="https://user-images.githubusercontent.com/97882565/157491613-1fbf5fd6-1b95-4ba3-a439-ec7542d0801f.png">

**Expected result**
"Тип закладу" block is present according to design.

<img width="432" alt="Снимок экрана 2022-03-09 в 18 57 09" src="https://user-images.githubusercontent.com/97882565/157491649-0c425db1-b647-467b-9930-3a3705177758.png">

Out of scope - "Фото" block.

**User story and test case links**

US https://github.com/ita-social-projects/OoS-Backend/issues/173
TC https://jira.softserve.academy/browse/OS-354

**Labels to be added**
"Bug", Priority ("pri: low"), Severity ("severity: minor"), Type ("UI, "Functional")

**Comment by litvinets** [comment]
@OksanaGuz fixed!

**Comment by litvinets** [comment]
fixed

**Comment by OksanaGuz** [comment]
Verified.
