### ISSUE TITLE
[Search] Existing workshop does not shown in the search result page

### ISSUE THREAD

**Issue by OksanaGuz** [ita-social-projects/OoS-Frontend#978]
**Environment:**  macOS Big Sur 11.5.1; Chrome version 99.0.4844.51.
**Reproducible:** always.
**Build found:** 
[gcp-0.0.116](https://github.com/ita-social-projects/OoS-Backend/releases/tag/gcp-0.0.116)
[gcp-0.0.55](https://github.com/ita-social-projects/OoS-Frontend/releases/tag/gcp-0.0.55)

**Preconditions**

1. Use this SQL query to make sure that workshop exist:
 SELECT * FROM `Workshops` WHERE Title = "ГуртокГурток"

Or 

1. Log in as SP Email - kamin@gmail.com Password - Qwerty1!
2. Go to "Мої гуртки" (in the top right corner) and make sure that "ГуртокГурток" workshop is exists.

**Steps to reproduce**

1. Follow link https://oos.dmytrominochkin.cloud/#/
3. Select "Київ" location
4. Set search field "ГуртокГурток" and click search button

**Actual result**
This search returned no results
<img width="1344" alt="Снимок экрана 2022-03-10 в 15 48 39" src="https://user-images.githubusercontent.com/97882565/157675056-b531d1bc-5d3b-4769-8a8b-574f83837984.png">

**Expected result**
Workshop "ГуртокГурток" should be shown on the results page

**Labels to be added**
"Bug", Priority ("pri: high "), Severity ("severity: minor"), Type ("Functional")

**Comment by perepichai** [comment]
it was a backend issue. It is fixed for now but we have to check it from time to time.

**Comment by ViktoriiaHrytchyna** [comment]
This bug is not relevant anymore.
