### ISSUE TITLE
[UI] The order of sections is different from the design

### ISSUE THREAD

**Issue by OksanaGuz** [ita-social-projects/OoS-Frontend#981]
**Environment:** macOS Big Sur 11.5.1; Chrome version 99.0.4844.51.
**Reproducible:** always.
**Build found:** 
[gcp-0.0.116](https://github.com/ita-social-projects/OoS-Backend/releases/tag/gcp-0.0.116)
[gcp-0.0.55](https://github.com/ita-social-projects/OoS-Frontend/releases/tag/gcp-0.0.55)

**Preconditions**

1. Follow link https://oos.dmytrominochkin.cloud/#/
2. Log in as SP - Email: [kamin@gmail.com](mailto:kamin@gmail.com); Password: Qwerty1!

**Steps to reproduce**

1. Go to "ОСОБИСТА ІНФОРМАЦІЯ" page by clicking in the top right corner drop-down list
2. Take a look to the order of "Ім'я" and "Прізвище" sections

**Actual result**
The first name is shown first and then the last name.
<img width="751" alt="Снимок экрана 2022-03-10 в 18 31 51" src="https://user-images.githubusercontent.com/97882565/157710266-411493a9-df48-40c0-927a-8cfa2e94dc54.png">

**Expected result**
Last name should be first and then first name
<img width="743" alt="Снимок экрана 2022-03-10 в 18 33 08" src="https://user-images.githubusercontent.com/97882565/157710309-cc58e10c-a999-4e6f-b976-1c3fe7781844.png">

**User story and test case links**
US https://github.com/ita-social-projects/OoS-Backend/issues/173
TC https://jira.softserve.academy/browse/OS-358

**Labels to be added**
"Bug", Priority ("pri: low"), Severity ("severity: trivial"), Type "UIl"

**Comment by litvinets** [comment]
fixed!

**Comment by litvinets** [comment]
fixed!
