### ISSUE TITLE
[SP Заяви] Not enough information about child is shown

### ISSUE THREAD

**Issue by OksanaGuz** [ita-social-projects/OoS-Frontend#986]
**Environment:** macOS Big Sur 11.5.1; Chrome version 99.0.4844.51.
**Reproducible:** always.
**Build found:**
[gcp-0.0.116](https://github.com/ita-social-projects/OoS-Backend/releases/tag/gcp-0.0.116)
[gcp-0.0.55](https://github.com/ita-social-projects/OoS-Frontend/releases/tag/gcp-0.0.55)

**Preconditions**
Follow link https://oos.dmytrominochkin.cloud/#/
Log in as SP Email: [kamin@gmail.com](mailto:kamin@gmail.com); Password: Qwerty1!

**Steps to reproduce**

1. Go to "Мої заяви" page by clicking in the top right corner drop-down list.
2. Hover cursor over child's name

**Actual result**
Information is different from the design.
<img width="494" alt="Снимок экрана 2022-03-11 в 13 33 46" src="https://user-images.githubusercontent.com/97882565/157859394-b68cfbbd-cc24-4a64-aff6-d1806bf9a86c.png">

**Expected result**
information fields should be the same as on the design.
<img width="535" alt="Снимок экрана 2022-03-11 в 13 35 53" src="https://user-images.githubusercontent.com/97882565/157859674-1a2cfa1e-4b76-44ec-b9db-98c34af3d95f.png">

**User story and test case links**
US https://github.com/ita-social-projects/OoS-Backend/issues/173
TC https://jira.softserve.academy/browse/OS-474

**Labels to be added**
"Bug", Priority ("pri: medium"), Severity ("severity: minor"), Type "Functional"

**Comment by Illya97** [comment]
Fixed
