### ISSUE TITLE
[SP Заяви] Typo in the "Очікує підтвердження" section 

### ISSUE THREAD

**Issue by OksanaGuz** [ita-social-projects/OoS-Frontend#989]
**Environment:** macOS Big Sur 11.5.1; Chrome version 99.0.4844.51.
**Reproducible:** always.
**Build found:**
[gcp-0.0.116](https://github.com/ita-social-projects/OoS-Backend/releases/tag/gcp-0.0.116)
[gcp-0.0.55](https://github.com/ita-social-projects/OoS-Frontend/releases/tag/gcp-0.0.55)

**Preconditions**

1. Follow link https://oos.dmytrominochkin.cloud/#/
2. Log in as SP Email: [kamin@gmail.com](mailto:kamin@gmail.com); Password: Qwerty1!

Steps to reproduce

1. Go to "Мої заяви" page by clicking on the top right corner drop-down list.
2. Take a look to "Очікує підтвердження" section.

**Actual result**
There is "Очікує підтвердження" section.
<img width="274" alt="Снимок экрана 2022-03-11 в 15 09 31" src="https://user-images.githubusercontent.com/97882565/157872525-a399116c-420d-4cc5-bab4-d3408a07d4f1.png">

**Expected result**
There should be "Очікують підтвердження" section.
<img width="243" alt="Снимок экрана 2022-03-11 в 15 09 51" src="https://user-images.githubusercontent.com/97882565/157872574-f754307a-cb9c-4fb8-b063-92b5dd7cc12d.png">

**User story and test case links**
US https://github.com/ita-social-projects/OoS-Backend/issues/173
TC https://jira.softserve.academy/browse/OS-474

**Labels to be added**
"Bug", Priority ("pri: low "), Severity ("severity: trivial"), Type "UI".

**Comment by litvinets** [comment]
fixed!
